### ISSUE TITLE
Docs: Binary classification notebook issues

### ISSUE THREAD

**Issue by thorbjornwolf** [online-ml/river#1031]
The [binary classification notebook in the docs](https://github.com/online-ml/river/blob/main/docs/introduction/getting-started/binary-classification.ipynb) needs a hand:
- The ImageSegments dataset is multiclass, not binary. It could be replaced with the Phishing dataset.
- The notebook should be re-run from the top and saved to get rid of the NameError in cell -2
- The `next steps` link at the bottom is broken (at least in [the website version](https://riverml.xyz/dev/introduction/getting-started/binary-classification/)), pointing to a nonexisting "next steps" page. Maybe it should point to https://riverml.xyz/dev/introduction/getting-started/concept-drift-detection/ ?

That being said, it is a nice introduction to `river` 🤗 Thanks a lot!

**Comment by MaxHalford** [comment]
Oh gosh, good catch. I don't know how those mistakes got through, they should have been caught by CI... I'll fix it very soon.

I'm glad you could acquainted with River nonetheless :)
