### ISSUE TITLE
'from river import metrics' gives  numpy.core.multiarray failed

### ISSUE THREAD

**Issue by paularindam** [online-ml/river#1047]
I am unable to remove this error. I tried re-installing river and numpy as some had suggested on stackoverflow. 
<img width="920" alt="Screen Shot 2022-10-02 at 2 23 47 PM" src="https://user-images.githubusercontent.com/2607180/193469753-a9254191-e280-476a-8d77-557095ac2dff.png">

**Comment by MaxHalford** [comment]
Can you share version information? (i.e. Python, numpy, river). We can't reproduce this issue without some more context.

**Comment by paularindam** [comment]
Please find the version information. FYI, I had tried a few different versions of numpy but none of them solved the issue.

**Comment by MaxHalford** [comment]
> Please find the version information

I'm not sure what you mean. Where should I find it?

**Comment by paularindam** [comment]
Hi

Please find here.

numpy = 1.22.4

river = 0.13.0

python= 3.9.5

Earlier, I had sent a screenshot but apparently you cannot see it. 

-Arindam

**Comment by MaxHalford** [comment]
Can you do `pip install numpy --upgrade`? I was able to reproduce your error, but it disappeared when I upgraded numpy to 1.23.x

**Comment by paularindam** [comment]
It seemed to work if I installed numpy after I installed river. Installing river after numpy rolls back numpy to 22.4.x. 

Anyways, thanks for the help. It seems to work after I restarted the kernel after upgrading numpy.

**Comment by MaxHalford** [comment]
I'm glad you fixed the issue.

It's super weird we're still getting this issue though, I thought I'd fixed it. I'll look into it.
