### ISSUE TITLE
Logistic Regression Prediction

### ISSUE THREAD

**Issue by SuleymanCetiner** [online-ml/river#1056]
Hello there. I have an issue for logistic regression.

from river import stream
from river import compose
from river import linear_model
from river import optim
from river import preprocessing
from river import metrics

datapath = "C/.. "

model = compose.Pipeline(
    preprocessing.StandardScaler(),
    linear_model.LogisticRegression(optim.SGD(lr=0.01))
    )
metric = metrics.ROCAUC()

for xi, yi in stream.iter_csv(datapath,target='Class'):

    # Test the current model on the new "unobserved" sample
    yi_pred = model.predict_proba_one(xi)

    # Update the running metric with the prediction and ground truth value
    metric.update(yi, yi_pred)

    # Train the model with the new sample
    model.learn_one(xi, yi)

print(f'ROC AUC: {metric}')

![image](https://user-images.githubusercontent.com/38746955/194554512-b4d64dbb-29df-4aa5-abc7-36ea13ab7940.png)

And i got this error. My inputs are float and output is 'categorical 0 and 1. What should be done to overcome this ? 
Thanks for helping me.

**Comment by MaxHalford** [comment]
Hello there. It seems to me that your features are of type `str`, not of type `float`. Maybe that's the issue?

By default, the `stream.iter_csv` function doesn't parse your data into floats. But can parse them yourself with the `converters` parameter. [Check out the docs](https://riverml.xyz/0.13.0/api/stream/iter-csv/).

We could/should probably add default parsing of strings to numbers, I'll look into it :)

**Comment by SuleymanCetiner** [comment]
Hello,

No,i already converted to all data into float,also i already used converters dictionary structure.
Yep, i didn't added that missing parts,i mean converts part so it is misunderstood.
Thanks anyway !

**Comment by MaxHalford** [comment]
Hey again. I'm not sure I follow, does your code work now?

**Comment by SuleymanCetiner** [comment]
Hi,no,does not work for now. I will try different things to make it worked.

**Comment by MaxHalford** [comment]
Ok, feel welcome to ask us if you have a question.

**Comment by SuleymanCetiner** [comment]
Thank you, i will do !
