### ISSUE TITLE
Question/proposal regarding ADWIN clock

### ISSUE THREAD

**Issue by mvieth** [online-ml/river#1061]
Hi, I have a question about the clock implemented into the ADWIN drift detector (https://github.com/online-ml/river/blob/main/river/drift/adwin_c.pyx#L215). As I understand it, it will only check for drifts every 32nd time. My guess would be that this is done to increase the speed/performance of the detector, but I haven't found any mention about this in the original ADWIN paper. If you know more about this or can point me to a paper where the reason for this clock is given, that would be great.
My concern is that this clock period (32) will likely not fit for all scenarios, and there is no (easy) way for a user to change it. So I would propose to make this configurable, similar to the `delta` parameter. If you agree, I can create a pull request.
Thanks.

**Comment by MaxHalford** [comment]
I believe we already discussed moving back to a Python implementation for the sake of maintainability. But we decided the performance gain is worth keeping.

I would say that the required change is small enough to justify adding it to the Cython implementation. Especially considering the OP is offering to make a pull request :)

**Comment by smastelini** [comment]
I think the best compromise is to set `clock` based on the `bucket_size` then. I don't remember the details now, but I have a gut feeling these parameters should walk together :)

Feel free to open a PR @mvieth. I had missed that part hahaha

**Comment by mvieth** [comment]
Are you sure that there is a connection between the clock and the max number of buckets? [In the MOA code](https://github.com/Waikato/moa/blob/master/moa/src/main/java/moa/classifiers/core/driftdetection/ADWIN.java), there is no apparent connection, and the clock is set to 32 (independently from `MAXBUCKETS`).
Let's say the max number of buckets is 5, then the 32 new samples since the last check for concept change would fill all 5 buckets of size 1, all 5 buckets of size 2, and 4 of the 5 buckets of size 4 (assuming I understood the algorithm correcty :smile: ).
Another example, let's say the max number of buckets is 3 (then `2 ** 3 = 8`). The 8 samples since the last check for concept change would fill all 3 buckets of size 1, and almost but not completely all buckets of size 2.
I just don't see any logic in this. Could it be that it was just a coincidence that `MAXBUCKETS` was set to 5 and the clock to 32 in the MOA code, and they don't have any connection?

**Comment by smastelini** [comment]
Hi @mvieth. No, I'm not sure, TBH. Just recently I started delving a bit around the concept drift world, out of necessity 😅.

What I know is that both variables are hardcoded in the MOA code, and the paper does not defines`clock`.
You might be correct, and your explanation makes a lot of sense, but since we don't have a formal explanation, the best we can do is informed guesses.

In any case, setting the `bucket_size` should be accessible for the user. Let's expose both `bucket_size` and `clock`. What do you think?

When you do the PR, could you please run some benchmarks to evaluate the impact of the `clock` choice? In the future, we could even document some extra guidelines for ADWIN. Thanks for looking into that!

**Comment by mvieth** [comment]
> In any case, setting the `bucket_size` should be accessible for the user. Let's expose both `bucket_size` and `clock`. What do you think?

Yes, I think that is a good solution. `grace_period` and `min_window_length` too?

> When you do the PR, could you please run some benchmarks to evaluate the impact of the `clock` choice? In the future, we could even document some extra guidelines for ADWIN. Thanks for looking into that!

Sure, do you have some benchmark framework in mind or are you okay with an "informal" measurement :smile: 
What kind of guidelines do you mean? Something describing the effects of each parameter?

**Comment by smastelini** [comment]
> Yes, I think that is a good solution. grace_period and min_window_length too?

I forgot about those two. Good catch! Yes, if we are going expose the internal parameters, let's do it for real 😄 . I believe the ADWIN algorithm is fresher in your mind, so can you think of any corner cases that should be checked when setting the values of all these "new" hyperparameters in `__init__`? If so, we need to document that and (maybe) raise some `ValueError` exceptions if the user passes a value outside the valid range.

> Sure, do you have some benchmark framework in mind or are you okay with an "informal" measurement 😄
What kind of guidelines do you mean? Something describing the effects of each parameter?

Informal is okay for our case! I thought about varying a handful of values for each hyperparameter and checking detection delays. You can use synthetic data with abrupt drifts. Nothing fancy 😃 

This way, we can get a gist of how the hyperparameters influence the detection. Sounds reasonable, @mvieth ?

**Comment by MaxHalford** [comment]
The best is to implement some unit tests when possible. But don't go out your way, sometimes unit tests can be hard to write.

**Comment by MaxHalford** [comment]
Addressed in #1062. Thanks a ton @mvieth!

**Comment by mvieth** [comment]
Thanks for the fast review and the guidance!
