### ISSUE TITLE
Doc search is broken

### ISSUE THREAD

**Issue by cyrilou242** [online-ml/river#1064]
**river version**: river website - all versions

## Describe the bug
Hey, the search index at `https://riverml.xyz/${version}/search/search_index.json` does not exists. 
This makes the search experience broken on the doc website. 

## Steps/code to reproduce
- Go to the doc website https://riverml.xyz/0.13.0/
- Type something in the search bar.

A 404 on `https://riverml.xyz/0.13.0/search/search_index.json` happens, making search unavailable.

**Comment by MaxHalford** [comment]
Yep I believe it's because we're using a broken version of mkdocs-material. I'll release a new version soon, hopefully by tomorrow evening. Thanks for opening an issue!

**Comment by cyrilou242** [comment]
Thanks @MaxHalford!

**Comment by MaxHalford** [comment]
Fixed!
