### ISSUE TITLE
Bandit-based Classifier selection not Implemented

### ISSUE THREAD

**Issue by mutazat** [online-ml/river#1122]
Bandit-based classification model selection is not implemented while it appears in one of your tutorial videos on YouTube.

**Comment by MaxHalford** [comment]
What tutorial was that? It's possible but I can't remember. Also feel free to contribute :)

**Comment by mutazat** [comment]
Thank for your reply.

It is in this video:

https://youtu.be/nzFTmJnIakk

Best regards

**Comment by MaxHalford** [comment]
Ok not sure what you part you mean, but anyway I added an entry to the roadmap.
