### ISSUE TITLE
learn_many of OneClassSVM has Problem!

### ISSUE THREAD

**Issue by hesamgh77** [online-ml/river#1153]
Hello 

I think learn_many of OneClassSVM has a Problem!
I used window of size=100 with learn_many of OCSVM but it did not work! 
please see this Code in python3.8:

```
from river import anomaly
from river import datasets
from river import metrics
from river import preprocessing
import pandas as pd

model = anomaly.QuantileFilter(
	anomaly.OneClassSVM(nu=0.2),
	q=0.995
)
auc = metrics.ROCAUC()

windows_size = 100
x_list = []
y_list = []
x_windows = pd.DataFrame()
y_series = pd.Series()
count = 0

for x, y in datasets.CreditCard().take(2500):
	score = model.score_one(x)
	is_anomaly = model.classify(score)
	auc = auc.update(y, is_anomaly)
	
	x_list.append(x)
	y_list.append(y)
	count += 1
	if count == windows_size:
		count = 0
		x_windows = pd.DataFrame(x_list)
		y_series = pd.Series(y_list)
		model.anomaly_detector = model.anomaly_detector.learn_many(x_windows)
		x_list = []
		y_list = []

print(auc)
```

at the end ROCAUC = 50.00% !
with `learn_one` at [https://riverml.xyz/0.13.0/api/anomaly/OneClassSVM/](url)  ROCAUC = 74.68% !

what is problem?

Thank you all

**Comment by hesamgh77** [comment]
and instead of using 
`model.anomaly_detector = model.anomaly_detector.learn_many(x_windows)`

i check this code too:
`model = model.learn_many(x_windows)`

and this error occurred:
`AttributeError: 'QuantileFilter' object has no attribute 'learn_many'`

**Comment by MaxHalford** [comment]
Hey there. The `learn_one` and `learn_many` are not equivalent. If you train on `n` samples with `learn_many`, you won't get the same model state as training individually on the `n` samples with `learn_one`.

>  AttributeError: 'QuantileFilter' object has no attribute 'learn_many'

Indeed, anomaly filters don't support `learn_many` yet. It's not a bug, it's just something we haven't implemented yet.

**Comment by hesamgh77** [comment]
Thank you so much dear @MaxHalford
