### ISSUE TITLE
river 0.1.0 issue

### ISSUE THREAD

**Issue by thanaswetha15** [online-ml/river#1156]
Hi ,

I am getting below error while importing **river 0.1.0** package. Can you please help.
were you able to get everything working? Can you share the root cause of the problem?

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10332\1863907629.py in <module>
----> 1 from river import metrics
      2 from river import stream
      3 from river import tree,neighbors,naive_bayes,ensemble,linear_model
      4 from river.drift import DDM, ADWIN,EDDM,HDDM_A,HDDM_W,KSWIN,PageHinkley
      5 

~\anaconda3\lib\site-packages\river\__init__.py in <module>
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,

~\anaconda3\lib\site-packages\river\cluster\__init__.py in <module>
      1 """Unsupervised clustering."""
----> 2 from .clustream import CluStream
      3 from .dbstream import DBSTREAM
      4 from .denstream import DenStream
      5 from .k_means import KMeans

~\anaconda3\lib\site-packages\river\cluster\clustream.py in <module>
      2 from abc import ABCMeta
      3 
----> 4 from river import base, cluster, utils
      5 
      6 EPSILON = 0.00005

~\anaconda3\lib\site-packages\river\utils\__init__.py in <module>
      7 from .sdft import SDFT
      8 from .skyline import Skyline
----> 9 from .vectordict import VectorDict
     10 from .window import SortedWindow, Window
     11 

ModuleNotFoundError: No module named 'river.utils.vectordict'

**Comment by MaxHalford** [comment]
Hey! I'm curious, why are you looking to install River v0.1.0? That's a really old version.

**Comment by MaxHalford** [comment]
Closing this, but feel free to reopen.

**Comment by thanaswetha15** [comment]
please reopen this,I forgot to open this previously

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
08/02/23,
16:17:37

**Comment by thanaswetha15** [comment]
I am doing a project in online stream data. so I require river 0.1.0 package.

**Comment by MaxHalford** [comment]
Version 0.1.0 of River doesn't even exist. It starts at version 0.7.0.
