### ISSUE TITLE
Hierarchical forecasting?

### ISSUE THREAD

**Issue by cdeterman** [online-ml/river#1177]
This is more of a general/documentation question.  I see the example of forecasting bikes but what about forecasting situations where there is a structured hierarchy to the time series data?  Is that supported or is that to be handled otherwise?

**Comment by MaxHalford** [comment]
Hey there. Do you have a link or more details to what exactly you mean? The answer is likely no, but I'm not exactly sure what you're referring to.

*PS: use [discussions](https://github.com/online-ml/river/discussions) next time, issues are more for bug reports.*

**Comment by cdeterman** [comment]
One example would be trying to predict electricity use across the United States.  But if you want to have the forecasts for both the country and also the individual states.  You could take it a step further and say counties within the states.  Clearly, there is a hierarchy to these different granularities that could inform upper/lower levels.  Does that make sense?

**Comment by MaxHalford** [comment]
Ah yes I see, interesting! My only experience with that setting is the [ASHRAE competition](https://www.kaggle.com/competitions/ashrae-energy-prediction), but there I only predicted at the most granular level, and then summed them up.
