### ISSUE TITLE
Inconsistent initialisation of quantile estimates

### ISSUE THREAD

**Issue by Tveten** [online-ml/river#1178]
## Versions
**river version**: 0.13.0
**Python version**: 3.9.16
**Operating system**: Windows 10 Pro

## Describe the bug
During initialisation of river.Quantile (the first five observations input to .update()), the values returned by Quantile.get() behave inconsistently with respect to the set quantile q. As you can see in the example below, the low quantile stays high despite observing lower values, while the high quantile drops. Exected behaviour: q.get() returns values such that Quantile(0.01) <= Quantile(0.99) for all sample sizes. Something like the regular sample quantile for sample sizes <= 5.

## Steps/code to reproduce
```python
from river.stats import Quantile

# Low quantile
q = Quantile(0.01)
for x in [5, 0, 0, 0, 0, 0, 0, 0]:
    q.update(x)
    print(q.get())
# 5.0
# 5.0
# 5.0
# 5.0
# 5.0
# 0.0

# High quantile:
q = Quantile(0.99)
for x in [5, 0, 0, 0, 0, 0, 0, 0]:
    q.update(x)
    print(q.get())
# 5.0
# 0.0
# 0.0
# 0.0
# 0.0
# 0.0
# 0.27777777777777773

```

**Comment by AdilZouitine** [comment]
First investigation, the inconsistent behavior was in pure python implementation too.
I'll try to fix that.

**Comment by AdilZouitine** [comment]
I made a fix in the following PR: https://github.com/online-ml/river/pull/1179

Thanks @Tveten, for the report 😄

**Comment by Tveten** [comment]
Fantastic, thanks for the quick fix!

**Comment by MaxHalford** [comment]
Added unit tests [here](https://github.com/online-ml/river/blob/main/river/stats/test_quantile.py) :)
