### ISSUE TITLE
Docs not working for version 0.15.0

### ISSUE THREAD

**Issue by prabhant** [online-ml/river#1192]
It seems like you had a bug with docs for version 0.15 as the docs are not loading on any of my devices. When I change the version to 0.14 in the URL does work. So looks like a doc build fail

**Comment by MaxHalford** [comment]
Not really sure what's going on. It could be a temporary issue with mkdocs-material. I'll try to find some time later in the week to debug.

**Comment by smastelini** [comment]
Hi @prabhant, do you face issues when building the docs or accessing the river website?

**Comment by prabhant** [comment]
Hi, I can't access the website

**Comment by smastelini** [comment]
That is strange. I can access the docs as usual from my Windows laptop and phone. Can you give us more information about your current setup?

**Comment by smastelini** [comment]
Yeap. I can confirm the issue. Nonetheless, the dev version seems to be working.

**Comment by MaxHalford** [comment]
Super weird. I suppose it's coming from mkdocs-material. Either we wait for a new version, either we try to rollback to a previous version.

**Comment by AllesMeins** [comment]
Have the same problem on Linux with Firefox and Chromium - the page just stays blank. But I can access the source-code and it seems to contain all the content. However it's complaining about this tag in the document header 
`<script defer
  src="[https://unpkg.com/@tinybirdco/flock.js](view-source:https://unpkg.com/@tinybirdco/flock.js)"
  data-host="https://api.tinybird.co"
  data-token="p.eyJ1IjogIjgwMGRiMTVkLWZmZWYtNDMzNy1hNGI5LWI1OWYxZGNiMjhlZSIsICJpZCI6ICIwNTBkNTc5ZC1lNDE5LTQzMDEtOTVkMi02MTE3M2QwN2UyYTQifQ.122DB6AHud_DFQQn2Hm31ySnTKNgWBc5XYDYdxuIDGI"
/>`

Especially the closing "/>" in the last line stating "Self-closing syntax (/>) used on a non-void HTML element. Ignoring the slash and treating as a start tag." Judging from the formatting of the source-code view it seems as if the Browser treats everything after as part of a script - thus not displaying it.

**Comment by MaxHalford** [comment]
Good catch @AllesMeins, that fixed it! Thanks 🙏
