### ISSUE TITLE
online PCA

### ISSUE THREAD

**Issue by leeauk21** [online-ml/river#1196]
https://scholar.google.com/citations?view_op=view_citation&hl=en&user=7gYXdo0AAAAJ&sortby=pubdate&citation_for_view=7gYXdo0AAAAJ:hqOjcs7Dif8C

**Comment by MaxHalford** [comment]
Looks interesting! Are you looking to contribute this?

Note some students have implemented 3 variants of PCA, see [here](https://github.com/ormarv/online_pca). We have to look into what offers the best tradeoff.
