### ISSUE TITLE
river 1.15 depedency conflict with numba 0.56

### ISSUE THREAD

**Issue by Tveten** [online-ml/river#1197]
Hey,

With river 1.15 I experience some dependency issues because it requires numpy >= 1.24.2. This is not compatible with any version of numba for example, which only supports numpy < 1.24. Is it intentional to require such a recent numpy version?

Versions:
python = 3.10
river = 1.15
numba=0.56

I'll be happy to share more details and a reproducible example if that's necessary.

**Comment by MaxHalford** [comment]
Hey! You mean version 0.15 of River right?

> Is it intentional to require such a recent numpy version?

Sadly yes... we've been facing weird numpy issues, in particular on Windows. Bumping to 1.24 seem to solve this issue, but we didn't identify the root cause.

**Comment by Tveten** [comment]
I mean 0.15, of course, sorry.

No worries, I just wanted to see whether there was a quick fix here or not. 

Thanks for the response.
