### ISSUE TITLE
I'm trying to use river in google colab. There's a version issue between the river and numpy (numba). I have been trying to install older versions of numpy. But in vain. I have included the error below. Thanks in advance. 

### ISSUE THREAD

**Issue by deepacmulimani** [online-ml/river#1207]
## Versions

**river version**:
**Python version**:
**Operating system**:

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
# Please do your best to provide a Minimal, Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example
```

**Comment by deepacmulimani** [comment]
from river import metrics

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
__init__.pxd in numpy.import_array()

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-8-4c14f35c9710> in <module>
----> 1 from river import metrics

1 frames
/usr/local/lib/python3.9/dist-packages/river/metrics/mutual_info.py in <module>
      4 
      5 from river import metrics
----> 6 from river.metrics.expected_mutual_info import expected_mutual_info
      7 
      8 __all__ = [

build/lib.linux-x86_64-cpython-38/river/metrics/expected_mutual_info.pyx in init river.metrics.expected_mutual_info()

__init__.pxd in numpy.import_array()

ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by MaxHalford** [comment]
Hello? Have you tried looking at #1138?

**Comment by deepacmulimani** [comment]
> Hello! Have you tried looking at #1138?

Thanks ....it's working.
