### ISSUE TITLE
Issue in Docs: Incorrect Releases Order

### ISSUE THREAD

**Issue by Dominastorm** [online-ml/river#1209]
The releases have currently been sorted in descending order. 
https://github.com/online-ml/river/blob/50bc0b70323cf2b385b20d9e6aa8c9dbfff594ac/docs/releases/.pages#L2

This however, doesn't work beyond version 0.9.0 because the string "0.10.0" < "0.9.0". Leading to a messed up order. 
![Screenshot from 2023-03-26 15-13-51](https://user-images.githubusercontent.com/43818888/227767876-4bfe26df-bec1-4829-8f1f-63e336fb53c9.png)

**Comment by MaxHalford** [comment]
Yep, I'm aware. Not sure how to fix it though. Feel free to contribute a fix :)

**Comment by MaxHalford** [comment]
Fixed in the next version!

![Screenshot 2023-04-30 at 17 49 53](https://user-images.githubusercontent.com/8095957/235362832-07449c4d-a469-47aa-be2b-fc4178e489c6.png)
