### ISSUE TITLE
DBSTREAM: recluster whenever needed

### ISSUE THREAD

**Issue by bmatschke** [online-ml/river#1211]
Currently in river.cluster.DBSTREAM, `predict_one()` calls the offline phase `_recluster()` no matter whether it is necessary or not. At the same time, the attributes `clusters`, `n_clusters`, `centers` are "public" and do not call `_recluster()` even if needed. As if it currently is expected to call `predict_one()` before `clusters`, `n_clusters`, `centers` are updated.

It seems more natural to do the offline phase precisely whenever it is needed.

To achieve this I propose to 
- add an attribute `_clustering_is_up_to_date`, which is set to True at the end of each `_recluster()` call, set to False whenever `learn_one()` is called, and that `_recluster()` returns early in case `_clustering_is_up_to_date` is already True, 
- make `clusters`, `n_clusters`, `centers` into "private" attributes `_clusters`, `_n_clusters`, `_centers`,
- add properties `clusters`, `n_clusters`, `centers` to DBSTREAM that first call `_recluster()` before returning their corresponding private attributes,
- include an underscore in front of all other attributes in DBSTREAM to signify them as private.

I can provide a PR.

**Comment by bmatschke** [comment]
The proposed code changes: https://github.com/bmatschke/river/tree/dbstream_recluster_whenever_needed

**Comment by MaxHalford** [comment]
I believe this is now implemented.
