### ISSUE TITLE
[Documentation] broken ./benchmarks Vegaplot csv file

### ISSUE THREAD

**Issue by julien-blanchon** [online-ml/river#1220]
The `binary_classification.csv`, `multiclass_classification.csv` and `regression.csv` seems to be not served anymore: https://riverml.xyz/0.15.0/benchmarks/

At first glance,

- `mkdocs_charts_plugin` is working well and try to render the vegaplot.
- the `render.py` glue code is working well and did expose the csv file (see https://github.com/online-ml/river/tree/gh-pages/0.15.0/benchmarks)
- However the `latest` redirection broke the link

-> https://riverml.xyz/0.15.0/benchmarks/multiclass_classification.csv is available
But
-> https://riverml.xyz/benchmarks/multiclass_classification.csv is not.

**Comment by MaxHalford** [comment]
Hello @julien-blanchon, thanks for letting us know! This is one of those tricky bugs that is difficult to reproduce locally.

@kulbachcedric I see we can do

```py
"data": {
      "values": df.to_dict(orient="records")
}
```

instead of this


```py
"data": {
      "url": f"benchmarks/{df_path.name}"
}
```

Is there any reason not to do this? I'm pretty sure this will fix the issue.

**Comment by kulbachcedric** [comment]
Hi @MaxHalford and @julien-blanchon,
thanks! 
The error can be fixed by the solution proposed by Max. However, the problem why I skipped it on my local machine is that the json for the Vega plot get huge and a little slow. 
But for now, I think it should do the job.

Best
Cedric
