### ISSUE TITLE
About online kernel learning

### ISSUE THREAD

**Issue by Kaslanarian** [online-ml/river#1224]
I haven't seen any implementation of online kernel learning, such as Forgetron and Projection. Will they be realized?

**Comment by MaxHalford** [comment]
Hello there. No those algorithms are not on the roadmap, currently. Have you had good performance with them? Do you think we should include them?

**Comment by Kaslanarian** [comment]
My experience tells me online learning with kernelized models often plays a role as a base learner with nonlinearity. Just like svm in `sklearn`, LinearSVM is obviously not enough.  I've seen some implementations such as [KOL](https://github.com/LIBOL/KOL), [Large-scale-kernel-learning](https://github.com/jingcoco/Online-Kernel-Learning) and [Online-Multiple-Kernel-Learning](https://github.com/jingcoco/Online-Multiple-Kernel-Learning). However, they are written with MATLAB or C++. I think it's necessary to fill the gap in this area.
