### ISSUE TITLE
Desicion function for OCSVM

### ISSUE THREAD

**Issue by hesamgh77** [online-ml/river#1229]
Hello
Output of OCSVM is a score without limit. Is there any way to calculate output of OCSVM within (0,1) ?

I want to compare result of OCSVM and HST with ROCAUC metric but output of OCSVM is not within (0,1) and can't use ROCAUC metric for OCSVM.

**Comment by MaxHalford** [comment]
I personally don't know how to do that. But I'm sure it's possible.

However, my intuition is that you still wouldn't be able to compare the scores with each other. The outputs would still be calibrated differently.
