### ISSUE TITLE
Bigger value of silhouette metric is better

### ISSUE THREAD

**Issue by josepaiva94** [online-ml/river#1236]
## Describe the bug

Silhouette metric should return `true` on `bigger_is_better()` as values closer to 1 indicate more cohesion and lower average distances from the points to their second-closest centroid.

Or did I misunderstood this?

**Comment by hoanganhngo610** [comment]
According to the definition of Silhouette metric provided in the book "Machine Learning for Data Stream" by Albert Bifet et al. (DOI [10.7551/mitpress/10654.001.0001](https://www.doi.org/10.7551/mitpress/10654.001.0001) , with online version at [https://moa.cms.waikato.ac.nz/book-html/](https://moa.cms.waikato.ac.nz/book-html/)), in section 9.1, 
- Cohesion is defined as the average distance from a point in the dataset to its assigned cluster centroid. The smaller the better.
- Silhouette is defined as "the ratio between cohesion and the average distances from the points to the second-closest centroid. 
From this information, we can see that the Silhouette calculation applied in the library is totally different from the Silhouette coefficient definition we usually see for the traditional machine learning methods. Moreover, the smaller this metric, the better the clustering result is.
