### ISSUE TITLE
TransformerProduct behavior

### ISSUE THREAD

**Issue by yolking** [online-ml/river#1238]
Hello, I am getting familiar with your library. I have an issue with TransformerProduct. You have an example:
```py
x = dict(
    a=0, b=1,  # group 1
    x=2, y=3   # group 2
)
group_1 = Select('a', 'b')
group_2 = Select('x', 'y')
product = group_1 + group_2 + group_1 * group_2
print(product.transform_one(x))
```
resulting in output
`{'b*y': 3, 'b*x': 2, 'a*y': 0, 'a*x': 0, 'y': 3, 'x': 2, 'b': 1, 'a': 0}`

Now let's try to change order
```py
product = group_1 * group_2 + group_1 + group_2
print(product.transform_one(x))
```
This results in
`{'b*y*b*y': 9, 'b*y*b*x': 6, 'b*y*a*y': 0, 'b*y*a*x': 0, 'b*x*b*y': 6, 'b*x*b*x': 4, 'b*x*a*y': 0, 'b*x*a*x': 0, 'a*y*b*y': 0, 'a*y*b*x': 0, 'a*y*a*y': 0, 'a*y*a*x': 0, 'a*x*b*y': 0, 'a*x*b*x': 0, 'a*x*a*y': 0, 'a*x*a*x': 0}`
What's completely different from what I wanted to get.

​Okay order may be one issue, but now what about 
```py
product = group_1 + group_1 * group_2
print(product.transform_one(x))
```
I get
`{'b*y*b': 3, 'b*y*a': 0, 'b*x*b': 2, 'b*x*a': 0, 'a*y*b': 0, 'a*y*a': 0, 'a*x*b': 0, 'a*x*a': 0}`
What's also wrong. 
It seems to me currently it interprets most use cases in a wrong way and calculates product of everything

**Comment by MaxHalford** [comment]
Good catch! I've fixed the issue in #1239.
