### ISSUE TITLE
website | dataset page returns 404

### ISSUE THREAD

**Issue by dberardo-com** [online-ml/river#1245]
https://riverml.xyz/api/datasets/ChickWeights

all datasets pages return 404

**Comment by MaxHalford** [comment]
That's normal, there's no version or latest in the URL. Where did you get that link from?

**Comment by dberardo-com** [comment]
from this page 
![image](https://github.com/online-ml/river/assets/65530457/84dcb3f1-35ee-4203-9478-377468fa5823)

**Comment by dberardo-com** [comment]
but then what is the right link ?

this one seems not to work either: https://riverml.xyz/0.16.0/api/datasets/WaterFlow

**Comment by MaxHalford** [comment]
Ok thanks, I've pin-pointed the issue. This will be fixed in 0.17, which I'm releasing right now.
