### ISSUE TITLE
EXP3 and ThompsonSampling Not Working with Bandit Classifier 

### ISSUE THREAD

**Issue by mutazat** [online-ml/river#1259]
I have tried running a BanditClassifier example in which the Exp3 policy is used. However, I have got an error related to the update method in the exp3.py file. The error is related to the following statement:

reward = reward_args[0]

IndexError: tuple index out of range

Below is the example I tried to run: 

from river import bandit
from river import datasets
from river import evaluate
from river import linear_model
from river import metrics
from river import model_selection
from river import optim
from river import preprocessing

models = [
    linear_model.LogisticRegression(optimizer=optim.SGD(lr=lr))
    for lr in [0.0001, 0.001, 1e-05, 0.01]
]

dataset = datasets.Phishing()
model = (
    preprocessing.StandardScaler() |
    model_selection.BanditClassifier(
        models,
        metric=metrics.Accuracy(),
        policy=bandit.Exp3(
            gamma=0.5,
            seed=42
        )
    )
)
metric = metrics.Accuracy()

evaluate.progressive_val_score(dataset, model, metric)

**Comment by MaxHalford** [comment]
Fixed in #1262!
