### ISSUE TITLE
Problem with reclustering in DBSTREAM

### ISSUE THREAD

**Issue by slvnwhrl** [online-ml/river#1265]
Hi there,

I had a close look at outcomes of the DBSTREAM algorithm, i.e., I would first learn the whole dataset (using `learn_one`) and then label the whole dataset (using `predict_one`). I realised that the number of micro-clusters always equals the number of macro-clusters. I think it has to do with the fact that, when creating macro-clusters in the `_recluster` method (more precisely, the `_generate_clusters_from_labels` method), the [macro-cluster is a shallow copy of the selected micro-cluster](https://github.com/online-ml/river/blob/b651af919de1880dd7a0935f1a79992bab231054/river/cluster/dbstream.py#L348). Subsequently, the merge operation changes the weight and center of the micro-clusters. In further `predict_one` calls, the weight of neighboring micro_clusters will be too high (and the centers will be similar) causing the shared density to be too low --> micro-clusters will not be merged.

To demonstrate this problem, here a visualization of a dataset with the current implementation for DBSTREAM showing the micro-clusters (with a radius=1):
![recluster_shallow_copy](https://github.com/online-ml/river/assets/24292116/61726b49-7088-479f-bbf3-56f6ca2cbfab)

And with deep copying the macro-clusters:
![recluster_deep_copy](https://github.com/online-ml/river/assets/24292116/a235d732-ed86-4be0-95a5-9d73cead66bd)

On a different note, I would also suggest to run the `_recluster` in `predict_one` only when a new data point is learnt (which would improve performance).

I hope this is an understandable explanation of the problem. I'd be happy to setup a PR if you'd like me to. Let me know how I can be of help. Thank you!! :)

**Comment by hoanganhngo610** [comment]
Thank you so much @MaxHalford ! @slvnwhr , would you mind sharing the code and synthetic dataset that you used for this example so that I can have a run again on my personal computer, or "play" around with the hyperparameters? I think what you have raised in your question is quite valid, and I want to verify it myself before going to the next steps.

**Comment by slvnwhrl** [comment]
> Thank you so much @MaxHalford ! @slvnwhrl , would you mind sharing the code and synthetic dataset that you used for this example so that I can have a run again on my personal computer, or "play" around with the hyperparameters? I think what you have raised in your question is quite valid, and I really hope I can verify it myself before going to the next steps.

Yes, sure. You can use this code:

```
import copy
import numpy as np
import plotly.graph_objects as go
import types

from river import cluster, stream


data = np.loadtxt("data.txt")

def _generate_clusters_from_labels(self, cluster_labels):
    """Adjusted method (deep copy of micro-cluster)"""
    # initiate the set for final clusters
    clusters = {}
    # generate set of clusters with the same label with the structure {j: micro_cluster_index}
    for i in range(max(cluster_labels.values()) + 1):
        j = 0
        mcs_with_label_i = {}
        for index, label in cluster_labels.items():
            if label == i:
                mcs_with_label_i[j] = self.micro_clusters[index]
                j += 1

        # generate a final macro-cluster from clusters with the same label using the
        # merge function of DBStreamMicroCluster
        macro_cluster = copy.deepcopy(mcs_with_label_i[0]) # DEEP copy micro cluster!
        for m in range(1, len(mcs_with_label_i)):
            macro_cluster.merge(mcs_with_label_i[m])

        clusters[i] = macro_cluster

    n_clusters = len(clusters)
    
    return n_clusters, clusters

shallow_clusterer = cluster.DBSTREAM()
deep_clusterer = cluster.DBSTREAM()
deep_clusterer._generate_clusters_from_labels = types.MethodType(_generate_clusters_from_labels, deep_clusterer)

for x, _ in stream.iter_array(data):
    shallow_clusterer.learn_one(x)
    deep_clusterer.learn_one(x)

for x, _ in stream.iter_array(data):
    shallow_clusterer.predict_one(x)
    deep_clusterer.predict_one(x)
    
for i, clusterer in enumerate([shallow_clusterer, deep_clusterer]):
    fig = go.Figure()

    # data points
    fig.add_trace(
        go.Scatter(
            mode='markers',
            x=data[:, 0],
            y=data[:, 1],
            marker=dict(
                size=3,
                color="#A7A6A7"
            ),
            showlegend=False
        )
    )

    # micro-clusters
    centers = set([(clusterer.micro_clusters[i].center[0], clusterer.micro_clusters[i].center[1])
                   for i in range(len(clusterer.micro_clusters))])
    circles = [dict(type="circle", x0=c[0]-0.5, y0=c[1]-0.5, x1=c[0]+0.5, y1=c[1]+0.5, line_width=2) for c in centers]
    fig.update_layout(shapes=circles, title=f"{'shallow' if i == 0 else 'deep'} macro-clusters")

    fig.show()
```
And I created a simple txt-file with numpy arrays for the data: [data.txt](https://github.com/online-ml/river/files/11787248/data.txt). Let me know if this is a problem or you need anything else.

**Comment by hoanganhngo610** [comment]
@slvnwhrl Thank you so much for pointing this error out! I have updated DBSTREAM using `copy.deepcopy` to copy selected micro-clusters to the set of macro clusters. 

Regarding the use of `_recluster`, actually, we design `learn_one()` and `predict_one()` so that the user can freely choose when and where the algorithm should learn new data points, or predict them. Currently, by leaving `_recluster` in the `predict_one()` function, this means that for every time we demand a new clustering result, we have to recluster before returning results, regardless of whether there is any new point learnt or not. Moreover, you can also refer to issue #1211 and PR #1213 for more context, as @MaxHalford previously said. Hope this helps
