### ISSUE TITLE
ARF background models training with poisson(6)

### ISSUE THREAD

**Issue by danielnowakassis** [online-ml/river#1266]
From the BaseForestMember class of AdaptiveRandomForest, I've noticed that : 

```python
def learn_one(self, x: dict, y: base.typing.Target, *, sample_weight: int, n_samples_seen: int):
        self.model.learn_one(x, y, sample_weight=sample_weight)

        if self.background_learner:
            # Train the background learner
            self.background_learner.model.learn_one(x=x, y=y, sample_weight=sample_weight)
```

The background model apparently is receiving the sample weight from Poisson(6)

but in the original implementation of ARF in the MOA framework

```java
public void trainOnInstance(Instance instance, double weight, long instancesSeen) {
            Instance weightedInstance = instance.copy();
            weightedInstance.setWeight(instance.weight() * weight); //train with sample_weight = poisson(6)
            this.classifier.trainOnInstance(weightedInstance);
            
            if(this.bkgLearner != null)
                this.bkgLearner.classifier.trainOnInstance(instance); //train with sample_weight = 1 
```

one can see that the background model trains with sample_weight = 1.

Is there any part of the code that i did not see that trains background models with sample_weight = 1? If the background model is training with poisson(6) it is making ARF more expensive.

This might happen with StreamingRandomPatches also.

**Comment by smastelini** [comment]
Hi @danielnowakassis, I confirm that both the foreground and background models in River use Poisson(6) for training. I was not aware of this difference in MOA. As far as I remember, the ARF paper doesn't mention this tweak, and I can't see clear benefits for prediction apart from computational cost reduction. Am I wrong?

**Comment by danielnowakassis** [comment]
The pseudocode presented in the paper does not match with the implementation in MOA. In the pseudocode background models receive poisson(6). I think this could be a option for the user to choose between poisson and 1.

**Comment by smastelini** [comment]
Hmm, maybe you could run some simple benchmarks and see how River's ARF fares against MOA. I still don't see the benefits in shutting down online bagging from a diversity induction standpoint. But I am intrigued to understand the reasons why this happens in MOA. Any thoughts, @danielnowakassis?

**Comment by danielnowakassis** [comment]
@smastelini I think only Heitor Gomes knows why 😅.
