### ISSUE TITLE
Stateless inference for the last pipeline step

### ISSUE THREAD

**Issue by ColdTeapot273K** [online-ml/river#1269]
## Versions

**river version**: current upstream
**Python version**: 3.10
**Operating system**: Fedora 38

## Describe the bug

Problem:

The current use of stateless inference context manager (https://github.com/online-ml/river/blob/main/river/compose/pipeline.py#L98) for a pipeline which consists only of unsupervised transformers (e.g. `StandardScaler`, `OneHotEncoder`) doesn't protect from calls to `learn_*` on the last transformer. 

Usecase:

Developing online models with other frameworks while leveraging handy online abstractions of `river` for pre-processing.

## Steps/code to reproduce

```python

import io
import logging

import river
from river import compose, datasets, linear_model, preprocessing, utils

model = compose.Select("ordinal_date", "gallup") | preprocessing.StandardScaler()


logger = logging.getLogger()
logger.setLevel(logging.DEBUG)


logs = io.StringIO()
sh = logging.StreamHandler(logs)
sh.setLevel(logging.DEBUG)
logger.addHandler(sh)


class_condition = lambda x: x.__class__.__name__ in ("StandardScaler", "LinearRegression")


with river.utils.log_method_calls(class_condition), river.compose.pure_inference_mode():
    for x, y in datasets.TrumpApproval().take(1):
        _ = model.transform_one(x)

print(logs.getvalue())
# desired output:
# StandardScaler.transform_one

# actual output:
# StandardScaler.learn_one
# StandardScaler.transform_one
```

---

P.S. To be frank, me and my team find it very questionable that `Pipeline` by default has the side effect of `learn_*` during inference (`predict_*`/`transform_*`). For we'd like to correctly estimate, how the model responds to unknown categorical features/values until in has been fit to fresh data. From my personal experience, systems-engineering-wise, instant model fit, mentioned in the docstrings, is more of a luxury than a common opportunity.

If anything, it's the side effect behaviour that should be optional, not vice-versa. Plus i don't think this side-effect is emphasized enough in the docs. 

Anyway, respecting the authors' vision i'asking for just a small adjustment.

**Comment by MaxHalford** [comment]
I'm actually convinced. I agree that the current behavior is too advanced, and should be opt-in. I'll implement the necessary changes, and see what breaks (probably a lot of stuff) :)
