### ISSUE TITLE
ARFClassifier throws error when using CrossEntropy metric

### ISSUE THREAD

**Issue by jpfeil** [online-ml/river#1272]
## Versions

**river version**: 0.18.0
**Python version**: 3.9.1
**Operating system**: Ubuntu 22.04

## Describe the bug

I tried using CrossEntropy as the metric for training the ARFClassifier, but I get an AttributeError: 'NoneType' object has no attribute 'items'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 3>()
      1 model = forest.ARFClassifier(metric=metrics.CrossEntropy())
----> 3 model.learn_one({"x": 1}, True)

File ~/miniconda3/lib/python3.9/site-packages/river/forest/adaptive_random_forest.py:78, in BaseForest.learn_one(self, x, y, **kwargs)
     75 y_pred = model.predict_one(x)
     77 # Update performance evaluator
---> 78 model.metric.update(y_true=y, y_pred=y_pred)
     80 k = poisson(rate=self.lambda_value, rng=self._rng)
     81 if k > 0:

File ~/miniconda3/lib/python3.9/site-packages/river/metrics/base.py:337, in MeanMetric.update(self, y_true, y_pred, sample_weight)
    336 def update(self, y_true, y_pred, sample_weight=1.0):
--> 337     self._mean.update(x=self._eval(y_true, y_pred), w=sample_weight)
    338     return self

File ~/miniconda3/lib/python3.9/site-packages/river/metrics/cross_entropy.py:54, in CrossEntropy._eval(self, y_true, y_pred)
     51 def _eval(self, y_true, y_pred):
     52     total = 0
---> 54     for label, proba in y_pred.items():
     55         if y_true == label:
     56             total += math.log(utils.math.clamp(x=proba, minimum=1e-15, maximum=1 - 1e-15))

AttributeError: 'NoneType' object has no attribute 'items'

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
# Please do your best to provide a Minimal, Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example

import river
from river import forest, metrics
model = forest.ARFClassifier(metric=metrics.CrossEntropy())
model.learn_one({"x": 1}, True)

model = forest.ARFClassifier()
model.learn_one({"x": 1}, True)
```

**Comment by MaxHalford** [comment]
Thanks for pointing this out! It was an easy fix.
