### ISSUE TITLE
iter_arff issue

### ISSUE THREAD

**Issue by Elanktar** [online-ml/river#1287]
Hi there,

I am currently facing an issue for the use of this dataset and others using the same format :
[Scene.zip](https://github.com/online-ml/river/files/12094977/Scene.zip)

It seems that the read function is not able to understand this file and that we only can use one target.
I also noticed that the arffread function used from scipy is deprecated.

I'm currently using python 3.11 and river 0.18.0
I would really appreciate your help!

**Comment by MaxHalford** [comment]
Hey there. Indeed, we need to improve `iter_arff` to support multi-target cases. No problem, I can do that.

However, are you sure your dataset is valid? When I run `arff.loadarff('Scene.arff')` I get a `{ 3 1 value not in ('0', '1')` exception. You have define 6 targets, but I don't really understand what the leading part of each row represents. For instance, what is `5 1,6`?

**Comment by Elanktar** [comment]
That would be great! 

Yes the dataset is valid. We used this format for a while. With it, we only represent the key features/labels for each example, getting rid of all null values for example.

Each example is divided into a series of tuples, which contain the index of a feature/label and its value. Depending on the number, and location of the labels, the indices vary. In the case of Scene, where there are 6 labels, the indices 0-5 indicate the labels, and everything after is a feature. So an index of 6 represents the X1 feature of the example. This means that you can easily cut the examples into features and labels without having to reference the names of the targets, and only the number of labels and their location in the data.

We also noticed that the current scipy.io.arff.loadarff method cannot read files with sparse data. It's also a problem.

**Comment by MaxHalford** [comment]
> Each example is divided into a series of tuples, which contain the index of a feature/label and its value.

That's clear to me. And this follows the standard ARFF format, correct? It's just scipy that can't handle sparse ARFF datasets?

> In the case of Scene, where there are 6 labels, the indices 0-5 indicate the labels

Ok so once again what does `5 1,6` mean? What would be the target values? I understand the feature format, but not the labels.

**Comment by Elanktar** [comment]
> That's clear to me. And this follows the standard ARFF format, correct? It's just scipy that can't handle sparse ARFF datasets? 

Exactly, according to the documentation of loadarff (as we can’t find the one for arff_read which is older), it can’t handle sparse versions of ARFF files. 

> Ok so once again what does 5 1,6 mean? What would be the target values? I understand the feature format, but not the labels. 

In the case of Scene, “5 1” would indicate that the 6th Label is equal to 1, the comma is the entry separator, and the following 6 should be the index of the next entry, the first Feature, and should be followed by the value associated with it. 
For example, a correct version could be “5 1, 6 0.699889”, possibly followed by even more entries to complete the example.

**Comment by MaxHalford** [comment]
So what about the other labels? They're 0? If so, I don't see any cases of more than one label being equal to 1. If that's true, isn't this a multi-classification problem?

**Comment by killianLM** [comment]
There are actually a few examples with multiple labels in Scene. For example line 313 (one of the first examples) of the file we sent has labels 0 and 5 as both true.

**Comment by MaxHalford** [comment]
Hey @Elanktar @killianLM, I've merged #1288. I added your example as a doctest, and it seems to work fine. Let me know if something doesn't work as you expect it to.
