### ISSUE TITLE
Regression error when predict_one

### ISSUE THREAD

**Issue by raul-parada** [online-ml/river#1292]
I'm using Colab 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] using the latest version of River installed by pip

I have this code:

from river import neighbors

model = neighbors.KNNRegressor()

```
X= dat[0:(i*num)]
y=[]
for i in range(0, len(X)):
  geoh = geohash.encode(latitude=dat['latitude(m)'][i], longitude=dat['longitude(m)'][i], precision=24)
  y.append(geoh)
model = model.learn_one(X, y)
X1=dat[num:num+1]
model.predict_one(X1)
```

However, I get this error:
`ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
`
type(X1) --> pandas.core.frame.DataFrame

I don't know why it says Series when is a DataFrame.

Do you know how to solve this? If you require more information, let me know. Thanks

**Comment by smastelini** [comment]
You ended up using nested dicts. 

The solution is convert each row to a dict.

**Comment by MaxHalford** [comment]
X.to_dict(orient=records) should give you the right conversion

**Comment by raul-parada** [comment]
@MaxHalford, I've used in `X.to_dict(orient='records')` in both training data X and test data X1 and in this last I get this error `AttributeError: 'list' object has no attribute 'keys'`. The line is model.predict_one(X1) and X1 has the content `[{'latitude(m)': 41.390912746795, 'longitude(m)': 2.160932968687648}]` type list. Previously, I've also tried X1.to_dict()

**Comment by smastelini** [comment]
@raul-parada, you should try something like:

```py

X = dat[0:(i*num)].to_dict(orient='records' )
for i in range(0, len(X)):
  geoh = geohash.encode(latitude=dat['latitude(m)'][i], longitude=dat['longitude(m)'][i], precision=24)
  model = model.learn_one(X[i], geoh)

X1 = dat[num:num+1].to_dict()
model.predict_one(X1)
```

**Comment by raul-parada** [comment]
I've used this:

```
import geohash
from river import neighbors

model = neighbors.KNNRegressor()
num=10
i=1
X = dat[0:(i*num)].to_dict(orient='records')
for j in range(0, len(X)):
  geoh = geohash.encode(latitude=dat['latitude(m)'].values[j], longitude=dat['longitude(m)'].values[j], precision=24)
  model = model.learn_one(X[j], geoh)

X1 = dat[num:num+1].to_dict()
model.predict_one(X1)
```
Still got this error: `TypeError: unsupported operand type(s) for -: 'dict' and 'float'` this is the content: 
```
{'latitude(m)': {7756818: 41.390912746795},
 'longitude(m)': {7756818: 2.160932968687648}}
```
. It is dict type, however, different from X ```
[{'latitude(m)': 41.39084623800272, 'longitude(m)': 2.160805281576777},
 {'latitude(m)': 41.390851486976665, 'longitude(m)': 2.1608111896735127},
 {'latitude(m)': 41.39086003129282, 'longitude(m)': 2.1608208069171},
 {'latitude(m)': 41.39087467807671, 'longitude(m)': 2.1608372929357924},
 {'latitude(m)': 41.3908917193554, 'longitude(m)': 2.160856474144813},
 {'latitude(m)': 41.39089960435842, 'longitude(m)': 2.160865349298634},
 {'latitude(m)': 41.390894486198434, 'longitude(m)': 2.1608763129349247},
 {'latitude(m)': 41.390888424091, 'longitude(m)': 2.1608861783642985},
 {'latitude(m)': 41.39088797704704, 'longitude(m)': 2.1609023978100472},
 {'latitude(m)': 41.39089878662674, 'longitude(m)': 2.160914971413666}]
```
It's weird how X and X1 are different

**Comment by smastelini** [comment]
The format in `X` seems correct. You are not supposed to use nested dictionaries as inputs.

It is safe to assume that using `model.predict_one({'latitude(m)': 41.390912746795, 'longitude(m)': 2.160932968687648})` will work as expected.

Note that this is not a River-related problem but a data-handling issue. 

I suggest you investigate how to make X1 have the same format as X. Without your data, the best I can do is guesswork.

The `7756818` seems to be the index value.  Maybe using `X1 = dat[num:num+1].flatten().to_dict()` can help. But again, this is not a River-related issue.
