### ISSUE TITLE
TypeError when using Gaussian Scorer in Pipeline

### ISSUE THREAD

**Issue by MarekWadinger** [online-ml/river#1296]
## Versions

**river version**: 0.18.0
**Python version**: 3.10.1
**Operating system**: macOS Sonoma 14.0 Beta

## Describe the bug

[anomaly.GaussianScorer](https://github.com/online-ml/river/blob/main/river/anomaly/gaussian.py) cannot be used as last_step in [compose.Pipeline](https://riverml.xyz/0.18.0/api/compose/Pipeline). Learning on new samples raises a TypeError.
I

## Possible Solutions
1. Edit ["anomaly/gaussian.py" line 60](https://github.com/online-ml/river/blob/1497f147c95b43e863bd8714c629693f5432fb4c/river/anomaly/gaussian.py#L60), in learn_one: def learn_one(self, _, y): → def learn_one(self, x, y):
2. Edit ["compose/pipeline.py", line 474](https://github.com/online-ml/river/blob/1497f147c95b43e863bd8714c629693f5432fb4c/river/compose/pipeline.py#L474), in learn_one: step.learn_one(x=x, y=y) → learn_one(x, y=y)

## Steps/code to reproduce

```python
from river import anomaly
from river import preprocessing

model = preprocessing.StandardScaler() 
model |= anomaly.GaussianScorer()

from river import datasets

dataset = datasets.CreditCard()
x, y = next(iter(dataset))

print(model.score_one(x, y=y))

model.learn_one(x, y=y)
```

## Full Backtrace of Exception
<details>
<summary><code>TypeError: GaussianScorer.learn_one() got an unexpected keyword argument 'x'</code></summary> 
<code>Traceback (most recent call last):
  File "./pipeline_gaussian.py", line 14, in <module>
    model.learn_one(x, y=y)
  File "./.env/lib/python3.10/site-packages/river/compose/pipeline.py", line 551, in learn_one
    last_step.learn_one(x=x, y=y, **params)
</code>
</details>

**Comment by MaxHalford** [comment]
Good catch, just fixed it in https://github.com/online-ml/river/commit/3525891fed76791bd63593174407c016b8f54148
