### ISSUE TITLE
Progressive Val Score on iter_pandas

### ISSUE THREAD

**Issue by ericleonardo** [online-ml/river#1299]
Please, how to make Progressive Val Score run on iter_pandas?
Also, how to convert CSV or pandas Dataframe (feature1, feature2, feature3, target) to Dict?
Most examples on River docs use native dataset, but most people will import their own from CSV or pandas.
It would be useful to include in Docs how to convert CSV/Dataframe do same format as the native dataset to follow examples with my own data easily. **Thank you!**

Erro when trying to use Progressive Val Score on iter_pandas:

```
X = pd.read_csv('My_data.csv', usecols=['Feat1','Feat2','Feat3'])
y = pd.read_csv('My_data.csv', usecols=['Target'])
```

```
model = forest.ARFClassifier(split_criterion='info_gain', max_depth=5)
metric = metrics.Accuracy()
```

```
dataset_stream = stream.iter_pandas(X,y)
steps = evaluate.iter_progressive_val_score(
    model=model,
    dataset=next(dataset_stream),
    metric=metric,
    step=50
)
```

```
for step in steps:
    print(step)
```

Error:
     66         # Case 1: no ground truth, just make a prediction
     67         if y is None:
---> 68             y_pred = pred_func(x, **kwargs)
     69             y_pred, ask_for_label = y_pred if active_learning else (y_pred, True)
     70             if utils.inspect.isanomalyfilter(model):

`TypeError: river.base.classifier.Classifier.predict_one() argument after ** must be a mapping, not str`

**Comment by MaxHalford** [comment]
Hey there. I think you're a bit confused. progressive_val_score expects a generator as a dataset. But you're calling `next`, which is wrong. This should work:

```py
dataset_stream = stream.iter_pandas(X,y)
steps = evaluate.iter_progressive_val_score(
    model=model,
    dataset=dataset_stream,
    metric=metric,
    step=50
)
```

>  Most examples on River docs use native dataset, but most people will import their own from CSV or pandas.

Actually, I hope most people run their models on infinite data streams, such as a database query or a Kafka message broker :)

**Comment by ericleonardo** [comment]
Thank you, Max! But it still not working:

```
[/usr/local/lib/python3.10/dist-packages/river/metrics/confusion.py](https://localhost:8080/#) in _update(self, y_true, y_pred, sample_weight)
     75 
     76     def _update(self, y_true, y_pred, sample_weight):
---> 77         self.data[y_true][y_pred] += sample_weight
     78         self.total_weight += sample_weight
     79         self.sum_row[y_true] += sample_weight

TypeError: unhashable type: 'dict'
```

As the error seems to originate when metrics is called, I tried using `metrics.ROCAUC()` or `metrics.Accuracy()` but none worked. Maybe it is not related to metrics. Please, what you think may be the cause?

**Comment by MaxHalford** [comment]
I think the issue is that y is a dataframe and not a series. Indeed, the target should be univariate. See what I mean?

**Comment by ericleonardo** [comment]
Yes.. Now it works!

```
X = pd.read_csv('My_data.csv', usecols=['Feat1','Feat2','Feat3'])
y = pd.read_csv('My_data.csv', usecols=['Target'])
y = y.squeeze()
```

Really converting the dataframe `y` to series `.squeeze()` was necessary.

Thank you so much!
