### ISSUE TITLE
Serializing and saving River models with MLFlow and BentoML

### ISSUE THREAD

**Issue by sebasmos** [online-ml/river#1316]
I am running River and need to save the model using MLFlow, however this flavour is not implemented yet. MLFlow suggests a customize option defined [here](https://mlflow.org/docs/2.3.2/models.html#example-creating-a-custom-add-n-model) but not very friendly with River implementation. Is there any solution for this issue? 

## Versions

numpy>=1.15.0,<1.24.3
notebook==6.5.4
seaborn>=0.11.2,<=0.12.2
pandas>=1.4.3
matplotlib==3.7.1
scikit-learn==1.2.2
xgboost==1.7.6
tqdm==4.65.0
mlflow==2.3.2
bentoml==1.0.20

**Comment by MaxHalford** [comment]
Hey there. You can pickle/unpickle any River model, as shown [here](https://riverml.xyz/0.18.0/faq/#how-do-i-save-and-load-models). Is this sufficient?

**Comment by sebasmos** [comment]
Yes thanks you Max I am currently doing this as a backup solution. However the goal was to integrate it with MLFlow, but probably this should be an issue in MLFlow flavours at a later stage

**Comment by MaxHalford** [comment]
Yep sorry I don't know enough about MLFlow to give you a proper answer. As you say, I'm guessing the solution will come from MLFlow's side.
