### ISSUE TITLE
Unique index of a leaf node in Decision Trees

### ISSUE THREAD

**Issue by danielnowakassis** [online-ml/river#1320]
Hi!

I wish to get an index of a leaf node in a decision tree, such that this index is unique to the leaf node and was not an index of other leaf node previously in the stream.

I want to traverse the tree with an instance sample and get the index of the leaf node. 

Does someone know how to do that?

Thanks in advance!

**Comment by smastelini** [comment]
Hi @danielnowakassis. The way the trees are implemented does not allow for such analysis at the moment. Each branch has a list of leaf nodes, so there are no explicit ids unless you access the actual object id. However, I am not sure how reliable this approach would be for your objectives.
