### ISSUE TITLE
DBSTREAM: multiple issues

### ISSUE THREAD

**Issue by donny741** [online-ml/river#1324]
Hi, I'm new to Python and data science, and I'm currently exploring the clustering algorithms. When comparing the DBSTREAM algorithm implementation with the original paper I noticed some inconsistencies:
- It seems the `-` signs before the `fading_factor` are missing [here](https://github.com/online-ml/river/blob/main/river/cluster/dbstream.py#L256) and [here](https://github.com/online-ml/river/blob/main/river/cluster/dbstream.py#L269) what prevents the clusters with low weight from being removed
- Length of the `micro_clusters` list is used as an index key when creating the new cluster ([here](https://github.com/online-ml/river/blob/main/river/cluster/dbstream.py#L185)) what can override the existing clusters because the length is decremented when clusters are removed from the list ([here](https://github.com/online-ml/river/blob/main/river/cluster/dbstream.py#L261))
- `clustering_is_up_to_date` variable introduced with [this PR](https://github.com/online-ml/river/pull/1213) is never being set to `True`

**Comment by MaxHalford** [comment]
Hey @hoanganhngo610, do you have time to take a look at this issue? :)

**Comment by hoanganhngo610** [comment]
@MaxHalford I will have a look at the issues by the end of this week. Also, thank you @donny741 for raising the issues!

**Comment by hoanganhngo610** [comment]
@donny741 @MaxHalford I have just made a PR to fix the points that @donny741 proposed within this issue. Hope that the changes are satisfactory.

If you have some time, please do not hesitate to have a look through the PR and leave comments wherever necessary!

**Comment by MaxHalford** [comment]
Good job! Just merged the PR.

@donny741 I'll let you close the PR if you're satisfied

**Comment by donny741** [comment]
Looks good! Thank you!
