### ISSUE TITLE
TextClust: How to pass time variable to learn_one

### ISSUE THREAD

**Issue by kchoe0401** [online-ml/river#1325]
Greetings,

I am relatevly new to text clustering algorithms, but I am trying to implement TextClust. It works fine with ```real_time_fading = False```, but I am trying to do it with that option. 
Now I assumed that I could just pass a timestamp or datetime for the parameter ```t```in learn_one like this example

```prediction = model.learn_one(x['tweet'], t=x['timestamp'])```

However, ```t```stays ```None``` no matter the input. What is the reason for that?

**Comment by MaxHalford** [comment]
Hey @Dennis1989, can you take a look? :)

**Comment by Dennis1989** [comment]
Yep Max. I will have a look at this later this week.

**Comment by Dennis1989** [comment]
Sorry for my late reply. It's been some time but I think you need to set `self.real_time_fading` during the initialization of the cluster model.  Also, you need to do some preprocessing of the timestamp (transform it to an integer) before passing it to `model.learn_one`. For example:

```
now = datetime.datetime.now()
int(now.timestamp())
```

Does this help and work?
