### ISSUE TITLE
LocalOutlierFactor raises ZeroDivisionError on identical initial samples

### ISSUE THREAD

**Issue by MarekWadinger** [online-ml/river#1328]
## Versions

**river version**: latest
**Python version**: Python 3.10.1
**Operating system**: macOS Sonoma 14.0 (23A344)

## Describe the bug

If two identical samples arrive at the beginning of the stream, the ZeroDivisionError is raised. Making some attempts to track down the issue and propose solutions (without success so far).

## Steps/code to reproduce

```python
from river import anomaly

lof = anomaly.LocalOutlierFactor()

X = [{"a": 1, "b": 1}, {"a": 1, "b": 1}]
for x in X:
    lof.learn_one(x)
```

## Full Backtrace of Exception
<details>
<summary><code>ZeroDivisionError: float division by zero</code></summary> 
<code>
ZeroDivisionError                         Traceback (most recent call last)
/river/test_lof.ipynb Cell 3 line 7
      <a href='vscode-notebook-cell:/river/test_lof.ipynb#W0sZmlsZQ%3D%3D?line=4'>5</a> X = [{\"a\": 1, \"b\": 1}, {\"a\": 1, \"b\": 1}]
      <a href='vscode-notebook-cell:/river/test_lof.ipynb#W0sZmlsZQ%3D%3D?line=5'>6</a> for x in X:
----> <a href='vscode-notebook-cell:/river/test_lof.ipynb#W0sZmlsZQ%3D%3D?line=6'>7</a>     lof.learn_one(x)

File ~/river/anomaly/lof.py:265, in LocalOutlierFactor.learn_one(self, x)
    263 self.x_batch.append(x)
    264 if len(self.x_list) or len(self.x_batch) > 1:
--> 265     self.learn(self.x_batch)
    266     self.x_batch = []

File ~/river/anomaly/lof.py:336, in LocalOutlierFactor.learn(self, x_batch)
    327 self.reach_dist = calc_reach_dist_other_points(
    328     set_rev_neighbors,
    329     self.rev_neighborhoods,
   ()
    332     self.k_dist,
    333 )
    335 # Calculate new local reachability distance of all affected points
--> 336 self.local_reach = calc_local_reach_dist(
    337     set_upd_lrd, self.neighborhoods, self.reach_dist, self.local_reach
    338 )
    340 # Calculate new Local Outlier Factor of all affected points
    341 self.lof = calc_lof(set_upd_lof, self.neighborhoods, self.local_reach, self.lof)

File ~/river/anomaly/lof.py:128, in calc_local_reach_dist(set_index, neighborhoods, reach_dist, local_reach_dist)
    124 \"\"\"
    125 Calculate local reachability distance of affected points.
    126 \"\"\"
    127 for i in set_index:
--> 128     local_reach_dist[i] = len(neighborhoods[i]) / sum(
    129         [reach_dist[i][j] for j in neighborhoods[i]]
    130     )
    131 return local_reach_dist

</code>
</details>

**Comment by smastelini** [comment]
Hi @MarekWadinger, good catch! I am not very knowledgeable about iLOF but it seems the issue comes from the division at line 128. Maybe we could create an auxiliary variable holding the sum of the reachability distances and skip the update when such a sum is zero. Either that or using a try/except block to skip the update. Does that sound reasonable?

**Comment by MaxHalford** [comment]
I just fixed the issue in https://github.com/online-ml/river/commit/4b949c6ad11cc088ddb42bf319b4c94f42fe4a67 :)
