### ISSUE TITLE
Inconsistency in ARFClassifier's `drift_detector` and `warning_detector` Attributes When Saving and Loading

### ISSUE THREAD

**Issue by kdMoura** [online-ml/river#1332]
## Versions

**river version**: 0.19.0
**Python version**: 3.9.18
**Operating system**: Ubuntu 18.04.6 LTS, Ubuntu 22.04.2 LTS

## Describe the bug

I have noticed an inconsistency when using the `ARFClassifier` from the `river` library in Python. When I create an `ARFClassifier` object and set its `drift_detector` and `warning_detector` attributes to `None`, I expect them to be `None` when I load the object from a saved file using `pickle`. However, `loaded_model.drift_detector` and `loaded_model.warning_detector` are not `None` as I expected. Is there something I'm missing, or is this an issue?

## Steps/code to reproduce

```python
from river import forest
import pickle

model = forest.ARFClassifier(n_models=15, seed=33, leaf_prediction="mc", drift_detector=None, warning_detector=None)
# Save the model
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

# Load the model
with open('model.pkl', 'rb') as model_file:
    loaded_model = pickle.load(model_file)

# I expect loaded_model.drift_detector and loaded_model.warning_detector to be None, but they're not.
print(loaded_model.drift_detector)
#ADWIN
print(loaded_model.warning_detector)
#ADWIN
```

**Comment by smastelini** [comment]
Hi @kdMoura, thanks for reporting that. 

Does the problem also happen in the development version of River? He recently made some changes in ARF.

**Comment by MaxHalford** [comment]
I don't think this has anything to do with pickle. The attributes are populated when the class is instantiated:

```py
from river import forest

model = forest.ARFClassifier(drift_detector=None, warning_detector=None)
model.drift_detector
```

```py
ADWIN (
  delta=0.001
  clock=32
  max_buckets=5
  min_window_length=5
  grace_period=10
)
```

However, isn't this expected behavior? Using `None` means that default values are used. See the docs:

<img width="651" alt="Screenshot 2023-10-03 at 23 58 12" src="https://github.com/online-ml/river/assets/8095957/7307df8a-d439-40e2-86af-16e12439097f">

**Comment by smastelini** [comment]
Actually, this led me to think. We need to revisit the way we set the detector to ensure users can switch off the drift detection part. 

I can take care of this.

**Comment by smastelini** [comment]
Hey @kdMoura, please check out #1350 :)
