### ISSUE TITLE
Cython.Compiler.Errors.CompileError: venv\Lib\site-packages\Cython\Utility\CConvert.pyx

### ISSUE THREAD

**Issue by Livisc** [online-ml/river#1348]
```
[ 1/15] Cythonizing river\drift\adwin_c.pyx
[ 2/15] Cythonizing river\metrics\efficient_rollingrocauc\efficient_rollingrocauc.pyx
[ 3/15] Cythonizing river\metrics\expected_mutual_info.pyx
[ 4/15] Cythonizing river\utils\vectordict.pyx
[ 5/15] Cythonizing venv\Lib\site-packages\Cython\Runtime\refnanny.pyx
[ 6/15] Cythonizing venv\Lib\site-packages\Cython\Utility\CConvert.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    bint PyMapping_Check(obj)
    object PyErr_Format(exc, const char *format, ...)
    int __Pyx_RaiseUnexpectedTypeError(const char *expected, object obj) except 0

@cname("{{funcname}}")
cdef {{struct_type}} {{funcname}}(obj) except *:
     ^
------------------------------------------------------------

venv\Lib\site-packages\Cython\Utility\CConvert.pyx:12:5: Expected an identifier, found '{'

Error compiling Cython file:
------------------------------------------------------------
...
    bint PyMapping_Check(obj)
    object PyErr_Format(exc, const char *format, ...)
    int __Pyx_RaiseUnexpectedTypeError(const char *expected, object obj) except 0

@cname("{{funcname}}")
cdef {{struct_type}} {{funcname}}(obj) except *:
      ^
------------------------------------------------------------

venv\Lib\site-packages\Cython\Utility\CConvert.pyx:12:6: Syntax error in C variable declaration
Traceback (most recent call last):
  File "D:\daikin\code\river-main\river-main\setup.py", line 121, in <module>
    ext_modules=cythonize(
  File "D:\daikin\code\river-main\river-main\venv\lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "D:\daikin\code\river-main\river-main\venv\lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: venv\Lib\site-packages\Cython\Utility\CConvert.pyx
```

How can i solve this problem？

**Comment by MaxHalford** [comment]
Hey there. You will have to provide more context. What OS are you using? What installation command did you use? What version of Python are you using?

We are not wizards who have access to your computer, so a traceback by itself is not enough :)

**Comment by Livisc** [comment]
> Hey there. You will have to provide more context. What OS are you using? What installation command did you use? What version of Python are you using?
> 
> We are not wizards who have access to your computer, so a traceback by itself is not enough :)
Thank you for your reply. I am using Windows 10 Professional and Python version 3.10.10. I am running
I am running setup.py in a virtual environment using Python 3.10.10. Encountered this problem. I tried updating Cython, but it didn't work.

**Comment by Livisc** [comment]
Current Python 3.0.4

**Comment by AdilZouitine** [comment]
There It seems that there may be a breaking change due to the `Cython 3.0` upgrade, which could be the root cause of your issue. I suggest that you try running the command `pip install 'Cython < 3'` to see if it resolves the problem.

**Comment by MaxHalford** [comment]
We only support Python 3.8 and onwards. 3.0 is very old!

**Comment by Livisc** [comment]
> We only support Python 3.8 and onwards. 3.0.4 is very old!

yep，This is my mistake.my Python is 3.10.10,   and my Cython is 3.0.4.

**Comment by Livisc** [comment]
> There may be a breaking change due to the `Cython 3.0` upgrade, which could be the root cause of your issue. I suggest you try running the command `pip install 'Cython < 3'` to see if it resolves the problem.

Thank you for your reply. I have tried lowering the version of Python. This did not work and the error still appears. I feel that this may be the focus of the problem。【@cname("{{funcname}}")
cdef {{struct_type}} {{funcname}}(obj) except *:
    ^
------------------------------------------------------------

venv\Lib\site-packages\Cython\Utility\CConvert.pyx:11:5: Expected an identifier, found '{'】

**Comment by MaxHalford** [comment]
And what OS are you using? Windows? It's weird that the wheel is being built, as we normally support most distributions.

PS: can you please put some effort into formatting your messages? They're not pleasant on the eyes.

**Comment by Livisc** [comment]
@MaxHalford  you for your patience. I am using Windows 10, and I have tried to change my Python version to 3.8.7. However, I still encountered the same error. Every time I go to the CConvert.pyx file in Python, there is an error. I am a fresh man, Thank for taking care of me.

**Comment by MaxHalford** [comment]
@Livisc I think the issue could be that Cython is trying to compile stuff in the `venv` directory. I don't know what this is. But basically I don't think the issue is coming from River. I think your Python setup is messed up.

**Comment by MaxHalford** [comment]
I take it you solved the problem :)
