### ISSUE TITLE
Building in Prediction History

### ISSUE THREAD

**Issue by robme-l** [online-ml/river#1351]
This is not so much an issue as it is a feature discussion. I have noticed in my modeling I have a need to issue a prediction after learning. As such when I set up training/eval loops for comparing different models, I often have to hand write these loops over again since the built-in `progressive_val_score` only yields the metric. I was wondering whether there is a feature to store predictions optionally up to say a certain window size? Or have `iter_progressive_val_score` yield the predicted value as well as the metric.

**Comment by MaxHalford** [comment]
Done! Just added a `yield_predictions` parameter to `evaluate.iter_progressive_val_score`, which allows including predictions in the output. I think that's the right way to go. See https://github.com/online-ml/river/blob/main/river/evaluate/progressive_validation.py#L191-L207 for an example.

Thanks a lot for suggesting this!

**Comment by robme-l** [comment]
@MaxHalford you are so helpful I hate you xD I'm going to have to refactor my pipelines now but this is great! Thank you!
