### ISSUE TITLE
TimeRollingQuantile

### ISSUE THREAD

**Issue by jakubxy08** [online-ml/river#1353]
## Describe your task
We have implemented TimeRolling class that supports time indexed computation of Sum, Mean, Variance. Is it possible to add implementation also for RollingQuantile? Probaly should implement this in watermill.rs in Rust.

## What kind of performance are you expecting?
Pandas and polars performance is not that good and also require time for conversion datatypes.

## Steps/code to reproduce
Implementation in rust and wrapper in python in river.
https://github.com/online-ml/river/blob/main/river/stats/quantile.py#L136

# Sample code to reproduce the performance issue

## Necessary data
Pure python implementation is not fast enough. It will be very helpful feature.

**Comment by MaxHalford** [comment]
> Is it possible to add implementation also for RollingQuantile? Probaly should implement this in watermill.rs in Rust.

Indeed, this would have to be implemented in Rust. I don't think @AdilZouitine has time to do that right now (he wrote the original Rust code). 

I've added a note [here](https://github.com/orgs/online-ml/projects/3?query=is%3Aopen+sort%3Aupdated-desc&pane=issue&itemId=43060455) so we keep track of this task. I'll close the issue in the meantime.
