### ISSUE TITLE
ConfusionMatrix metric does not working with iter_progressive_val_score

### ISSUE THREAD

**Issue by icaroperetti** [online-ml/river#1443]
## Versions
**0.19.0**:
**Python 3.8**:
**Windows**:

## Describe the bug
When I try to use the metric ConfusionMatrix  with iter_progressive_val_score I'm getting the following error: 'ConfusionMatrix' object has no attribute 'works_with'.
Using Accuracy,F1, ROCAUC works fine

## Steps/code to reproduce

Part of my code is here: https://gist.github.com/icaroperetti/942f2980a1d86e71c9ef1fdbe6f82573

Is there any workaround to calculate de confusion matrix anyways?

**Comment by MaxHalford** [comment]
Thanks for filing an issue!
