### ISSUE TITLE
Discrepancy in Evaluation Metrics for Online Logistic Regression Model

### ISSUE THREAD

**Issue by RafiullahOmar** [online-ml/river#1446]
**Description:**
I have encountered a discrepancy in the evaluation metrics when evaluating an online logistic regression model using two different methods. The code below demonstrates the issue:

**The output is:
Metric 1 ROCAUC: 89.36%
Metric 2 ROCAUC: 94.20%**

```python
from river import datasets
from river import linear_model
from river import metrics, evaluate

# Load the Phishing dataset
dataset = datasets.Phishing()

# Initialize the online logistic regression model
model = linear_model.LogisticRegression()

# Initialize two ROCAUC metrics for evaluation
metric1 = metrics.ROCAUC()
metric2 = metrics.ROCAUC()

# Train the model and update metrics
for x, y in dataset:
    y_pred = model.predict_proba_one(x)
    model.learn_one(x, y)
    metric1.update(y, y_pred)

# Evaluate the model using another method
evaluate.progressive_val_score(dataset, model, metric2)

# Print the results
print("Metric 1 ROCAUC:", metric1.get())
print("Metric 2 ROCAUC:", metric2.get())

**Comment by smastelini** [comment]
@RafiullahOmar , what happens if you try?

```py
evaluate.progressive_val_score(dataset, model.clone(), metric2)
```

**Comment by RafiullahOmar** [comment]
Thanks @smastelini then I get the same result for both.

**Comment by smastelini** [comment]
I executed the above script and got `Metric 1 ROCAUC: 0.5002776057800238`. 🤔

**Comment by RafiullahOmar** [comment]
@smastelini  Did you executed the same script?

**Comment by smastelini** [comment]
Yes! I copied both cells and ran them

**Comment by RafiullahOmar** [comment]
@smastelini  Can you please change the number of instances and then the dataset to 'dataset = datasets.Phishing()'

**Comment by smastelini** [comment]
Hey @RafiullahOmar, when you clone a model you are creating a new copy of it. That why the for becomes irrelevant if you are only looking at the results of `progressive_val_score`.
