### ISSUE TITLE
0.20.1 release is missing artifacts for MacOS ARM64

### ISSUE THREAD

**Issue by cch0** [online-ml/river#1449]
## Versions

**river version**: 0.20.1
**Python version**: 
**Operating system**: MacOS 

## Describe the bug

`0.20.1` installation failed on Mac M1.

After comparing the package on pypi between [0.19.0](https://pypi.org/project/river/0.19.0/#files) and [0.20.1](https://pypi.org/project/river/0.20.1/#files), built for MacOS arm64 are missing from `0.20.1` release. There are probably others built missing as well.

I also downloaded the Github action build artifact for [0.19.0](https://github.com/online-ml/river/actions/runs/6065170604) and [0.20.1](https://github.com/online-ml/river/actions/runs/6812525928), macos whl files are also not present in `0.20.1` build artifact.

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
# Please do your best to provide a Minimal, Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example

pip install river==0.20.1

```

**Comment by MaxHalford** [comment]
Hey there, thanks for opening the issue. I am aware of the issue, and will take a look very soon.

**Comment by chrisgoddard** [comment]
Hi there! Any update on this?

**Comment by MaxHalford** [comment]
Not yet.

**Comment by MaxHalford** [comment]
River 0.21 is now out, which should fix the installation issues you have encountered. Thanks for your patience. Feel welcome to reopen this issue if the problem persists though.
