### ISSUE TITLE
'river.ensemble' has no attribute 'AdaptiveRandomForestClassifier'

### ISSUE THREAD

**Issue by RafiullahOmar** [online-ml/river#1452]
I am using the AdaptiveRandomForestClassifier as below:
`from river import ensemble
name1 = "ARF-ADWIN model"
model1 = ensemble.AdaptiveRandomForestClassifier(n_models = 3, drift_detector = ADWIN()) # Define the model`

but get this error, I have installed the river.
`AttributeError: module 'river.ensemble' has no attribute 'AdaptiveRandomForestClassifier'`

**Comment by MaxHalford** [comment]
Hey there. Two questions: what version of River are you using? And where did you get this piece of code from? That model is called ARFClassifier now

**Comment by RafiullahOmar** [comment]
version is 0.20.1 and got the code from github the link is: 
https://github.com/Western-OC2-Lab/PWPAE-Concept-Drift-Detection-and-Adaptation/blob/main/globecom2021_PWPAE_CICIDS2017.ipynb

**Comment by MaxHalford** [comment]
Please see https://riverml.xyz/latest/api/forest/ARFClassifier/
