### ISSUE TITLE
DBSTREAM: update shared density

### ISSUE THREAD

**Issue by ShkarupaDC** [online-ml/river#1468]
## Description

Hi! I have a question about the DBSTREAM implementation. The DBSTREAM updates shared densities by multiplying the current weight by the fading factor (2^(-lambda * (t_current - t_last)) and adding 1. Thus, if 2 micro-clusters (MC) have not shared data samples before but receive a data sample that falls into assignment areas of both ones now, their shared density should be 1. However, in the code (snippet that supports my statement is presented below), we have 0. Am I right, and we should fix this bug, or did I miss something? @hoanganhngo610, could you take a look?

## Code

```python
# river/cluster/dbstream.py, 228 - 234
except KeyError:
    try:
        self.s[i][j] = 0
        self.s_t[i][j] = self._time_stamp
    except KeyError:
        self.s[i] = {j: 0}
        self.s_t[i] = {j: self._time_stamp}
```

## Pseudo code

The update rule is described on line 11.
<img width="400" alt="Screenshot 2023-12-05 at 15 57 05" src="https://github.com/online-ml/river/assets/54143556/0f6ed6bc-0b9b-42e9-9801-19633312d278">

**Comment by ShkarupaDC** [comment]
The second question arose when I created this issue(

Could you explain why we take the square root of Minkowski distance as we already accounted for that in the metric implementation?

```python
# river/cluster/dbstream.py, 162 - 164
@staticmethod
    def _distance(point_a, point_b):
        return math.sqrt(utils.math.minkowski_distance(point_a, point_b, 2))
```

**Comment by hoanganhngo610** [comment]
Thank you so much @ShkarupaDC for raising the issue. I will have a look at this issue shortly.

**Comment by hoanganhngo610** [comment]
@ShkarupaDC For the second question, it's true that the `math.sqrt` is redundant. In fact, this is due to the fact that at the time this algorithm is implemented, the `minkowski_distance` function does not have `**(1/p)**`, hence the existence of the square root. I will modify this in the next commit.

**Comment by ShkarupaDC** [comment]
@hoanganhngo610, thank you for your answer! Could you also help me understand the reason for catching the OverflowError? The expression 
```python
# river/cluster/dbstream.py, 261 - 263
value = 2 ** (
    -self.fading_factor * (self._time_stamp - micro_cluster_i.last_update)
)
```
may result in a large number that causes an OverflowError only in the case we use a negative fading_factor. Such behavior is not expected, so it may be a good idea to add parameter validation as a protection mechanism.  When using positive fading_factor the value can be only too small. However, Python just returns 0 in this case.

**Comment by ShkarupaDC** [comment]
From the [official C++/R implementation](https://github.com/mhahsler/stream/blob/master/src/DBSTREAM.cpp#L244), I also found that entries in shared density dict should be removed for weak clusters that are removed. That looks pretty obvious, so it will be great if you implement that.

P.S. I could create a PR instead but maybe on Saturday or Sunday. What is better for you?

**Comment by ShkarupaDC** [comment]
@hoanganhngo610, I asked you because I did not get the reason from the mentioned discussion. If an overflow occurs here
```python
self._time_stamp - micro_cluster_i.last_update
# or here
self._time_stamp - self.s_t[i][j] 
```
then **value** should be close to 0 and less than weak density (or weak density multiplied by **intersection_factor**). Therefore, we should not continue, but remove the micro-cluster (or set the shared density to 0).

I am telling you about these 2 cases:
```python
# river/cluster/dbstream.py, 260 - 265
try:
    value = 2 ** (
        -self.fading_factor * (self._time_stamp - micro_cluster_i.last_update)
    )
except OverflowError:
    continue
```

```python
# river/cluster/dbstream.py, 275 - 278
try:
    value = 2 ** (-self.fading_factor * (self._time_stamp - self.s_t[i][j]))
except OverflowError:
    continue
```

**Comment by hoanganhngo610** [comment]
@ShkarupaDC I'm really sorry but I don't really get your point here. If I understand it correctly, usually, the calculation

```
self._time_stamp - micro_cluster_i.last_update
or
self._time_stamp - self.s_t[i][j]
```
would never be large enough for an overflow. Instead, what we are trying to catch here is the calculation of the `value` variable itself, i.e when it is too large. As the author discussed in the discussion, in any case that the value is too large, even multiplying it with `micro_cluster_i.weight` would never make it less than the threshold, which is why we only catch the error and continue.

**Comment by ShkarupaDC** [comment]
[This](https://github.com/online-ml/river/issues/1468#issuecomment-1841256417) is how I understand why the error is captured for the first time. The **value** can not be a large number because the power of 2 is **negative**

**Comment by hoanganhngo610** [comment]
@ShkarupaDC Sorry I can finally get your point now. Yes even if `self._time_stamp - micro_cluster_i.last_update` or `self._time_stamp - self.s_t[i][j]` gets large enough, this would only cause an overflow (logically if and only if) the fading factor is negative, which is not supposed to happen. However, there has been some problems when people are applying DBSTREAM in certain use cases (you can have a look at #1168), which I will follow up with it now.

At this state, I suggest that we keep it stable (since in my use cases they don't really have any major impact) until we totally understand which caused the overflow.

**Comment by ShkarupaDC** [comment]
Thank you! Could you also look at the first point [here](https://github.com/online-ml/river/issues/1468#issuecomment-1841558233)? The current implementation may lead to the case when cluster 1 is removed and then recreated with non-zero shared densities because we did not clear them when popping it here:
```python
# river/cluster/dbstream.py, 259 - 268
for i, micro_cluster_i in self._micro_clusters.items():
    try:
        value = 2 ** (
            -self.fading_factor * (self._time_stamp - micro_cluster_i.last_update)
        )
    except OverflowError:
        continue

    if micro_cluster_i.weight * value < weight_weak:
        micro_clusters.pop(i)
```

**Comment by MaxHalford** [comment]
Guys, I'm not following deeply, but all I can recommend is that you write a couple of unit tests :)

**Comment by hoanganhngo610** [comment]
@MaxHalford Totally agree! I would write up the unit tests once we resolved all the issues.

@ShkarupaDC If I understand correctly, after removing the micro cluster i (by `micro_clusters.pop(i)`, you want to erase all the entries within the shared density and the time-points (i.e removing all `s[i][j]` or `s[j][i]` and `s_t[i][j] or `s_t[j][i]`). Is that correct?

**Comment by ShkarupaDC** [comment]
@hoanganhngo610, yes, you are right, it is my point!

**Comment by hoanganhngo610** [comment]
@ShkarupaDC Thank you very much! If that's the case, I suggest modifying the code as follows:

```python
# starting from line 267
            if micro_cluster_i.weight * value < weight_weak:
                micro_clusters.pop(i)
                self.s.pop(i)
                self.s_t.pop(i)
                for j in range(i):
                    try:
                        self.s[j].pop(i)
                        self.s_t[j].pop(i)
                    except KeyError:
                        continue
```

Do you think this should be appropriate for the task?

**Comment by ShkarupaDC** [comment]
@hoanganhngo610, looks good to me! We can use `pop(i, None)` to avoid catching the **KeyError**

**Comment by hoanganhngo610** [comment]
@ShkarupaDC All of the changese that we have discussed here have been incorporated into the main branch. If there is any other problem that still persists, please do not hesitate to let me know!
@MaxHalford I have also modified the unit tests and added one more on a synthetic dataset to investigate the behavior of DBSTREAM after changes. As @ShkarupaDC have also suggested previously, at some time, we can run some experiments to compare the performance of our version and the original implementation.
However, if there is nothing remains, I will proceed to close this PR.

**Comment by MaxHalford** [comment]
Good job @hoanganhngo610! In the future, can you please do pull requests instead of pushing to main? It's easier to see what changes you made that way.

>  However, if there is nothing remains, I will proceed to close this PR.

You mean this issue?

**Comment by hoanganhngo610** [comment]
@MaxHalford I will definitely do that for future issues! And yes, I mean closing this issue :D
