### ISSUE TITLE
More clustering metrics

### ISSUE THREAD

**Issue by rutujagurav** [online-ml/river#1495]
Hello,

Is it possible to implement more clustering metrics like [Calinski-Harabasz score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.calinski_harabasz_score.html) and [Davies-Bouldin score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.davies_bouldin_score.html#sklearn.metrics.davies_bouldin_score) ?

**Comment by MaxHalford** [comment]
Check out river-extra, [here](https://github.com/online-ml/river-extra/tree/main/river_extra/metrics/cluster) :)

**Comment by hoanganhngo610** [comment]
Thank you so much @MaxHalford!

In case there is no other requests on clustering metrics, I would proceed to close this issue. And thank you @rutujagurav for your question!
