### ISSUE TITLE
Obtaining Model memory in MB

### ISSUE THREAD

**Issue by sebasmos** [online-ml/river#1521]
I see that you report the model's memory in MB in https://riverml.xyz/0.21.0/benchmarks/Regression/ how do you calculate it? Thanks!

**Comment by smastelini** [comment]
It is a property of `base.Base`:

https://github.com/online-ml/river/blob/aac6318a5e9b593ac07ea55171121553d92ec712/river/base/base.py#L352-L389

**Comment by sebasmos** [comment]
Thanks!
