### ISSUE TITLE
The wrong units are used for binary size

### ISSUE THREAD

**Issue by e10e3** [online-ml/river#1582]
## Versions

**River version**: 0.21.2

## Describe the bug

There is a confusion in the units used to report the binary size of objects (the number of bytes).

In the library's documentation, decimal units are mentioned (kB, MB, GB, etc.), but the code handling them implicitly expects binary units and converts the quantities to bytes using powers of 2.

Instead, binary units should be used (KiB, MiB, GiB, etc.). This is mostly a documentation change.
There is nothing wrong in using base-2 units, given the proper unit names are used.

### Why does this matter?

River is commonly used for machine learning research, and being precise in one's intent is important. This helps to clear an ambiguity in reporting.

## Steps/code to reproduce

See `humanize_bytes`: the decimal units are used, but the quantity is divided by a power of 1024.

https://github.com/online-ml/river/blob/f18594c253cf10a8110e0060813d879a00620aac/river/utils/pretty.py#L63-L79

**Comment by smastelini** [comment]
Good catch, @e10e3! Ideally, we should correct the conversion and keep using the most commonly used units. I suspect some tests might break and we will need to update some docs/guidelines. I will make some tests and assess the magnitude of the changes and then ping you.

**Comment by e10e3** [comment]
I created a PR that changes the unit names but keeps the same conversion code. The changes are light.

> Ideally, we should correct the conversion and keep using the most commonly used units.

It depends on what you consider common. In computer science, I think the binary units are well-known (and the different symbol dissipates doubts).
That said, if you take all the scientific fields in account, the decimal units are more common.
