### ISSUE TITLE
Issue with Timeseries.Evaluate in River 

### ISSUE THREAD

**Issue by StephanieEpsteinUML** [online-ml/river#1586]
[debug_river.pdf](https://github.com/user-attachments/files/16431957/debug_river.pdf)
[example.csv](https://github.com/user-attachments/files/16431952/example.csv)

The .csv file, is a random dataset to be an example of what I am trying to do without giving the actual dataset. The .pdf is the code outline with the versions of the packages, along with the general script of what I am trying to achieve. Essentially, the first run through with river uses the first .csv or any .csv file to forecast ahead. If you went to run this with multiple files in a loop, the timeseries.evaluate does not produce values of the results such as the RMSE. Also, if you try to save the output to timeseries.evaluate, you are not able to save it either as a text file or a dataframe to compare many different file results for online learning prior to implementation. This is helpful for evaluation before deployment so that you can tune hyperparameters to find the right settings for the particular model of interest.

**Comment by smastelini** [comment]
Hi @StephanieEpsteinUML, thanks for reporting that. I could not access the complete code within the pdf (the data handling part). Besides that, I am not sure I completely understand what you are trying to do. Is there a loop around the code strip you sent in your real usage scenario?

 Without checking how you initialize the data, metrics, and models across multiple runs (aka, different datasets) it is hard to help. Could you provide an MWE?

**Comment by StephanieEpsteinUML** [comment]
import pandas as pd
import numpy as np
from river import drift, active, evaluate, preprocessing
from river.metrics import RMSE, MAE
from river.stream import iter_array, iter_pandas
from river import time_series
import pathlib, os, glob
from pathlib import Path

#Python 3.11.0 River 0.21.2 Pandas 2.2.2

directory_GLOB_PATH = list(Path(r".").glob("*.csv"))
directory = len(list(Path(r".").glob("*.csv")))

vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")] = pd.read_csv(directory_GLOB_PATH[0])
vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].index += 1
vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")] = vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].reset_index()
y_dict = dict(zip(vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].iloc[:,0], vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].iloc[:,1]))

# alpha = 1.4
# beta = 0.25
horizon = 50

model = time_series.HoltWinters(alpha=1.4,beta=0.05,seasonality=10,gamma=0.15, multiplicative=True)
metric = RMSE()

time_series.evaluate(
    dataset=iter(y_dict.items()),
    model=model,
    metric=metric,
    horizon=horizon)

for i in range(0, directory, 1):
    vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")] = pd.read_csv(directory_GLOB_PATH[i])
    vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].index += 1
    vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")] = vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].reset_index()
    y_dict = dict(zip(vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].iloc[:,0], vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].iloc[:,1]))

    # alpha = 1.4
    # beta = 0.25
    horizon = 50

    model = time_series.HoltWinters(alpha=1.4,beta=0.05,seasonality=10,gamma=0.15, multiplicative=True)
    metric = RMSE()

    time_series.evaluate(
        dataset=iter(y_dict.items()),
        model=model,
        metric=metric,
        horizon=horizon)

**Comment by StephanieEpsteinUML** [comment]
# %%
import pandas as pd
import numpy as np 
from river import drift, active, evaluate, preprocessing
from river.metrics import RMSE, MAE
from river.stream import iter_array, iter_pandas
from river import time_series
import pathlib, os, glob
from pathlib import Path

# %% [markdown]
# Python 3.11.0
# River 0.21.2
# Pandas 2.2.2

# %%
directory_GLOB_PATH = list(Path(r".").glob("*.csv"))
directory = len(list(Path(r".").glob("*.csv")))

vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")] = pd.read_csv(directory_GLOB_PATH[0])
vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].index += 1
vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")] = vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].reset_index()
y_dict = dict(zip(vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].iloc[:,0], vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].iloc[:,1]))

# alpha = 1.4
# beta = 0.25
horizon = 50

model = time_series.HoltWinters(alpha=1.4,beta=0.05,seasonality=10,gamma=0.15, multiplicative=True)
metric = RMSE()

time_series.evaluate(
    dataset=iter(y_dict.items()),
    model=model,
    metric=metric,
    horizon=horizon)

# %%
for i in range(0, directory, 1):
    vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")] = pd.read_csv(directory_GLOB_PATH[i])
    vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].index += 1
    vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")] = vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].reset_index()
    y_dict = dict(zip(vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].iloc[:,0], vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].iloc[:,1]))

    # alpha = 1.4
    # beta = 0.25
    horizon = 50

    model = time_series.HoltWinters(alpha=1.4,beta=0.05,seasonality=10,gamma=0.15, multiplicative=True)
    metric = RMSE()

    time_series.evaluate(
        dataset=iter(y_dict.items()),
        model=model,
        metric=metric,
        horizon=horizon)

**Comment by StephanieEpsteinUML** [comment]
` %%
import pandas as pd
import numpy as np 
from river import drift, active, evaluate, preprocessing
from river.metrics import RMSE, MAE
from river.stream import iter_array, iter_pandas
from river import time_series
import pathlib, os, glob
from pathlib import Path

 %% [markdown]
%%Python 3.11.0
%% River 0.21.2
%5 Pandas 2.2.2

%%
directory_GLOB_PATH = list(Path(r".").glob("*.csv"))
directory = len(list(Path(r".").glob("*.csv")))

vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")] = pd.read_csv(directory_GLOB_PATH[0])
vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].index += 1
vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")] = vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].reset_index()
y_dict = dict(zip(vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].iloc[:,0], vars()[str(directory_GLOB_PATH[0]).split("/")[-1].replace(".csv","")].iloc[:,1]))

%% alpha = 1.4
%% beta = 0.25
horizon = 50

model = time_series.HoltWinters(alpha=1.4,beta=0.05,seasonality=10,gamma=0.15, multiplicative=True)
metric = RMSE()

time_series.evaluate(
    dataset=iter(y_dict.items()),
    model=model,
    metric=metric,
    horizon=horizon)

%%
for i in range(0, directory, 1):
      vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")] = pd.read_csv(directory_GLOB_PATH[i])
      vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].index += 1
      vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")] = vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].reset_index()
      y_dict = dict(zip(vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].iloc[:,0], vars()[str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")].iloc[:,1]))`

**Comment by StephanieEpsteinUML** [comment]
Essentially, timeseries.evaluate will not report/print out results when set inside a for loop setting nor will it allow you to save in a DataFrame or a text file. Please let me know if this was what you were looking for?

**Comment by smastelini** [comment]
Hi, @StephanieEpsteinUML. From what I got from your code (the formatting is not helping), the loop would be something like:

```py
import pandas as pd
import numpy as np
from river import drift, active, evaluate, preprocessing
from river.metrics import RMSE, MAE
from river.stream import iter_array, iter_pandas
from river import time_series
import pathlib, os, glob
from pathlib import Path


directory_GLOB_PATH = list(Path(r".").glob(".csv"))
directory = len(list(Path(r".").glob(".csv")))

for i in range(0, directory, 1):
    dataset_name = str(directory_GLOB_PATH[i]).split("/")[-1].replace(".csv","")
    vars()[dataset_name] = pd.read_csv(directory_GLOB_PATH[i])
    vars()[dataset_name].index += 1
    vars()[dataset_name] = vars()[dataset_name ].reset_index()
    y_dict = dict(zip(dataset_name ].iloc[:,0], vars()[dataset_name ].iloc[:,1]))

    model = time_series.HoltWinters(alpha=1.4, beta=0.05, seasonality=10, gamma=0.15, multiplicative=True)
    metric = RMSE()
    
    time_series.evaluate(
        dataset=iter(y_dict.items()),
        model=model,
        metric=metric,
        horizon=horizon
    )
```

Is that correct?

**Comment by StephanieEpsteinUML** [comment]
yes

**Comment by smastelini** [comment]
I will try to reproduce the problem locally with the code and data you provided and give feedback soon!

**Comment by StephanieEpsteinUML** [comment]
okay, thank you

**Comment by smastelini** [comment]
I modified your code to fix the file reading part and also used `time_series.iter_evaluate` to retrieve the predictions and errors as described in your question. The following script works as expected:

```py
import pandas as pd
from river import metrics
from river import time_series
from pathlib import Path


horizon = 50
data_paths = list(
    str(file) for file in Path(".").iterdir() if str(file).endswith(".csv")
)
n_datasets = len(data_paths)

results = {}
for i in range(n_datasets):
    dataset_name = str(data_paths[i]).split("/")[-1].replace(".csv", "")
    print(dataset_name)
    vars()[dataset_name] = pd.read_csv(data_paths[i])
    vars()[dataset_name].index += 1
    vars()[dataset_name] = vars()[dataset_name].reset_index()

    y_dict = dict(zip(vars()[dataset_name].iloc[:, 0], vars()[dataset_name].iloc[:, 1]))

    model = time_series.HoltWinters(
        alpha=1.4, beta=0.05, seasonality=10, gamma=0.15, multiplicative=True
    )
    metric = metrics.RMSE()

    results[dataset_name] = [
        r
        for r in time_series.iter_evaluate(
            dataset=iter(y_dict.items()), model=model, metric=metric, horizon=horizon
        )
    ]

    results[dataset_name] = pd.DataFrame(results[dataset_name])
    # Add the corresponding names to the columns
    results[dataset_name].columns = ["timestamp", "y_true", "y_preds", "metrics"]


print(results["example1"])
# Prints one of the dataframes

# The last column carries the metrics, which can be accessed via .get()
print(results["example1"].iloc[0, -1].get())
```

Alternatively, you can pass an aggregation function to join the multiple evaluated forecasting horizons. For example, `agg_func=numpy.mean`. In this case, a `HorizonAggMetric` object is generated. Or you can extract the actual RMSE measurements from the metrics column:

```py
results["example1"].loc[:, "metrics"]= results["example1"].loc[:, "metrics"].apply(lambda x: x.get())

print(results["example1"].head(3))
```

Which produces:

```csv
   timestamp  y_true                                            y_preds                                            metrics
0         51    6005  [-49640.26422778916, -57376.78148196398, -2486...  [371468.58246216376, 567195.4131777475, 519366...
1         52    1577  [32103.470332699046, 13691.339431187535, 34377...  [371468.58246216376, 567195.4131777475, 519366...
2         53    5716  [-4764.369586552522, -12499.35017047809, -5042...  [371468.58246216376, 567195.4131777475, 519366...
```

I hope this answers your question. :D

**Comment by StephanieEpsteinUML** [comment]
thank you
