### ISSUE TITLE
The River website tries to execute code from https://polyfill.io

### ISSUE THREAD

**Issue by e10e3** [online-ml/river#1589]
## Versions

**River version**: 0.21.1
**Python version**: 3.12.5
**Operating system**: macOS 14.6.1

## Describe the bug

The River website makes a request to load the file at https://polyfill.io/v3/polyfill.min.js.

The domain polyfill.io was taken over by a malicious actor to download malware on user's computers. It was deactivated after the takeover was discovered, but should still be removed.

Reference : https://blog.qualys.com/vulnerabilities-threat-research/2024/06/28/polyfill-io-supply-chain-attack

## Steps/code to reproduce

1. Open the website at the URL https://riverml.xyz.
3. Open the developer panel (usually with the right-click menu or the F12 key).
4. Open the Network tab.
5. Reload the page.
6. See the line showing the request for `polyfill.min.js?features=es6` from `https://polyfill.io/v3/polyfill.min.js?features=es6`.

The request may be blocked by your ad blocker, if you have one[^1], to protect you.

The URL to load the code from is listed here:
https://github.com/online-ml/river/blob/b5e6fea4e4f564a5dd3c42cfc7622c1cefa820c9/mkdocs.yml#L88

[^1]: If you don't have an ad blocker, you should get one!

**Comment by gbolmier** [comment]
Apparently can be replaced with `https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js`. See this [Cloudflare blog post](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet) or this [reddit thread](https://www.reddit.com/r/cybersecurity/comments/1dpyatk/polyfillio_can_no_longer_be_trusted_and_should_be/).

**Comment by e10e3** [comment]
Is this shim still needed? As the various articles indicate, all modern browsers have good support of Javascript and do not need a polyfill.
In the case of the River website, a polyfill was asked only the ES6 features. According to [Can I Use…](https://caniuse.com/?search=es6), all major browsers have had full support of ES6 since 2017.

If we decide to continue using the polyfill, I would personally prefer to go with [Fastly's](https://community.fastly.com/t/new-options-for-polyfill-io-users/2540) replacement for decentralisation's sake, Cloudflare already has too much power.

**Comment by gbolmier** [comment]
Good point, we can remove it and add the Cloudflare mirror link later if needed 👍

**Comment by MaxHalford** [comment]
Thanks for taking care of this, it's much appreciated :)
