### ISSUE TITLE
The class CentralMoments from module stats cannot be instantiated

### ISSUE THREAD

**Issue by e10e3** [online-ml/river#1591]
## Versions

**River version**: 0.21.2
**Python version**: 3.12.5
**Operating system**: macOS 14.6.1

## Describe the bug

The class non-abstract [`CentralMoments`](https://github.com/online-ml/river/blob/main/river/stats/moments.py) inherits from `stats.base.Univariate`, but it does not implement any of the abstract methods. As a consequence, creating an instance throws a TypeError.
In addition, the class has no public method apart from the constructor.

There seem to be no reference to this class in River's code.

The last reference to this class in River appears to have been removed during the migration to Rust statistics (commit 5f88f7c80837afb80b37bcb5f57c1149126acfea).

## Steps/code to reproduce

```python
from river.stats.moments import CentralMoments
c = CentralMoments()
```

Output:
```
TypeError: Can't instantiate abstract class CentralMoments without an implementation for abstract methods 'get', 'update'
```

**Comment by gbolmier** [comment]
Good catch @e10e3! Feel free to delete the `stats.moments` module
