### ISSUE TITLE
Python 3.13 wheel distribution

### ISSUE THREAD

**Issue by Bing-su** [online-ml/river#1622]
Thanks for maintaining this library!
Could you add support for Python 3.13 in the next release?

**Comment by MaxHalford** [comment]
For sure! @gbolmier how would you feel about taking care of this? I can take care of it if you're jampacked

**Comment by gbolmier** [comment]
@Bing-su please follow the progress in the linked PR. We'll make a new release once the support for `3.13` is merged to `main`.
