### ISSUE TITLE
Exponential smoothing

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#168]
I would like to see [exponential smoothing](https://www.wikiwand.com/en/Exponential_smoothing) added to the `time_series` module. Rob Hyndman gives a good overview of it [here](https://otexts.com/fpp2/expsmooth.html). To be as general as possible I think we should produce an implementation which supports the 9 variants described [here](https://otexts.com/fpp2/taxonomy.html). Note that this shouldn't be too difficult to implement, as the equations are straightforward and easy to unit test.

**Comment by AdilZouitine** [comment]
I´m in #239 😄
