### ISSUE TITLE
Disable pipeline's fit_one from transforming if all items inside the pipeline is a transformer

### ISSUE THREAD

**Issue by mxlei01** [online-ml/river#254]
Is it possible to stop a pipeline from transform_one before fitting?

In other words to disable transforming during a fitting?

According to:

```python
def fit_one(self, x, y=None, **fit_params):
        """Fits each step with ``x``."""

        # Loop over the first n - 1 steps, which should all be transformers
        for t in itertools.islice(self.values(), len(self) - 1):
            x_pre = x
            x = t.transform_one(x=x)

            # If a transformer is supervised then it has to be updated
            if t.is_supervised:

                if isinstance(t, union.TransformerUnion):
                    for sub_t in t.values():
                        if sub_t.is_supervised:
                            sub_t.fit_one(x=x_pre, y=y)

                else:
                    t.fit_one(x=x_pre, y=y)

        self.final_estimator.fit_one(x=x, y=y, **fit_params)
        return self
```

It will try to transform_one before fitting, and this is causing issues for me where I need to fit and check dictionary keys, and to add them to a list before doing some cleanups.

I think the main issue is that my pipeline only contains all transformers, and no estimators.

**Comment by mxlei01** [comment]
Currently my solution is to monkey_patch the `fit_one` function with a modified version of fit that does not fit the final item (an estimator).

def fit_one(self, x, y=None, **fit_params):
    """Fits each step with ``x``."""
    # Loop over all the steps
    for t in itertools.islice(self.values(), len(self)):

        # If a transformer is supervised then it has to be updated
        if t.is_supervised:

            if isinstance(t, union.TransformerUnion):
                for sub_t in t.values():
                    if sub_t.is_supervised:
                        sub_t.fit_one(x=x, y=y)

            else:
                t.fit_one(x=x, y=y)

    return self

pipeline.fit_one = fit_one.__get__(pipeline, Pipeline)

where `pipeline` is an Pipeline object.

**Comment by MaxHalford** [comment]
Hey there! Can you try to describe a bit more what you're trying to do? You only have transformers, right? I'm having a hard time trying to understand why you wouldn't want to transform before fitting :). Essentially, transforming has to be done in order to communicate with the next step of the pipeline.

It would help a lot if you describe your use case a bit more :)

**Comment by mxlei01** [comment]
@MaxHalford Actually I think I was not using the pipeline correctly. I do have another question though, why does pipeline transform first then fit?

Isn't it more logical to first fit and then transform like scikit-learn?

Example:

```
class PipelineTransformers(Pipeline):
    def fit_one(self, x, y=None, **fit_params):
        """Fits each step with ``x``."""

        # Loop over the first n - 1 steps, which should all be transformers
        for t in itertools.islice(self.values(), len(self) - 1):
            # If a transformer is supervised then it has to be updated
            if t.is_supervised:

                if isinstance(t, union.TransformerUnion):
                    for sub_t in t.values():
                        if sub_t.is_supervised:
                            sub_t.fit_one(x=x, y=y)

                else:
                    t.fit_one(x=x, y=y)
                    
            x = t.transform_one(x=x)

        self.final_estimator.fit_one(x=x, y=y, **fit_params)
        return self
```

Extending your Pipeline class to have a different fit_one function where I fit before transform. I have some custom transforms using your base.Transformer requires to fit first, and then do some transform to pass the data downwards.

My flow looks like:

fit => transform => fit => transform

But the original fit function was:

transform => fit => transform => fit

Is this correct?

**Comment by MaxHalford** [comment]
Actually it's a bit more complicated than that, but you're raising a very important topic. The tranformer steps of a pipeline are in fact fitted in the `predict_one` and `predict_proba_one` methods! This makes sense in an online context because to train the unsupervised parts of our pipeline as soon as possible, and so we can do that without requiring `y`. In the `fit_one` method, only the supervised parts of the pipeline are updated. What you're proposing would work, but it would be slightly suboptimal.

**Comment by mxlei01** [comment]
@MaxHalford 

Is it possible to support this kind of behavior where we fit first using a boolean variable? I can help to create a pull request.

Although I think placing this kind of behavior makes the code a little less elegant.

Maybe the best solution is for me to subclass Pipeline?

**Comment by MaxHalford** [comment]
Just to understand, why would you want to fit before predicting? What's your usecase?

**Comment by mxlei01** [comment]
I have a large amount of rows that I want to iterate through first to create a preprocessing pipeline.

My workflow is like this:
1. Iterate through all the data with fit_one
2. Transform each row later with transform_one

The above process becomes a preprocessing pipeline.

3. Create a file with all the file transformed.
4. Create a model based on the file.

5. Deploy the preprocessing pipeline with the model embedded with another pipeline, so this new pipeline contains the preprocessing pipeline, and the fitted model where I create a base transformer with it.

Now all the transforms from 5 can perform prediction.

I think my use case isn't exactly what the library is intended to be used?

**Comment by MaxHalford** [comment]
Sorry but it's still exactly clear what you're trying to do... Are you looking to do some kind of warming up? Also do you have some code?

`creme` might not be able to do what you'd like it to do, but I'd like to get a better understanding of your usecase. The API isn't set in stone so we can still do some big changes if necessary :)

**Comment by mxlei01** [comment]
The API is nice and documented, and I'm not sure if it even needs a change.

The code is company property though, however it may be possible to join a screen chat looking over my code if you are willing. Just need to get my company's approval if you'd like to have a look.

**Comment by MaxHalford** [comment]
That would be nice :). Take your time!

**Comment by MaxHalford** [comment]
See #503 where we've added the possibility to not update unsupervised parts of the pipeline during `predict_one`.
