### ISSUE TITLE
Implement Cython dict

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#280]
We really want to give a shot at implementing a fast dictionary in Cython. scikit-learn has one [here](https://github.com/scikit-learn/scikit-learn/blob/5e7ff0d0cde7b997ee5bc1300c2dc5bdac4c2608/sklearn/utils/_fast_dict.pyx). This could potentially be very useful for linear models.

**Comment by MaxHalford** [comment]
@brcharron has done a wonderful job at implementing `utils.VectorDict`, which is dictionary-like data structure that has methods implemented in Cython. For instance it implements the `@` operator for doing a dot product. Let's use in the `linear_model` module before closing this issue.

**Comment by MaxHalford** [comment]
`VectorDict` has been successfully integrated into `linear_model`. We will now focus on the optimizers from the `optim` module. We will keep this issue open for potential discussions.

**Comment by raphaelsty** [comment]
@brcharron Nice job, it's really cool to get good performance with dictionaries.

**Comment by brcharron** [comment]
The [`WeightVector`](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/_weight_vector.pyx) class in `sklearn` could be used as inspiration for further work, it implements custom functions like `w += c * u` or `w *= c`.

**Comment by MaxHalford** [comment]
I took a go at converting the AdaDelta optimizer and ran into some issues. The current code is:

```
for i, gi in g.items():

    self.g2[i] = self.rho * self.g2[i] + (1 - self.rho) * gi ** 2
    step = - self._rms(self.s2[i]) / self._rms(self.g2[i]) * gi
    self.s2[i] = self.rho * self.s2[i] + (1 - self.rho) * step ** 2
    w[i] += step
```

I wrote the following vector notation:

```
if self.g2 is None:
    self.g2 = base.empty_like(g)
    self.s2 = base.empty_like(g)

self.g2 = self.rho * self.g2 + (1 - self.rho) * g ** 2
step = -self._rms(self.s2) / self._rms(self.g2) * g
self.s2 = self.rho * self.s2 + (1 - self.rho) * step ** 2
w += step
```

The `empty_like` function is defined as so:

```python
def empty_like(x):
    if isinstance(x, utils.VectorDict):
        return utils.VectorDict({})
    return np.empty_like(x)
```

One issue I had is that multiplication (`*`) between a `VectorDict` and a `VectorDict` doesn't work. Likewise for division (`/`). I also implemented the power function (`**`). Any particular thoughts on this @brcharron? I looked at the other optimizers and we also need to implement `abs`. Finally, we need a function for calculating the `min`/`max` with respect to a scalar as well as a vector. I think what I have listed covers most stuff, and will allow every optimizer to be written in vector notation.

**Comment by brcharron** [comment]
Thanks for the feedback. Indeed I only implemented the operations of a mathematical vector so no multiplication or division of two vectors. I can work on that, should be easy enough, and `abs` as well. As for `min`/`max`, that seems like `np.maximum` which is not a method of the array, `.max()` would be expected to return the maximum value in the vector. How do you see it? An external `maximum`, overloading like `.max(other=None)`, or a `.maximum(other)` or something that would distinguish from `.max()`?

In `empty_like` it's fine to use `utils.VectorDict()`.

**Comment by MaxHalford** [comment]
Yes indeed `.max()` should return the vector's max value. `.maximum(other)` should compute the element-wise maximum.

The reason why I added the `empty_like` like function is that I want the optimizers to work with arrays. Some optimizers requires initializing some empty vectors, but we only what kind of array will be used at runtime (`VectorDict` or `numpy.ndarray`). Not sure this is very clear to everybody.

**Comment by brcharron** [comment]
Got it, will implement all that. `numpy.ndarray` don't have `.maximum` so probably will need a `utils.math.maximum` wrapper which works for both types.

**Comment by brcharron** [comment]
How do you see multiplication / division of vectors with different keys? Could be either on the union or the intersection of the keys. For multiplication both should be fine but for division, union would likely lead to divisions by zero. The behavior should likely be the same for both so maybe intersection.

**Comment by MaxHalford** [comment]
Well the union seems reasonable. We don't need to do anything for keys that are in `right` but not in `left`. We can also ignore the case where a key is in `left` but not in `right` (division by 0).

**Comment by MaxHalford** [comment]
About `utils.math.maximum`; I'm not 100% sure but here is my opinion. I think it's fine to attach many functions to `VectorDict`, such as `maximum` as well as `max`. It will ease documentation and I don't see any reason not do to do this. As for handling numpy arrays as well as `VectorDict`s, I would handle this within each optimizer, or in a `utils` submodule of the `optim` module. The way I see it is that this equivalence between `VectorDict`s and numpy arrays should only exist in the `optim` module for a good reason: neural networks where all but the first layer's weights have a fixed size, and thus justify the use of numpy.

**Comment by brcharron** [comment]
I made a PR #318 that shows the behavior using the union of keys (see the tests).
Probably for `*` we don't want to just keep the keys of `left` as it would make it non-commutative.
For `/` it could be but that's a different behavior from `+`, `-` and `*` and there is the possibility that there is a `default_factory` which return non-zero values. Not sure if there is any similar operation that can be used as analogy, either in math or another library.

Ok for `utils.math.maximum`, didn't include it.

**Comment by MaxHalford** [comment]
The PR looks good, nice one. About `*`, you're right that it should be commutative. It's really just a question of wasting memory usage. The current behaviour is fine 👍

**Comment by brcharron** [comment]
Great. That's true and it may return many `0`s but it's consistent with the support of `default_factory`. Same for the dot product, could just loop on the key intersection otherwise.

**Comment by MaxHalford** [comment]
Just some news on this @brcharron: we're currently deep into the process of merging with scikit-multiflow. I'll get back into propagating `VectorDict` throughout the codebase once we've made more progress on that side :)
