### ISSUE TITLE
Update many for metrics

### ISSUE THREAD

**Issue by AdilZouitine** [online-ml/river#310]
It would be very interesting to implement this method in order to be able to update the metrics in batch.

**Comment by AdilZouitine** [comment]
Should we rename the update method to update_one with the addition of the new update_many method?

**Comment by MaxHalford** [comment]
Mmm for the moment I would say no. I would rather start by defining an `update_many` method in the `Metric` mother class.

**Comment by AdilZouitine** [comment]
PR #317

**Comment by MaxHalford** [comment]
Actually after the last talk with scikit-multiflow, we've decided on something different for metrics :). I'll leave your PR open for the moment.
