### ISSUE TITLE
Use mini-batch to reduce I/O overhead and speed up independent operations

### ISSUE THREAD

**Issue by gbolmier** [online-ml/river#324]
Related to #234 

The idea is to stick to the online regime, but instead of loading one sample at a time, we could load mini-batch to benefit from memory resources when available.

Also, pre-processing operations that are independent from previous samples could benefit of a nice speed up if treated with mini-batch. We could think of parallelizing `TransformerUnion` for such cases.

Some benchmarking/profiling would be interesting.

**Comment by MaxHalford** [comment]
Let's drop this now that vaex support is possible. It would be nice to have but in the end it's not really a priority for this to be in River. Other libraries can and will do this better than us.
