### ISSUE TITLE
fail to import model_selection 

### ISSUE THREAD

**Issue by LeonardAukea** [online-ml/river#340]
I'm trying to just run the examples from the docs. I seem to fail to import `model_selection`. It I could not find it on the master branch either.  

```
-----------------------------------------------------------
ImportError               Traceback (most recent call last)
<ipython-input-178-0c70db37b907> in <module>
      2 from creme import linear_model
      3 from creme import metrics
----> 4 from creme import model_selection
      5 from creme import preprocessing
      6 from creme import optim

ImportError: cannot import name 'model_selection' from 'creme' (/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/creme/__init__.py)
```

**Comment by LeonardAukea** [comment]
Ok, I guess you have moved it to `evaluate` https://github.com/creme-ml/creme/blob/dd42c852f7a05c7402dceb80be4800c3b4f4ec6c/creme/evaluate/progressive_validation.py#L14

maybe worth updating docs.

**Comment by MaxHalford** [comment]
Hey @LeonardAukea! On what version of `creme` are you testing? We renamed `model_selection` to `evaluate` but that only affects the development branch.

We're in the process with merging with `scikit-multiflow`. It's a big undertaking and a fair amount of things will change.
