### ISSUE TITLE
Add debug_one to logistic regression

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#346]
It would be nice to add a `debug_one` method to `linear_model.LogisticRegression`. There's a great overview of explaining logistic regression [here](https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/).

**Comment by manesioz** [comment]
I can work on a PR for this if you're still looking for someone to pick this up

**Comment by MaxHalford** [comment]
Yes that would be lovely! I've just started a new job so I have very little bandwidth for implementing new stuff atm. I'll always allocate time for reviewing PRs and advising though.

**Comment by manesioz** [comment]
Awesome. And our of curiosity, how will the merger affect this and subsequent PRs? Should we even bother adding new features or will that only make the merger more difficult?

**Comment by MaxHalford** [comment]
Good question! The merger shouldn't have too much impact. The only significant difference is that we're going to rename `fit_one` to `learn_one` and `fit_many` to `learn_many`. You can make a pull request to the `the-merge` branch or to `master`, I'll sort out discrepancies myself :)

**Comment by manesioz** [comment]
Sounds good!

**Comment by MaxHalford** [comment]
Adding this to the [roadmap](https://www.notion.so/d1e86fcdf21e4deda16eedab2b3361fb?v=503f44740b8b44a99a961aa96e9e46e1) instead.
