### ISSUE TITLE
What will the new logo look like?

### ISSUE THREAD

**Issue by kivo360** [online-ml/river#384]
The question in the title.

**Comment by MaxHalford** [comment]
Patience my friend :)

**Comment by raphaelsty** [comment]
My proposal was:

![4lzfqf](https://user-images.githubusercontent.com/24591024/98842740-4d6b7580-244a-11eb-80a9-05153197767c.jpg)

Not sure it's appropriate...

**Comment by MaxHalford** [comment]
Hahaha! We actually have got a logo. I'm just waiting on the files.

**Comment by kivo360** [comment]
DOPE!!!!

**Comment by MaxHalford** [comment]
Glad you like it! In France, the 3-wave symbol is used to indicate a river :). 

We'll make t-shirts when we reach 2k stars ;)
