### ISSUE TITLE
Multinomial object while using RandomForest gives Attribute Error

### ISSUE THREAD

**Issue by mfsuve** [online-ml/river#392]
---
name: Bug report
about: Multinomial object while using RandomForest gives Attribute Error
title: Multinomial object has no attribute keys
labels: RandomForest, Multinominal, AttributeError
assignees: ''

---

## Versions

**river version**: 0.6.1
**Python version**: Python 3.8.5
**Operating system**: Windows 10

## Describe the bug

In some cases when using `RandomForestClassifier`, `CategoricalSplitEnum `class is used and it has a dictionary of Multinomial distribution. In `enumerate_splits `function of this class, the code below asks for keys of Multinomial distribution and gets an AttributeError saying `AttributeError: 'Multinomial' object has no attribute 'keys'`.

    categories = set(*(p_x.keys() for p_x in self.P_xy.values()))

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
```
```
from creme import tree
from creme import metrics
from creme.stream import iter_pandas
import pandas as pd
from pprint import pprint

X = pd.read_csv('../data.csv')
y = pd.Series(np.random.randint(2, size=X.shape[0]))

model = tree.RandomForestClassifier()
metric = metrics.Accuracy()

for i, (X, y) in enumerate(iter_pandas(X, y), 1):
    y_pred = model.predict_one(X)      # make a prediction
    metric = metric.update(y, y_pred)  # update the metric
    model = model.fit_one(X, y)        # make the model learn
    
print(metric)
```

[data.zip](https://github.com/online-ml/river/files/5589321/data.zip)

**Comment by MaxHalford** [comment]
Can you please install `river` by running `pip install git+https://github.com/online-ml/river --upgrade` and try again? You're using `creme`, which is the ancestor of `river`.

**Comment by mfsuve** [comment]
I ran that command and I got this error.
```
confusion.c
    C:\Users\mus-k\Anaconda3\envs\temp\include\pyconfig.h(59): fatal error C1083: i‡erme dosyas\x8d a‡\x8dlam\x8dyor: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\mus-k\Anaconda3\envs\temp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mus-k\\AppData\\Local\\Temp\\pip-req-build-p0mxitl3\\setup.py'"'"'; __file__='"'"'C:\\Users\\mus-k\\AppData\\Local\\Temp\\pip-req-build-p0mxitl3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mus-k\AppData\Local\Temp\pip-record-zbh9sb50\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\mus-k\Anaconda3\envs\temp\Include\river' Check the logs for full command output.
```
It has also a bunch of logs above that error message.

**Comment by MaxHalford** [comment]
Do you have GCC installed?

**Comment by mfsuve** [comment]
I don't think I have. I am using Windows, how can I install it?

**Comment by mfsuve** [comment]
OK, after a day of just researching about this, I think I finally managed to install river. For anyone who struggles as I did, I first downloaded [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16), after installing it, I chose _C++ build tools_ and installed _MSVC v142 - VS 2019 C++ x64/x86 build tools_ and _Windows 10 SDK_. Finally, I searched for _x64 Native Tools Command Prompt for VS 2019_ and ran `pip install git+https://github.com/online-ml/river --upgrade` on this Command Prompt and it worked.
