### ISSUE TITLE
Update Main Page Documents From Online-ML to 

### ISSUE THREAD

**Issue by kivo360** [online-ml/river#395]
## Versions

**river version**:
**Python version**:
**Operating system**:

## Steps/code to reproduce

Go to the main page and you'll see the link [Documentation](https://online-ml.github.io/) and [much more](https://online-ml.github.io/content/api.html). They should redirect to https://riverml.xyz/. Though, when I go to that it raises some troubles too.

```python
# Sample code to reproduce the problem
```

**Comment by MaxHalford** [comment]
I'm working on it :). See the [issue](https://github.com/jimporter/mike/issues/29#issuecomment-733147957) on the mike project.
