### ISSUE TITLE
vaex integration example

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#399]
[vaex](https://github.com/vaexio/vaex) is a very powerful data processing tool. This [Medium article](https://towardsdatascience.com/ml-impossible-train-a-1-billion-sample-model-in-20-minutes-with-vaex-and-scikit-learn-on-your-9e2968e6f385) on how they process 1 billion samples in 20 minutes with scikit-learn's `SGDClassifier` is mind-blowing. Now that we support mini-batches, and in particular pandas DataFrames, we should able to reproduce this example. [This](https://vaex.readthedocs.io/en/latest/tutorial_ml.html) is also relevant. I expect that we should be slightly faster than scikit-learn.

For context, see [this issue](https://github.com/vaexio/vaex/issues/747) on the vaex repository. Note that the vaex authors are really nice people who are aware of our project and would really like to collaborate with us. In a nutshell, they're experts at data processing, and are looking for expertise in online learning.

**Comment by venuraja79** [comment]
Both the vaex and river are impressive frameworks. I can assist here if this requirement is still open.

**Comment by venuraja79** [comment]
Hello @MaxHalford,
Spent sometime adapting the notebook above for training with river (using the yet to be released river integration (https://github.com/vaexio/vaex/pull/1256)). Please take a look at this colab notebook. Hope this is helpful - https://colab.research.google.com/drive/11N8Nid147W0lQiA7yhKqOfto-DocCxXi?usp=sharing

**Comment by MaxHalford** [comment]
Adding this to the [roadmap](https://www.notion.so/d1e86fcdf21e4deda16eedab2b3361fb?v=503f44740b8b44a99a961aa96e9e46e1) instead.
