### ISSUE TITLE
Activating mypy on CI

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#400]
We've made great strides to add type hints to our code. However, we're not done yet. Running [`mypy`](http://mypy-lang.org/) still raises errors. It would be great to spend some time and finish tidying up our code to satisfy `mypy`. I can then `mypy` to the tests workflow in the CI.

**Comment by smastelini** [comment]
+1 to that!

**Comment by MaxHalford** [comment]
Adding this to the [roadmap](https://www.notion.so/d1e86fcdf21e4deda16eedab2b3361fb?v=503f44740b8b44a99a961aa96e9e46e1) instead.
