### ISSUE TITLE
Is there any way to save or convert model to tensorlfow pb model ?

### ISSUE THREAD

**Issue by pardont** [online-ml/river#414]
Is there any way to save or convert model to tensorlfow pb model? I try to classify image, much slow than tensorflow.

**Comment by MaxHalford** [comment]
Alas, River is really not suited for image classification. It's not the kind of workloads we're looking to solve.

**Comment by pardont** [comment]
hi MaxHalford, thank for your reply, is there any way to save or convert model to other model? such as tensorflow, caffe or pytorch.

**Comment by MaxHalford** [comment]
Which model are you talking about? Why would you want to do that?

**Comment by pardont** [comment]
My thoughts：
the speed to classify image is low,  because river model contains structures and paramenters for online learning.  can we convert the trained model to a simple one to improve the predict speed.  just like teacher-student mode.

**Comment by MaxHalford** [comment]
Sorry but this is really not clear and needs framing. You're going to have to provide more detail.
