### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by microprediction** [online-ml/river#415]
Probably a dumb question but what would the example in the docs here: 
https://github.com/online-ml/river/blob/master/river/time_series/snarimax.py
or perhaps the example https://github.com/online-ml/river/blob/master/docs/examples/quantile-regression-uncertainty.ipynb look like if there was no exogenous variable? 

I'm a little confused as to the canonical way to establish a simple univariate ARIMA model (say) with no exogenous variables. I.e. just y and no x.

**Comment by SikandAlex** [comment]
Not trying to be mean or anything @microprediction but that's a terrible title for your issue. It may be resolved faster if you rename it.

**Comment by MaxHalford** [comment]
Hey @microprediction you just have to omit `x`. I agree that we should put more effort in the docs regarding the `time_series` module, it just isn't a priority as of now.
