### ISSUE TITLE
tsfresh support

### ISSUE THREAD

**Issue by markoarnauto** [online-ml/river#427]
I was wondering how to integrate [tsfresh](https://github.com/blue-yonder/tsfresh) into river?
According to the [docs](https://tsfresh.readthedocs.io/en/latest/text/forecasting.html) it is intended for online-learning.

**Comment by MaxHalford** [comment]
I didn't know tsfresh pursued this direction. However, I'm afraid that it's somewhat incompatible with what we're doing. What they're doing is that they produce a batch of features at every time step. I imagine that you could retrain a model for every batch that tsfresh gives, but that wouldn't be true online learning. The River philosophy would instead be to "yield" a single observation every time. Maybe that we can have a chat with the tsfresh maintainter(s) and see what can be done :)
