### ISSUE TITLE
Request to update the hyperlinks from Getting Started page of Website

### ISSUE THREAD

**Issue by katreparitosh** [online-ml/river#428]
Hello,

Just a gentle request/reminder to update the hyperlinks to API Reference, User Guide, Examples, etc. from the last paragraph of [Getting Started](https://riverml.xyz/latest/getting-started/getting-started/) page of the website.

**Comment by MaxHalford** [comment]
Hey! It's my bad, I thought I'd done this :(. I just checked with [deadlinkchecker.com](https://www.deadlinkchecker.com/website-dead-link-checker.asp) and we have a lot of dead links. I'll get this fixed... next year :). I'll take care of this @smastelini :).

**Comment by MaxHalford** [comment]
Fixed 👍
