### ISSUE TITLE
Error during installation on Windows

### ISSUE THREAD

**Issue by chetanambi** [online-ml/river#429]
Hi - I am trying to install river on Windows machine but running into below error message. Error message says Microsoft Visual C++ 14 or higher to be installed. And  it is already installed on my machine. But still I am running to error. 

**river version**: latest version
**Python version**: 3.9.1
**Operating system**: Windows 64-bit

**Error message**
------------------
-------------------
copying river\utils\vectordict.pyx -> build\lib.win-amd64-3.9\river\utils
    running build_ext
    building 'river.metrics.confusion' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\chetan_ambi\.conda\envs\river\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chetan_ambi\\AppData\\Local\\Temp\\pip-req-build-d8m0y3nz\\setup.py'"'"'; __file__='"'"'C:\\Users\\chetan_ambi\\AppData\\Local\\Temp\\pip-req-build-d8m0y3nz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chetan_ambi\AppData\Local\Temp\pip-record-h9hgxz_7\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\chetan_ambi\.conda\envs\river\Include\river' Check the logs for full command output.

**Comment by MaxHalford** [comment]
Hey!

See [this](https://github.com/online-ml/river/issues/381) thread!

In a couple of weeks (hopefully), we'll be able to build wheels, which means that you won't need to compile the library yourself. In the meantime, you need to install the C++ build tools.
