### ISSUE TITLE
Warn user if m=0 in SNARIMAX 

### ISSUE THREAD

**Issue by microprediction** [online-ml/river#432]
I suggest warning the user if m=0 in SNARIMAX, or perhaps just interpreting m=0 or m=None as m=1 ??  

Reproduce behaviour here by setting m=0 [notebook](https://github.com/microprediction/timeseries-notebooks/blob/main/river_hello.ipynb)

**Comment by MaxHalford** [comment]
A PR is welcome :)

**Comment by microprediction** [comment]
Will do. And I was planning on more substantive PRs, but I have one philosophical question. Do you want algorithms that sporadically fit under the hood but take on the interface of a streaming algorithm, or would that pollute the library? 

Example: An algorithm that fits once every 1000 data points.  
Example: A loss function that is computed every 1000 data points. 
I can't find a streaming version of https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.energy_distance.html for instance.

**Comment by MaxHalford** [comment]
Refitting models on a schedule is out-of-scope of River. There's `learn_many` and `predict_many` but that's for processing a mini-batch of data.

**Comment by microprediction** [comment]
That makes sense. The scope would explode otherwise.  I'll take a closer look at online energy and W distance.
