### ISSUE TITLE
Does River support deep learning models?

### ISSUE THREAD

**Issue by chetanambi** [online-ml/river#434]
I am new to Online (incremental) learning. I have the model built using keras/tensorflow. I wanted to know in order to implement incremental learning, River supports only the algorithms are part of River? I did look into River documentation and it seems we can use incremental learning only with the models that are implemented in River. Can you please let me know.

**Comment by MaxHalford** [comment]
Hello. River's primary focus is not on deep learning models. There's a little utility to run `PyTorch` models in the `compat` module but it's nothing serious.

Just to be clear: neural networks are already incremental because you train them with mini-batches.
