### ISSUE TITLE
Is there a way to export Tree models?

### ISSUE THREAD

**Issue by charliec443** [online-ml/river#437]
Hi, 

I'm just wondering if there is a straightforward way to export tree models to scikit-learn style interface so that we can leverage other libraries like:

* shap - if you see here: https://github.com/slundberg/shap/blob/master/shap/explainers/pytree.py if the tree model is in a supported format then we can use this library out of the box
* in the previous scikit-multiflow, one could export rules of individual trees; I surmise if we could export things as scikit-learn trees, then Skope-rules could be used (especially if there is a magical way to also allow a consistent interface for tree ensembles, though this could be non-trivial)

Is this something that may be supported?

**Comment by smastelini** [comment]
Hi @chappers, unfortunately our tree models are not currently compatible with sklearn's. It's in our plans to optimize some aspects of the trees but it's not trivial to use the same array-based structure adopted by sklearn in online tasks. This strategy might not be the most suitable one for incremental trees (that's something we intend to check). 

That said, it's also in our plans to bring rule-based models to river, as they appeared in skmultiflow. We want to refactor the previously existing algorithm to enhance modularity and performance (or even code them from scratch if needed). We could enable trees to export rules again, if that's in the interest of the community. 

I am not familiar with Skope-rules but we have in mind some algorithms to bring to river. For instance:

- Very Fast Decision Rules (classification)
- Adaptive Model Rules (AMRules)

Both of them are similar in their inner workings. Any help is welcomed, if you are interested in helping :)

Pinging @jacobmontiel, as he was involved in the implementation/review of skmultiflow's rule algorithm.

**Comment by jacobmontiel** [comment]
As mentioned by @smastelini the new implementation of the trees in `river` is different from what we used in `scikit-multiflow`. This is down to optimization for the instance-incremental setting. That being said, existing rules methods are likely to follow a similar refactoring. However, the functionality to retrieve the rules will remain. A potential issue is that predicates will need to support `keys` instead of attribute indexes.

**Comment by chappers** [comment]
I may have a go at seeing if I can integrate `river` with `shap` as it is something which I have a strong preference for. Afterwards if I get a good handle for the internals of `river` I may give the rules a go.

**Comment by chappers** [comment]
Okay, so its always easier to show than tell. Here is a full example of what I'm looking for, or seeking guidance whats the best way to integrate into this library. Of course we could also ask `shap` maintainers how they would like to ingest externally generated tree models, in the scenario we don't really care about performance as well. 

The rough outline of this code is:

*  Go through the tree structure via `_tree_root.iter_edges()` to create a `json` dump in the same format as LightGBM
*  Ingest this into the `shap` library and "trick" the library into running it naively

Here is a sample plot output that is generated: 

![output](https://user-images.githubusercontent.com/2498638/105448184-eda30d80-5cc9-11eb-9ff6-d57b14a52ea1.png)

I'll put the code in a gist as it is > 200 LoC

https://gist.github.com/chappers/1529a5bcc730de83f476da2a1096c6fe

**Comment by smastelini** [comment]
Would it be possible to use a pandas dataframe describing the tree structure as a generic input representation?

We are planning to add such functionality to the tree module soon.

**Comment by chappers** [comment]
I'll have to think about what the dataframe structure would look like - I do think it is plausible though.

**Comment by MaxHalford** [comment]
I was thinking of something like this:

| index | parent | split_feature | split_value    | split_type |
|-------|--------|---------------|----------------|------------|
| 0     | None   | foo           | ('abc', 'def') | in         |
| 1     | 0      | bar           | 12             | <          |
| 2     | 0      | bar           | 18             | <          |

**Comment by chappers** [comment]
If we approach it this way, then the purpose of dumping the tree to this format is for visualisation and post-hoc analysis right?

If it was as an intermediary format for deserialising/serialising models, we would need to hold stats for each node which might not be ideal?

**Comment by MaxHalford** [comment]
Yes it would just for viz and analysis. You're right the mixed is icky.

**Comment by chappers** [comment]
I think #568 is pretty close to what I'm after. I think it becomes a bit more obvious to export to an scikit-learn model so that you can use shap:

```py
from river import tree
from river import stream
import shap
import numpy as np
import pandas as pd
import sklearn


X, Y = shap.datasets.boston()
# we'll try to use this: https://github.com/slundberg/shap/blob/master/notebooks/tabular_examples/tree_based_models/Example%20of%20loading%20a%20custom%20tree%20model%20into%20SHAP.ipynb
mod = tree.HoeffdingTreeRegressor(max_depth=2)

for _ in range(100):
    for x, y in stream.iter_array(X.values, Y, feature_names=X.columns):
        # print(xi, yi)
        mod.learn_one(x, y)
        y_pred = mod.predict_one(x)

# try to get the dataframe
mod_df = mod.to_dataframe()
mod.draw().save("test.png")


def to_array_dict(df, feature_names=None):
    # converts to an array format for scikit learn + shap
    df["node"] = df.index

    thresholds = np.array(df[~df.is_leaf]["threshold"].tolist())
    values = [x.mean.mean for x in df["stats"].tolist()]
    node_sample_weight = [x.mean.n for x in df["stats"].tolist()]

    children_left = []
    children_right = []
    features = []

    for node in df.index:
        df_ = df[df["parent"] == node]
        if df_.shape[0] == 0:
            children_left.append(-1)
            children_right.append(-1)
        else:
            children_left.append(df_["node"].tolist()[0])
            children_right.append(df_["node"].tolist()[1])
        feat = df[df["node"] == node]["feature"].tolist()[0]
        if pd.isnull(feat):
            features.append(-2)
        else:
            if feature_names is not None:
                feat = feature_names.index(feat)
            features.append(feat)

    children_default = children_right
    return {
        "trees": [
            {
                "children_left": np.array(children_left),
                "children_right": np.array(children_right),
                "children_default": np.array(children_default),
                "features": np.array(features),
                "thresholds": np.array(thresholds),
                "values": np.array(values).reshape(-1, 1),
                "node_sample_weight": np.array(node_sample_weight),
            }
        ]
    }


mod_dict = to_array_dict(mod_df, feature_names=list(X.columns))

# this should work...
explainer = shap.TreeExplainer(mod_dict)

sk_model = sklearn.tree.DecisionTreeRegressor(max_depth=2)
sk_model.fit(X.values, Y)

# this becomes pretty close.
print("hoeffding tree", np.mean(np.abs(explainer.model.predict(X) - Y)))
print("sklearn decision tree", np.mean(np.abs(sk_model.predict(X) - Y)))
```

**Comment by nlittlepoole** [comment]
Could this be used to load a model into Sklearn directly?

**Comment by chappers** [comment]
@nlittlepoole I'm not aware of a way to manually update decision trees using their array format unfortunately.

**Comment by MaxHalford** [comment]
Closing this because it seems the initial question has been answered. Feel free to open a discussion/issue if there's anything further to discuss.
