### ISSUE TITLE
Support mini-batches with the naive_bayes.GaussianNB model.

### ISSUE THREAD

**Issue by raphaelsty** [online-ml/river#460]
As part of issue #398 and PR #424, I updated the models `naive_bayes.ComplementNB`, `naive_bayes.MultinomialNB`, `naive_bayes.BernoulliNB` to support mini-batch (updates and predictions).

I have not updated GaussianNB which requires more work and some statistics to be computed in mini-batch like variance.

So this issue is dedicated to provide `learn_many`, `predict_many`, `predict_proba_many` class methods to GaussianNB. 

I'd like to take care of this issue very soon. (In the next 2 weeks)

Raphaël

**Comment by MaxHalford** [comment]
Closing this and adding a care [here](https://www.notion.so/Support-mini-batch-updates-in-GaussianNB-946801cde1c24221bbdf3c3fa949084c).
