### ISSUE TITLE
Math Range Error in do_naive_bayes_prediction

### ISSUE THREAD

**Issue by sbuschjaeger** [online-ml/river#475]
Hi,

there seems to be a bug in `do_naive_bayes_prediction` which can cause a math range error. I get the following output when training a `HoeffdingTreeClassifier` (but I suspect, that this also affects other classifiers, e.g. `ExtremelyFastDecisionTreeClassifier`): 

```./minimal_example.py 
Loading data
labels:  {0, 1, 2, 3, 4, 5}
data:  (13910, 128)
[9604/13910] accuracy 78.4569:  69%|██████████████████▋        | 9604/13910 [01:36<00:43, 99.06it/s]
Traceback (most recent call last):
  File "./minimal_example.py", line 43, in <module>
    pred = model.predict_one(xdict)
  File "~/anaconda3/envs/test-env/lib/python3.7/site-packages/river/base/classifier.py", line 69, in predict_one
    y_pred = self.predict_proba_one(x)
  File "~/anaconda3/envs/test-env/lib/python3.7/site-packages/river/tree/hoeffding_tree_classifier.py", line 434, in predict_proba_one
    proba.update(node.leaf_prediction(x, tree=self))
  File "~/anaconda3/envs/test-env/lib/python3.7/site-packages/river/tree/_nodes/htc_nodes.py", line 202, in leaf_prediction
    return do_naive_bayes_prediction(x, self.stats, self.attribute_observers)
  File "~/anaconda3/envs/test-env/lib/python3.7/site-packages/river/tree/_tree_utils.py", line 48, in do_naive_bayes_prediction
    votes[class_index] = math.exp(votes[class_index])
OverflowError: math range error
```

Interestringly, my code works fine if I do not normalize the input examples. Then I get the following output (but with worse accuracy)
```
Loading data
labels:  {0, 1, 2, 3, 4, 5}
data:  (13910, 128)
[13910/13910] accuracy 59.8778: 100%|████████████████████████| 13910/13910 [02:00<00:00, 115.44it/s
```

I used the following script to generate both outputs: 
```Python
#!/usr/bin/env python3

import sys
from tqdm import tqdm
import os
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

import river

print("Loading data")
dfs = []
for i in range(1,11):
    dfs.append( pd.read_csv(os.path.join("Dataset", "batch{}.dat".format(i)), header=None, delimiter = " ") )
df = pd.concat(dfs, axis=0, ignore_index=True)

# map classes to {0,1,2,3,4,5}
Y = df[0].values.astype(np.int32) - 1
df = df.drop([0], axis=1)

normalize = True # Results in error
if normalize:
    scaler = MinMaxScaler()
    X = scaler.fit_transform(df.values.astype(np.float64))
else:
    X = df.values.astype(np.float64)
print("labels: ", set(Y))
print("data: ", X.shape)

model = river.tree.HoeffdingTreeClassifier(
    grace_period = 50,
    split_confidence = 0.01,
    leaf_prediction = "nba"
)

accuracy = 0
cnt = 0

with tqdm(total=len(X), ncols=100) as pbar:
    for x,y in zip(X,Y):
        xdict = {}
        for j, xj in enumerate(x):
            xdict["att_" + str(j)] = xj

        pred = model.predict_one(xdict)
        model.learn_one(xdict,y)
        accuracy += (pred == y)
        cnt += 1
        pbar.update(1)
        desc = '[{}/{}] accuracy {:2.4f}'.format(cnt, len(X), 100.0 * accuracy / cnt )
        pbar.set_description(desc)
```

So far this bug only occurred on the gas-sensor (https://archive.ics.uci.edu/ml/datasets/Gas+Sensor+Array+Drift+Dataset) dataset. The dataset itself is not that big. You can download the data via this bash script and bring it into the correct format:
```bash
#/bin/bash

wget https://archive.ics.uci.edu/ml/machine-learning-databases/00224/Dataset.zip
unzip Dataset.zip
sed -i 's/[0-9]*\://'g Dataset/batch1.dat
sed -i 's/[0-9]*\://'g Dataset/batch2.dat
sed -i 's/[0-9]*\://'g Dataset/batch3.dat
sed -i 's/[0-9]*\://'g Dataset/batch4.dat
sed -i 's/[0-9]*\://'g Dataset/batch5.dat
sed -i 's/[0-9]*\://'g Dataset/batch6.dat
sed -i 's/[0-9]*\://'g Dataset/batch7.dat
sed -i 's/[0-9]*\://'g Dataset/batch8.dat
sed -i 's/[0-9]*\://'g Dataset/batch9.dat
sed -i 's/[0-9]*\://'g Dataset/batch10.dat
```
`conda list` gives me to following output (truncated to relevant packages)
```
conda list
# Name                    Version                   Build  Channel
river                     0.1.0                    pypi_0    pypi
python                    3.7.8           hffdb5ce_3_cpython    conda-forge
scikit-learn              0.23.2           py37hddcf8d6_3    conda-forge
tqdm                      4.54.1                   pypi_0    pypi
numpy                     1.19.4           py37h7e9df27_1    conda-forge
```

**Comment by MaxHalford** [comment]
Thanks for opening the issue. I've assigned this to @smastelini :)

**Comment by smastelini** [comment]
Hi @sbuchjaeger. Thanks for reporting that. I downloaded the dataset and your script.

I ran your code using the latest versions of scikit-learn and numpy, under Python 3.8 and a Linux system. That's what I got (when `normalize=True`):

![image](https://user-images.githubusercontent.com/9000157/108203086-c856c300-7100-11eb-943c-ad0cc656938d.png)

Now, switching off the Mix-Max normalization:

![image](https://user-images.githubusercontent.com/9000157/108204127-26d07100-7102-11eb-846e-12ad453fd18a.png)


As far as I am concerned, the error might be related to numerical precision issues rather than third-party packages.

I'll now switch to a local Python 3.7 environment and use the same version of the packages you previously listed.

Recently, we upgraded the way naive bayes is computed in the tree leaves, precisely to avoid underflow/overflow errors. Are you using the latest version of river?

**Comment by sbuschjaeger** [comment]
Hi, @smastelini. Thanks for the quick reply. 
I can confirm that the combination of python 3.8 + river from the git repo works fine. Technically, I have (and had) river `0.1` installed. Previously I installed it via pip (`pip install river`), but that installation could have been dated by now (the conda environment is a few month old by now). The new version seems to be fine, although there are no pip wheels for python 3.8 available? 
```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement river
ERROR: No matching distribution found for river
```
Installation via `pip install git+https://github.com/online-ml/river --upgrade` worked without a problem. 
In any case, thanks for the quick reply. I will stick to this combination now.

**Comment by smastelini** [comment]
I could not reproduce your error while using the latest river version and Python 3.7 (I also manually installed the same versions you've reported of numpy and sklearn in my local virtual environment).

That's what I got when normalization is active:

![image](https://user-images.githubusercontent.com/9000157/108213335-aa438f80-710d-11eb-9403-da433d45b805.png)

Without normalization:

![image](https://user-images.githubusercontent.com/9000157/108213398-bd565f80-710d-11eb-9437-03bcbb890e63.png)

Note that the normalization-based results slightly differ between the different Python versions. My guess? Plenty of small valued numbers being manipulated. In the long run, the precision ends up differing between the two Python versions.

I also tried using `StandardScaler` instead. Python 3.7:

![image](https://user-images.githubusercontent.com/9000157/108215025-9bf67300-710f-11eb-91d6-5304f54cbe66.png)

Python 3.8:

![image](https://user-images.githubusercontent.com/9000157/108218774-c1857b80-7113-11eb-9c8d-a50b4a4a6678.png)

The results are consistent! :D

**Comment by MaxHalford** [comment]
> pip install river

@sbuschjaeger that won't install what you expect. We're currently in the process of acquiring the name on PyPI. `pip install git+https://github.com/online-ml/river --upgrade` is currently the correct (and only) way to download "River".

**Comment by sbuschjaeger** [comment]
Hm that is strange that you cannot reproduce this error. However, since its now also working for me, I dont really mind :D Thanks for the quick reply!

**Comment by jacobmontiel** [comment]
> Hm that is strange that you cannot reproduce this error. 

For clarification, we improved the robustness of the NB prediction code in recent updates. This seems to explain why we can not reproduce the error in the latest dev version ;-)
