### ISSUE TITLE
Math doesn't render nicely on the docs. 

### ISSUE THREAD

**Issue by koaning** [online-ml/river#485]
Here's a screenshot from [this url](https://riverml.xyz/latest/api/facto/FFMClassifier/). 

![image](https://user-images.githubusercontent.com/1019791/109148254-4bfa5a80-7766-11eb-9369-47573c78d4e0.png)

**Comment by raphaelsty** [comment]
Hello,

When you click directly on the url that @koaning provided, math render nicely.

Safari:

![image](https://user-images.githubusercontent.com/24591024/109148716-e8246180-7766-11eb-84c8-e6fe6e6aa976.png)

Chrome:

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/24591024/109148652-d3e06480-7766-11eb-8f02-c545abb56fa4.png">

When I get on another model description such as FFMRegressor using API reference, the math does not render nicely. 

![image](https://user-images.githubusercontent.com/24591024/109149022-4f421600-7767-11eb-9b7f-c4b7de80ae31.png)
Safari
![image](https://user-images.githubusercontent.com/24591024/109149547-00e14700-7768-11eb-9e04-b8f58cfaa4bb.png)

Chrome
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/24591024/109149126-700a6b80-7767-11eb-899c-42c0801f2d65.png">

After refreshing the page, the math render nicely. To me, There is a problem using API reference links. It do not render the maths correctly. After refreshing the page it's ok.

**Comment by koaning** [comment]
I can confirm that after I hit reload it seems fixed. Maybe it's a caching thing on a mkdocs-material plugin?
