### ISSUE TITLE
about online-learning subject

### ISSUE THREAD

**Issue by 645187919** [online-ml/river#491]
hi，i'm doing a online learning test with your lib  ,but what I found missing was an introduction to online learning algorithms。I mean similar to FTRL, OGD and other algorithms in the field of online learning.If so, can you do a special topic or presentation on the use of incremental learning algorithms within RIVER?

**Comment by gbolmier** [comment]
Hi there, did you have a look at the `README.md` [philosophy](https://github.com/online-ml/river#-philosophy) and [media](https://github.com/online-ml/river#%EF%B8%8F-media) sections? The latter includes slides and talks about online learning and the library. With the [documentation](https://riverml.xyz/latest/) content, they provide both a high-level view of how online learning works as well as some focus on specific algorithms.

**Comment by 645187919** [comment]
Sorry, I made a mistake. I looked at your API documentation and found that you classified algorithms in detail according to their functions.I'm sorry. Thank you for the work you've done!
