### ISSUE TITLE
predict_one has side effects

### ISSUE THREAD

**Issue by Styren** [online-ml/river#499]
## Versions

**river version**: master branch
**Python version**: 3.9
**Operating system**: osx

## Describe the bug

`predict_one` causes the weights to change and yields a different result. When we tried to do time series forecasting and predicting a value in the future we noticed that the weights we got was different - and it failed to learn even when both features and labels consistently increased.
Am I misunderstanding something here?
## Steps/code to reproduce

```python
  from river import linear_model, metrics, preprocessing, compose

  dataset = [(dict(val=5*x), x) for x in range(10)]

  model = compose.Pipeline(
      ('scale', preprocessing.StandardScaler()),
      ('lin_reg', linear_model.LinearRegression())
  )
  metric = metrics.MSE()

  for x, y in dataset:
      y_pred = model.predict_one(x)
      model.learn_one(x, y)
      metric.update(y, y_pred)
      print(metric)

  model_pred_future = compose.Pipeline(
      ('scale', preprocessing.StandardScaler()),
      ('lin_reg', linear_model.LinearRegression())
  )
  metric_pred_future = metrics.MSE()


  for x, y in dataset:
      y_pred = model_pred_future.predict_one(x)
      model_pred_future.learn_one(x, y)
      metric_pred_future.update(y, y_pred)

      y_pred = model_pred_future.predict_one(dict(val=200000))
      print(metric_pred_future)
      print(f"y_pred_future: {y_pred}")
```
Output:
```
MSE: 0.
MSE: 0.5
MSE: 1.608
MSE: 3.23633
MSE: 5.297142
MSE: 7.709677
MSE: 10.402261
MSE: 13.312451
MSE: 16.386476
MSE: 19.578424
MSE: 0.
y_pred_future: 0.0
MSE: 0.5
y_pred_future: 0.005858394718508348
MSE: 1.624937
y_pred_future: 0.01308476518140858
MSE: 3.322002
y_pred_future: 0.02086116442166372
MSE: 5.539981
y_pred_future: 0.028884526973104035
MSE: 8.230667
y_pred_future: 0.037010755533317063
MSE: 11.349102
y_pred_future: 0.0451613383229445
MSE: 14.853522
y_pred_future: 0.053289764175274146
MSE: 18.705213
y_pred_future: 0.06136696916931006
MSE: 22.868334
y_pred_future: 0.06937418419188068
```

**Comment by MaxHalford** [comment]
Actually what's happening is that the unsupervised parts of the pipeline (in this `StandardScaler`) get updated when `predict_one` is called and not when `learn_one` is called. It's not a bug, it's a feature. Tell me if this isn't clear.

I am more and more convinced that we could/should add a `no_learn` parameter to `Pipeline.predict_one` to prevent the `StandardScaler` from updating itself. What do you think?

**Comment by Styren** [comment]
In my mind a `no_learn` sounds the best as in our case we want live feedback on the prediction of a future value. We almost excluded this could have anything to do with `predict_one` until we had looked at almost every other potential issue, so I would say that to us this wasn't immediately clear.
Would this mean simply not invoking the `learn_one` transformer methods in `Pipeline#_transform_one` with said argument? If that's so I can send a PR.

**Comment by MaxHalford** [comment]
> Would this mean simply not invoking the learn_one/learn_many transformer methods in Pipeline#_transform_one/transform_many with said argument?

Yes, exactly!

> If that's so I can send a PR.

That would be wonderful.

> Also, just out of curiosity, is there some documentation available on the purpose of updating the unsupervised parts during prediction?

It's actually in the docstring of the pipeline, see [here](https://github.com/online-ml/river/blob/master/river/compose/pipeline.py#L26). It is a delicate point and we should definitely discuss elsewhere. We need to get better at writing documentation as a general rule; I just have very little time to spare with my job at the moment.
