### ISSUE TITLE
Install instructions (v0.1.0) on the website documentation don't work

### ISSUE THREAD

**Issue by benwhale** [online-ml/river#500]
## Versions

**Python version**: 3.7.7
**Operating system**: Ubuntu

## Describe the bug

The install instructions on the website at [https://riverml.xyz/latest/getting-started/installation/](url) start by pointing to a v0.1.0 tag. Running this command does not work.

I notice looking at github that this doesn't match with the tag naming convention, so wonder if it's out of date from before the name migration and could do with a tweak? It could perhaps point to the github tags list until the river name is availiable on pypi?

It may also be worth updating the readme, as pip install river doesn't work at the moment to lead with workaround? When I first tried to get started with river I think I tried three different install commands before landing on a correct one. :smile: 

## Steps/code to reproduce

```
pip install git+git://github.com/online-ml/river.git@v0.1.0

Collecting git+git://github.com/online-ml/river.git@v0.1.0
  Cloning git://github.com/online-ml/river.git (to revision v0.1.0) to /tmp/pip-req-build-14mau16n
  Running command git clone -q git://github.com/online-ml/river.git /tmp/pip-req-build-14mau16n
  WARNING: Did not find branch or tag 'v0.1.0', assuming revision or ref.
  Running command git checkout -q v0.1.0
  error: pathspec 'v0.1.0' did not match any file(s) known to git
ERROR: Command errored out with exit status 1: git checkout -q v0.1.0 Check the logs for full command output.
```

**Comment by MaxHalford** [comment]
You're right we should remove the tag, I'll do it! The instructions that are in the README should be correct.

I can't wait till we acquire the River name...

**Comment by raphaelsty** [comment]
Hi @benwhale,

Just a ping to say that installing river using pip is available.

```sh
pip install river
```

The latest version is 0.7.0 🙂
