### ISSUE TITLE
example ipynb file reading error

### ISSUE THREAD

**Issue by adills** [online-ml/river#536]
## searched prior issues
I searched all open issues on "ipynb" and did not see any issues.  Hopefully this is not an environment issue on my part, but if it is sorry to add an issue.

## Versions
**river version**: 0.1.0
**Python version**: 3.9.2
**Operating system**: MacOS 10.15.7

## Describe the bug
Attempted to open every ipynb example in docs/examples within a Jupyter Notebook that was launched within a pipenv containing river.  Received this pop-up from Jupyter.
> Unreadable Notebook: /Users/<myusername>/Documents/pyprojects/river_demo/examples/sentence_classification.ipynb NotJSONError('Notebook does not appear to be JSON: \'<!DOCTYPE html>\\n<html lang="en" data-c...')

## Steps/code to reproduce
```
cd river_demo
pipenv shell
jupyter notebook
```
From Chrome tab that Jupyter opened in, navigated to my copy of the examples and clicked on the example sentence_classification.ipynb file.

**Comment by raphaelsty** [comment]
@adills Thank you for the issue, I made this Notebook two weeks ago, it seems that I made a mistake, look forward into it. 

If you want to read the notebook, you can follow this [link](https://riverml.xyz/dev/examples/sentence_classification/) to the documentation.

**Comment by adills** [comment]
@raphaelsty Perfect!  Thank you.  I was able to run the code in your examples by copying into my own environment.   I just did it quick and dirty in a py script instead of a notebook.  Thanks again for your help.  I'm good to close this issue unless you want to keep it open to remind yourself to update the ipynb examples.

**Comment by raphaelsty** [comment]
@adills, I'd like to keep it as a remainder, I'll close it once I'll repair my mistake. 

Thank you.
