### ISSUE TITLE
CAN not install

### ISSUE THREAD

**Issue by byfsdhr** [online-ml/river#540]
CAN not install from this page:
https://riverml.xyz/dev/getting-started/installation/

PS C:\Windows\system32> pip install git+git://github.com/online-ml/river.git@v0.1.0
Collecting git+git://github.com/online-ml/river.git@v0.1.0
  Cloning git://github.com/online-ml/river.git (to revision v0.1.0) to c:\users\supernova\appdata\local\temp\pip-req-build-kho7d80k
  Running command git clone -q git://github.com/online-ml/river.git 'C:\Users\supernova\AppData\Local\Temp\pip-req-build-kho7d80k'
  WARNING: Did not find branch or tag 'v0.1.0', assuming revision or ref.
  Running command git checkout -q v0.1.0
  error: pathspec 'v0.1.0' did not match any file(s) known to git
WARNING: Discarding git+git://github.com/online-ml/river.git@v0.1.0. Command errored out with exit status 1: git checkout -q v0.1.0 Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q v0.1.0 Check the logs for full command output.

**Comment by byfsdhr** [comment]
This code also can install
PS C:\Windows\system32> pip install git+git://github.com/online-ml/river.git@0.6.1
Collecting git+git://github.com/online-ml/river.git@0.6.1
  Cloning git://github.com/online-ml/river.git (to revision 0.6.1) to c:\users\supernova\appdata\local\temp\pip-req-build-xu3bi5bq
  Running command git clone -q git://github.com/online-ml/river.git 'C:\Users\supernova\AppData\Local\Temp\pip-req-build-xu3bi5bq'
  Running command git checkout -q 3aad237f271fe3c27626d9ffd9c608a6503ef6ea
Collecting mmh3==2.5.1
  Downloading mmh3-2.5.1.tar.gz (9.8 kB)
Requirement already satisfied: numpy>=1.18.1 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from creme==0.6.1) (1.20.1)
Requirement already satisfied: scipy>=1.4.1 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from creme==0.6.1) (1.6.1)
Requirement already satisfied: pandas>=1.0.1 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from creme==0.6.1) (1.2.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\supernova\appdata\roaming\python\python39\site-packages (from pandas>=1.0.1->creme==0.6.1) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.0.1->creme==0.6.1) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\supernova\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.7.3->pandas>=1.0.1->creme==0.6.1) (1.15.0)
Building wheels for collected packages: creme, mmh3
  Building wheel for creme (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\supernova\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-req-build-xu3bi5bq\\setup.py'"'"'; __file__='"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-req-build-xu3bi5bq\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\supernova\AppData\Local\Temp\pip-wheel-gdaxtdwl'
       cwd: C:\Users\supernova\AppData\Local\Temp\pip-req-build-xu3bi5bq\
  Complete output (300 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\creme
  copying creme\conftest.py -> build\lib.win-amd64-3.9\creme
  copying creme\dummy.py -> build\lib.win-amd64-3.9\creme
  copying creme\test_.py -> build\lib.win-amd64-3.9\creme
  copying creme\__init__.py -> build\lib.win-amd64-3.9\creme
  copying creme\__version__.py -> build\lib.win-amd64-3.9\creme
  creating build\lib.win-amd64-3.9\creme\anomaly
  copying creme\anomaly\hst.py -> build\lib.win-amd64-3.9\creme\anomaly
  copying creme\anomaly\__init__.py -> build\lib.win-amd64-3.9\creme\anomaly
  creating build\lib.win-amd64-3.9\creme\base
  copying creme\base\anomaly.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\classifier.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\clusterer.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\ensemble.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\estimator.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\multi_output.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\predictor.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\regressor.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\test_base.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\transformer.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\typing.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\wrapper.py -> build\lib.win-amd64-3.9\creme\base
  copying creme\base\__init__.py -> build\lib.win-amd64-3.9\creme\base
  creating build\lib.win-amd64-3.9\creme\cluster
  copying creme\cluster\k_means.py -> build\lib.win-amd64-3.9\creme\cluster
  copying creme\cluster\__init__.py -> build\lib.win-amd64-3.9\creme\cluster
  creating build\lib.win-amd64-3.9\creme\compat
  copying creme\compat\pytorch.py -> build\lib.win-amd64-3.9\creme\compat
  copying creme\compat\sklearn.py -> build\lib.win-amd64-3.9\creme\compat
  copying creme\compat\test_sklearn.py -> build\lib.win-amd64-3.9\creme\compat
  copying creme\compat\__init__.py -> build\lib.win-amd64-3.9\creme\compat
  creating build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\func.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\grouper.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\pipeline.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\rename.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\select.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\test_.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\union.py -> build\lib.win-amd64-3.9\creme\compose
  copying creme\compose\__init__.py -> build\lib.win-amd64-3.9\creme\compose
  creating build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\airline_passengers.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\bananas.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\base.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\bikes.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\chick_weights.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\credit_card.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\elec2.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\higgs.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\http.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\insects.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\malicious_url.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\movielens100k.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\music.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\phishing.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\restaurants.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\segment.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\sms_spam.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\smtp.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\taxis.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\test_datasets.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\trec07.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\trump_approval.py -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\__init__.py -> build\lib.win-amd64-3.9\creme\datasets
  creating build\lib.win-amd64-3.9\creme\decomposition
  copying creme\decomposition\lda.py -> build\lib.win-amd64-3.9\creme\decomposition
  copying creme\decomposition\test_.py -> build\lib.win-amd64-3.9\creme\decomposition
  copying creme\decomposition\__init__.py -> build\lib.win-amd64-3.9\creme\decomposition
  creating build\lib.win-amd64-3.9\creme\ensemble
  copying creme\ensemble\bagging.py -> build\lib.win-amd64-3.9\creme\ensemble
  copying creme\ensemble\boosting.py -> build\lib.win-amd64-3.9\creme\ensemble
  copying creme\ensemble\hedging.py -> build\lib.win-amd64-3.9\creme\ensemble
  copying creme\ensemble\stacking.py -> build\lib.win-amd64-3.9\creme\ensemble
  copying creme\ensemble\__init__.py -> build\lib.win-amd64-3.9\creme\ensemble
  creating build\lib.win-amd64-3.9\creme\facto
  copying creme\facto\base.py -> build\lib.win-amd64-3.9\creme\facto
  copying creme\facto\ffm.py -> build\lib.win-amd64-3.9\creme\facto
  copying creme\facto\fm.py -> build\lib.win-amd64-3.9\creme\facto
  copying creme\facto\fwfm.py -> build\lib.win-amd64-3.9\creme\facto
  copying creme\facto\hofm.py -> build\lib.win-amd64-3.9\creme\facto
  copying creme\facto\__init__.py -> build\lib.win-amd64-3.9\creme\facto
  creating build\lib.win-amd64-3.9\creme\feature_extraction
  copying creme\feature_extraction\agg.py -> build\lib.win-amd64-3.9\creme\feature_extraction
  copying creme\feature_extraction\vectorize.py -> build\lib.win-amd64-3.9\creme\feature_extraction
  copying creme\feature_extraction\__init__.py -> build\lib.win-amd64-3.9\creme\feature_extraction
  creating build\lib.win-amd64-3.9\creme\feature_selection
  copying creme\feature_selection\k_best.py -> build\lib.win-amd64-3.9\creme\feature_selection
  copying creme\feature_selection\random.py -> build\lib.win-amd64-3.9\creme\feature_selection
  copying creme\feature_selection\variance.py -> build\lib.win-amd64-3.9\creme\feature_selection
  copying creme\feature_selection\__init__.py -> build\lib.win-amd64-3.9\creme\feature_selection
  creating build\lib.win-amd64-3.9\creme\impute
  copying creme\impute\previous.py -> build\lib.win-amd64-3.9\creme\impute
  copying creme\impute\stat.py -> build\lib.win-amd64-3.9\creme\impute
  copying creme\impute\__init__.py -> build\lib.win-amd64-3.9\creme\impute
  creating build\lib.win-amd64-3.9\creme\linear_model
  copying creme\linear_model\alma.py -> build\lib.win-amd64-3.9\creme\linear_model
  copying creme\linear_model\glm.py -> build\lib.win-amd64-3.9\creme\linear_model
  copying creme\linear_model\pa.py -> build\lib.win-amd64-3.9\creme\linear_model
  copying creme\linear_model\softmax.py -> build\lib.win-amd64-3.9\creme\linear_model
  copying creme\linear_model\test_glm.py -> build\lib.win-amd64-3.9\creme\linear_model
  copying creme\linear_model\__init__.py -> build\lib.win-amd64-3.9\creme\linear_model
  creating build\lib.win-amd64-3.9\creme\meta
  copying creme\meta\pred_clipper.py -> build\lib.win-amd64-3.9\creme\meta
  copying creme\meta\target_transform.py -> build\lib.win-amd64-3.9\creme\meta
  copying creme\meta\__init__.py -> build\lib.win-amd64-3.9\creme\meta
  creating build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\accuracy.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\base.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\confusion.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\cross_entropy.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\fbeta.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\jaccard.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\log_loss.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\mae.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\mcc.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\mse.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\multioutput.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\precision.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\recall.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\report.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\rmse.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\rmsle.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\roc_auc.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\rolling.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\smape.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\test_.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\time_rolling.py -> build\lib.win-amd64-3.9\creme\metrics
  copying creme\metrics\__init__.py -> build\lib.win-amd64-3.9\creme\metrics
  creating build\lib.win-amd64-3.9\creme\model_selection
  copying creme\model_selection\grid.py -> build\lib.win-amd64-3.9\creme\model_selection
  copying creme\model_selection\score.py -> build\lib.win-amd64-3.9\creme\model_selection
  copying creme\model_selection\sh.py -> build\lib.win-amd64-3.9\creme\model_selection
  copying creme\model_selection\test_grid.py -> build\lib.win-amd64-3.9\creme\model_selection
  copying creme\model_selection\__init__.py -> build\lib.win-amd64-3.9\creme\model_selection
  creating build\lib.win-amd64-3.9\creme\multiclass
  copying creme\multiclass\ooc.py -> build\lib.win-amd64-3.9\creme\multiclass
  copying creme\multiclass\ovo.py -> build\lib.win-amd64-3.9\creme\multiclass
  copying creme\multiclass\ovr.py -> build\lib.win-amd64-3.9\creme\multiclass
  copying creme\multiclass\__init__.py -> build\lib.win-amd64-3.9\creme\multiclass
  creating build\lib.win-amd64-3.9\creme\multioutput
  copying creme\multioutput\chain.py -> build\lib.win-amd64-3.9\creme\multioutput
  copying creme\multioutput\__init__.py -> build\lib.win-amd64-3.9\creme\multioutput
  creating build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\base.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\bernoulli.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\complement.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\gaussian.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\multinomial.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\test_multinomial.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  copying creme\naive_bayes\__init__.py -> build\lib.win-amd64-3.9\creme\naive_bayes
  creating build\lib.win-amd64-3.9\creme\neighbors
  copying creme\neighbors\knn.py -> build\lib.win-amd64-3.9\creme\neighbors
  copying creme\neighbors\test_knn.py -> build\lib.win-amd64-3.9\creme\neighbors
  copying creme\neighbors\__init__.py -> build\lib.win-amd64-3.9\creme\neighbors
  creating build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\adam.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\ada_bound.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\ada_delta.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\ada_grad.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\ada_max.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\ams_grad.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\base.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\ftrl.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\initializers.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\losses.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\mini_batch.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\momentum.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\nadam.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\nesterov.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\newton.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\rms_prop.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\schedulers.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\sgd.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\test_losses.py -> build\lib.win-amd64-3.9\creme\optim
  copying creme\optim\__init__.py -> build\lib.win-amd64-3.9\creme\optim
  creating build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\feature_hasher.py -> build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\kernel_approx.py -> build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\one_hot.py -> build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\poly.py -> build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\scale.py -> build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\test_scale.py -> build\lib.win-amd64-3.9\creme\preprocessing
  copying creme\preprocessing\__init__.py -> build\lib.win-amd64-3.9\creme\preprocessing
  creating build\lib.win-amd64-3.9\creme\proba
  copying creme\proba\base.py -> build\lib.win-amd64-3.9\creme\proba
  copying creme\proba\gaussian.py -> build\lib.win-amd64-3.9\creme\proba
  copying creme\proba\multinomial.py -> build\lib.win-amd64-3.9\creme\proba
  copying creme\proba\__init__.py -> build\lib.win-amd64-3.9\creme\proba
  creating build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\base.py -> build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\baseline.py -> build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\biased_mf.py -> build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\funk_mf.py -> build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\normal.py -> build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\surprise.py -> build\lib.win-amd64-3.9\creme\reco
  copying creme\reco\__init__.py -> build\lib.win-amd64-3.9\creme\reco
  creating build\lib.win-amd64-3.9\creme\sampling
  copying creme\sampling\hard_sampling.py -> build\lib.win-amd64-3.9\creme\sampling
  copying creme\sampling\random.py -> build\lib.win-amd64-3.9\creme\sampling
  copying creme\sampling\__init__.py -> build\lib.win-amd64-3.9\creme\sampling
  creating build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\auto_corr.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\count.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\cov.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\entropy.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\ewmean.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\ewvar.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\iqr.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\kurtosis.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\link.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\maximum.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\minimum.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\mode.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\moments.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\n_unique.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\pearson.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\ptp.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\quantile.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\sem.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\shift.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\skew.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\summing.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\test_.py -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\__init__.py -> build\lib.win-amd64-3.9\creme\stats
  creating build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\cache.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_arff.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_array.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_csv.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_libsvm.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_pandas.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_sklearn.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_sql.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\iter_vaex.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\qa.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\shuffling.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\test_sql.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\utils.py -> build\lib.win-amd64-3.9\creme\stream
  copying creme\stream\__init__.py -> build\lib.win-amd64-3.9\creme\stream
  creating build\lib.win-amd64-3.9\creme\time_series
  copying creme\time_series\base.py -> build\lib.win-amd64-3.9\creme\time_series
  copying creme\time_series\detrender.py -> build\lib.win-amd64-3.9\creme\time_series
  copying creme\time_series\snarimax.py -> build\lib.win-amd64-3.9\creme\time_series
  copying creme\time_series\__init__.py -> build\lib.win-amd64-3.9\creme\time_series
  creating build\lib.win-amd64-3.9\creme\tree
  copying creme\tree\base.py -> build\lib.win-amd64-3.9\creme\tree
  copying creme\tree\__init__.py -> build\lib.win-amd64-3.9\creme\tree
  creating build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\estimator_checks.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\histogram.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\math.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\pretty.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\sdft.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\skyline.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\window.py -> build\lib.win-amd64-3.9\creme\utils
  copying creme\utils\__init__.py -> build\lib.win-amd64-3.9\creme\utils
  creating build\lib.win-amd64-3.9\creme\datasets\synth
  copying creme\datasets\synth\friedman.py -> build\lib.win-amd64-3.9\creme\datasets\synth
  copying creme\datasets\synth\sea.py -> build\lib.win-amd64-3.9\creme\datasets\synth
  copying creme\datasets\synth\__init__.py -> build\lib.win-amd64-3.9\creme\datasets\synth
  creating build\lib.win-amd64-3.9\creme\tree\decision
  copying creme\tree\decision\criteria.py -> build\lib.win-amd64-3.9\creme\tree\decision
  copying creme\tree\decision\forest.py -> build\lib.win-amd64-3.9\creme\tree\decision
  copying creme\tree\decision\node.py -> build\lib.win-amd64-3.9\creme\tree\decision
  copying creme\tree\decision\splitting.py -> build\lib.win-amd64-3.9\creme\tree\decision
  copying creme\tree\decision\tree.py -> build\lib.win-amd64-3.9\creme\tree\decision
  copying creme\tree\decision\__init__.py -> build\lib.win-amd64-3.9\creme\tree\decision
  running egg_info
  creating creme.egg-info
  writing creme.egg-info\PKG-INFO
  writing dependency_links to creme.egg-info\dependency_links.txt
  writing requirements to creme.egg-info\requires.txt
  writing top-level names to creme.egg-info\top_level.txt
  writing manifest file 'creme.egg-info\SOURCES.txt'
  reading manifest file 'creme.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'creme.egg-info\SOURCES.txt'
  copying creme\datasets\airline-passengers.csv -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\banana.zip -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\chick-weights.csv -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\phishing.csv.gz -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\segment.csv.zip -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\datasets\trump_approval.csv.gz -> build\lib.win-amd64-3.9\creme\datasets
  copying creme\stats\base.c -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\base.pxd -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\base.pyx -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\mean.c -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\mean.pxd -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\mean.pyx -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\var.c -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stats\var.pyx -> build\lib.win-amd64-3.9\creme\stats
  copying creme\stream\pokedb.zip -> build\lib.win-amd64-3.9\creme\stream
  running build_ext
  building 'creme.stats.base' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for creme
  Running setup.py clean for creme
  Building wheel for mmh3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\supernova\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-install-yzzzfz3a\\mmh3_0027cf9ea8ee490782c99df1c4c5b178\\setup.py'"'"'; __file__='"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-install-yzzzfz3a\\mmh3_0027cf9ea8ee490782c99df1c4c5b178\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\supernova\AppData\Local\Temp\pip-wheel-iio43jtx'
       cwd: C:\Users\supernova\AppData\Local\Temp\pip-install-yzzzfz3a\mmh3_0027cf9ea8ee490782c99df1c4c5b178\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for mmh3
Failed to build creme mmh3
Installing collected packages: mmh3, creme
    Running setup.py install for mmh3 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\supernova\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-install-yzzzfz3a\\mmh3_0027cf9ea8ee490782c99df1c4c5b178\\setup.py'"'"'; __file__='"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-install-yzzzfz3a\\mmh3_0027cf9ea8ee490782c99df1c4c5b178\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\supernova\AppData\Local\Temp\pip-record-mni2dnh3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\supernova\appdata\local\programs\python\python39\Include\mmh3'
         cwd: C:\Users\supernova\AppData\Local\Temp\pip-install-yzzzfz3a\mmh3_0027cf9ea8ee490782c99df1c4c5b178\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'mmh3' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\supernova\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-install-yzzzfz3a\\mmh3_0027cf9ea8ee490782c99df1c4c5b178\\setup.py'"'"'; __file__='"'"'C:\\Users\\supernova\\AppData\\Local\\Temp\\pip-install-yzzzfz3a\\mmh3_0027cf9ea8ee490782c99df1c4c5b178\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\supernova\AppData\Local\Temp\pip-record-mni2dnh3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\supernova\appdata\local\programs\python\python39\Include\mmh3' Check the logs for full command output.

**Comment by byfsdhr** [comment]
PS C:\Windows\system32> pip install river
ERROR: Could not find a version that satisfies the requirement river
ERROR: No matching distribution found for river

**Comment by TheRisenPhoenix** [comment]
Try this one:
`pip install git+https://github.com/online-ml/river`

As explained in #534 , the name river is not yet released. You need to install the latest development version (which is the second command given in the documentation)

**Comment by MaxHalford** [comment]
It's because you don't have the C++ build tools. See [this](https://github.com/online-ml/river/issues/381) thread.
