### ISSUE TITLE
Why I cant import river?

### ISSUE THREAD

**Issue by byfsdhr** [online-ml/river#551]
from river import datasets

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-e7bee93a8b38> in <module>
----> 1 from river import datasets

~\AppData\Local\Programs\Python\Python39\lib\site-packages\river\__init__.py in <module>
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,

~\AppData\Local\Programs\Python\Python39\lib\site-packages\river\time_series\__init__.py in <module>
      1 """Time series forecasting."""
      2 from .detrender import Detrender, GroupDetrender
----> 3 from .snarimax import SNARIMAX
      4 
      5 __all__ = ["Detrender", "GroupDetrender", "SNARIMAX"]

~\AppData\Local\Programs\Python\Python39\lib\site-packages\river\time_series\snarimax.py in <module>
    144 
    145 
--> 146 class SNARIMAX(base.Forecaster):
    147     """SNARIMAX model.
    148 

~\AppData\Local\Programs\Python\Python39\lib\site-packages\river\time_series\snarimax.py in SNARIMAX()
    303         sd: int = 0,
    304         sq: int = 0,
--> 305         regressor: river.base.Regressor = None,
    306     ):
    307 

AttributeError: partially initialized module 'river' has no attribute 'base' (most likely due to a circular import)

**Comment by byfsdhr** [comment]
$ pip install git+https://github.com/online-ml/river --upgrade
Collecting git+https://github.com/online-ml/river
  Cloning https://github.com/online-ml/river to c:\users\supernova\appdata\local\temp\pip-req-build-g8z3w7hs
  Running command git clone -q https://github.com/online-ml/river 'C:\Users\supernova\AppData\Local\Temp\pip-req-build-g8z3w7hs'
Requirement already satisfied: numpy>=1.18.1 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from river==0.1.0) (1.20.1)
Requirement already satisfied: scipy>=1.4.1 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from river==0.1.0) (1.6.1) 
Requirement already satisfied: pandas>=1.0.1 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from river==0.1.0) (1.2.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.0.1->river==0.1.0) 
(2.8.1)
**After success install river**
Requirement already satisfied: pytz>=2017.3 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from pandas>=1.0.1->river==0.1.0) (2021.1)  
Requirement already satisfied: six>=1.5 in c:\users\supernova\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.0.1->river==0.1.0) (1.15.0)
Building wheels for collected packages: river
  Building wheel for river (setup.py) ... done
  Created wheel for river: filename=river-0.1.0-cp39-cp39-win_amd64.whl size=1105462 sha256=c9fec021305d42032f77009bafd3f34d04742723406303d2ed614895c9a00655  
  Stored in directory: C:\Users\supernova\AppData\Local\Temp\pip-ephem-wheel-cache-radg8cgr\wheels\b9\fe\7b\d65def20df80352415e2f46330c399cee74853ff43f862b764
Successfully built river
Installing collected packages: river
Successfully installed river-0.1.0

**Comment by MaxHalford** [comment]
Sorry but you're going to have to give more context. There's no way we can reproduce your bug.

**Comment by byfsdhr** [comment]
Work now after rebot
