### ISSUE TITLE
Regarding Installing River package for online streaming data

### ISSUE THREAD

**Issue by msabdulrazak** [online-ml/river#559]
I am getting error like ERROR: Could not find a version that satisfies the requirement river (from versions: none)
ERROR: No matching distribution found for river . The python version i am using is 3.8.3

**Comment by MaxHalford** [comment]
Did you try running this command?

```sh
pip install git+https://github.com/online-ml/river --upgrade
```

**Comment by msabdulrazak** [comment]
ERROR: Cannot find command 'git' - do you have 'git' installed and in your
PATH?
This is the error i am getting
if i run the above command

Regards
Abdul Razak M S

**Comment by MaxHalford** [comment]
Well you'll have to install git. Is that a problem? What OS are you on?

We should soon be given access to the `river` name on PyPI, after which we'll be able to publish the package so that you can `pip install river`.

**Comment by msabdulrazak** [comment]
windows 10, 64 bit operating system
How to install git from anaconda console or in jupyter notebook

**Comment by MaxHalford** [comment]
I don't know, I've never done it for Windows. But you can prefix commands with `!` to run them in your terminal, so I'm sure you'll find a way.

**Comment by msabdulrazak** [comment]
I tried in Ubuntu it works well. Tq for the support
