### ISSUE TITLE
[BUG] setup.py installation issue with metadata

### ISSUE THREAD

**Issue by odmarkj** [online-ml/river#564]
**river version**: 0.6.1
**Python version**: 3.8.8
**Operating system**: MacOS Catalina 10.15.4

## Describe the bug
install_requires = ["river @ git+https://github.com/online-ml/river@0.6.1#egg=river"]

When installing via setup.py from another library, the following error occurs:

WARNING: Generating metadata for package river produced metadata for project name creme. Fix your #egg=river fragments.
WARNING: Discarding git+https://github.com/online-ml/river@0.6.1#egg=creme. Requested creme from git+https://github.com/online-ml/river@0.6.1#egg=creme (from XXXX) has inconsistent name: filename has 'river', but metadata has 'creme'

In order to get it to install correctly, the names have to be changed to creme.

install_requires = ["creme @ git+https://github.com/online-ml/river@0.6.1#egg=creme"]

## Steps/code to reproduce
python setup.py bdist_wheel

```python
import setuptools

setuptools.setup(
    name="testpackage",
    version="1.0.0",
    author="John Smith",
    packages=setuptools.find_packages(),
    install_requires = ["river @ git+https://github.com/online-ml/river@0.6.1#egg=river"]
)
```

**Comment by raphaelsty** [comment]
Hi @odmarkj,

I think you should change the version, replace 0.6.1 by 0.1.0.

```sh
import setuptools

setuptools.setup(
    name="testpackage",
    version="1.0.0",
    author="John Smith",
    packages=setuptools.find_packages(),
    install_requires = ["river @ git+https://github.com/online-ml/river@0.1.0#egg=river"]
)
```

Please let me know if works.

**Comment by odmarkj** [comment]
Same error.

Are you also saying that the currently tagged releases on this repository are invalid?

**Comment by raphaelsty** [comment]
I managed to reproduce the error, 

You can add the last version of river in your dependancy by removing the version for now. 

```python
import setuptools

setuptools.setup(
    name="testpackage",
    version="1.0.0",
    author="John Smith",
    packages=setuptools.find_packages(),
    install_requires = ["river @ git+https://github.com/online-ml/river#egg=river"]
)
```

There is a conflict between the previous repository project called creme and the new one river which result of a merge with scikit-multiflow.

**Comment by odmarkj** [comment]
Perfect, thank you, was able to get it installed.

Do you think this can be resolved soon? Really need to lock down a version before I can distributed this.

Thanks!

**Comment by raphaelsty** [comment]
We have some difficulties with the river name assignment via pypi [#651](https://github.com/pypa/pypi-support/issues/651). As soon as we have the pypi name available, all should be rolling but it is a bit slower than expected... We hope this will be resolved soon.

You're welcome @odmarkj 

I close the issue 😊

**Comment by raphaelsty** [comment]
Hi @odmarkj, 

Just a ping to say that river is available using pip.

```sh
pip install river
```
You can lock down the latest release which is version 0.0.7. 🙂
