### ISSUE TITLE
Error when loading csv with missing integer value

### ISSUE THREAD

**Issue by StijnKas** [online-ml/river#582]
## Versions

**river version**: Latest commit (11a1c0ec78cf6c8b69c22f75c6af50f576b7f875)
**Python version**: 3.6.12
**Operating system**: MacOS, in Docker Container

## Describe the bug

When importing a csv dataset with missing values in an integer column, an error is thrown because an empty string cannot be converted to integer: shown in the example below.

## Steps/code to reproduce

```python
import csv
from river import stream

example = [ ['col1', 'col2', 'col3'], 
         ['', 1, 2], 
         [5, '', 4], 
         [3, 1, '']]

with open('example.csv', 'w') as f:
    write = csv.writer(f)
    write.writerows(example)

params = {'converters': {'col1': int, 'col2': int, 'col3': int}}
dataset = stream.iter_csv("example.csv", **params)
for x in dataset:
    print(x)
```

```python
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    for x in dataset:
  File "/usr/local/lib/python3.6/site-packages/river/stream/iter_csv.py", line 155, in iter_csv
    x[i] = t(x[i])
ValueError: invalid literal for int() with base 10: ''
```

## Desired outcome
For my use case, it would be sufficient to only return a converted integer if the string is non-empty, thus the simple fix below solves my specific use case:

### Current implementation in iter_csv.py:
```python
if converters is not None:
    for i, t in converters.items():
        x[i] = t(x[i])
```

### Possible solution:
```python
if converters is not None:
    for i, t in converters.items():
        if x[i] != '':
            x[i] = t(x[I])
```

I'm not sure if this is the 'correct' way to solve the issue, since it doesn't neatly define the entire column as integer. Perhaps it could be added as a parameter/option?

**Comment by MaxHalford** [comment]
I think it would be nice to add the same support as pandas (see `na_values` and `na_filter` in [`pandas.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html))

**Comment by MaxHalford** [comment]
I added a `drop_nones` parameter to `iter_csv` to allow dropping `None` values. This means that you need to use an `int` converters that allows for missing values. Here's a unit test to show how this works:

```py
example = io.StringIO("col1,col2,col3\n,1,2\n5,,4\n3,1,")

def int_or_none(s):
    try:
        return int(s)
    except ValueError:
        return None

params = {
    "converters": {"col1": int_or_none, "col2": int_or_none, "col3": int_or_none},
    "drop_nones": True,
}

dataset = stream.iter_csv(example, **params)

assert list(dataset) == [
    ({"col2": 1, "col3": 2}, None),
    ({"col1": 5, "col3": 4}, None),
    ({"col1": 3, "col2": 1}, None),
]
```
