### ISSUE TITLE
0 regressor output when a new value of a feature appears

### ISSUE THREAD

**Issue by ayush488** [online-ml/river#585]
Can you explain why the regressor starts giving 0 or absurd values when one of the predictors get a new value.

**Comment by raphaelsty** [comment]
Hi, we can't help you solve your problem if you don't follow the template below.

## Versions


**`creme` version**: 

**Python version**:

## Describe your task


## What kind of performance are you expecting?


## Steps/code to reproduce



```python
# Sample code to reproduce the performance issue
```

## Necessary data

**Comment by ayush488** [comment]
Thanks @raphaelsty .
Versions
river version:0.7.0

Python version: 3.7

Describe your task

Regressor starts giving 0 or absurd values when one of the predictors get a new value. This happens for some initial time unless the regressor has received several values of the feature. 

What kind of performance are you expecting?
In general regression the expectation is that even if the model has not seen a new value of a feature but based on previous values it can extrapolate or estimate. So the output should not suddenly be zero. 

Steps/code to reproduce
test_data=pd.read_csv(test_dataset.csv)
model = (
  preprocessing.StandardScaler() | linear_model.PARegressor(
     C=0.01,
     mode=2,
     eps=0.1,
     learn_intercept=False
 ))
from pandas.tseries.holiday import USFederalHolidayCalendar
cal = USFederalHolidayCalendar()
holidays =cal.holidays(start='2020-01-01', end='2021-12-31').to_pydatetime()
metric = metrics.MAE() + metrics.MSE()
for index, row in test_data.iterrows():
    x={}
    max_data_date = row['report_date']
    max_data_date=pd.to_datetime(max_data_date)
    DoW=(max_data_date.dayofweek)
    for d in range(1,8):
        x['DoW_'+str(d)]=1 if (d-1)==DoW else 0
      
            
#    WoM=(pendulum.parse(row['report_date']).week_of_month)
#    for w in range(1,6):
#        x['WoM_'+str(w)]=1 if (w-1)==DoW else 0
    DoM=(max_data_date.day)
    for d in range(1,32):
        x['DoM_'+str(d)]=1 if (d)==DoM else 0
    MoY=(max_data_date.month)
    for m in range(1,13):
        x['MoY_'+str(m)]=1 if (m)==MoY else 0
    QoY=(max_data_date.quarter)
    for q in range(1,5):
        x['QoY_'+str(q)]=1 if (q)==QoY else 0    
    holyday=1 if max_data_date in holidays else 0
    group_budget=row['campaigngroupbudget']
    x['Holiday']=holyday
    x['budget']=group_budget
    x['est_clicks']=row['t_clicks']
    x['est_cost']=row['spend']
    x['est_sales']=row['est_sales']
    
    y=row['attributedsales1d']
    #pprint(x)
#    print(y)
    
    
   # model.partial_fit(x, y)
    #y_pred =model.predict(x)
    y_pred = model.predict_one(x)
#    
    y_pred=0 if y_pred<0 else y_pred
    model = model.learn_one(x, y)
    print(y,y_pred,group_budget)

    metric = metric.update(y, y_pred)
[test_dataset.csv](https://github.com/online-ml/river/files/6443632/test_dataset.csv)

**Comment by ayush488** [comment]
Thanks great.. Thanks. it worked. Is there a way in River to select the best Regressor and do parameter optimization.

**Comment by ayush488** [comment]
Kind of auto-ml

**Comment by raphaelsty** [comment]
Here is a sample of code to make a grid search on your data. River does not offer auto-ml but you may be interested in [EWARegressor](https://riverml.xyz/latest/api/expert/EWARegressor/) which will learn to select the right model. :)

```python
import itertools

import pandas as pd

from river import preprocessing
from river import linear_model
from river import metrics

test_data = pd.read_csv("test_dataset.csv")

grid = {
    "C": [0.001, 0.003, 0.005, 0.007, 0.009, 0.01],
    "mode": [1, 2],
    "eps": [0.001, 0.003, 0.005, 0.007, 0.009, 0.01],
    "learn_intercept": [False, True]
}

parameters, values = zip(*grid.items())
parameters = [dict(zip(parameters, v)) for v in itertools.product(*values)]

# parameters = [
# {'C': 0.001, 'mode': 1, 'eps': 0.001, 'learn_intercept': False},
# {'C': 0.001, 'mode': 1, 'eps': 0.001, 'learn_intercept': True},
# {'C': 0.001, 'mode': 1, 'eps': 0.003, 'learn_intercept': False},
# {'C': 0.001, 'mode': 1, 'eps': 0.003, 'learn_intercept': True},
# {'C': 0.001, 'mode': 1, 'eps': 0.005, 'learn_intercept': False},
# {...},
# ]

for p in parameters:
    
    model = (preprocessing.MinMaxScaler() | linear_model.PARegressor(**p))
    
    # You can run the model in the for loop. 
    # Finally, you can select the value of p that improves your metric.
```

After coding, I realized that the [expand-param-grid](https://riverml.xyz/latest/api/utils/expand-param-grid/) tool is a more elegant way to create a parameter grid. I close the issue since we solved it. 🙂

**Comment by ayush488** [comment]
Yes. THanks.
