### ISSUE TITLE
Not able to generate tree diagram using method.draw()

### ISSUE THREAD

**Issue by JFchin11** [online-ml/river#606]

**Comment by raphaelsty** [comment]
Hi @JFchin11, could you provide more details by following the template: bug report

We won't be able to help you otherwise :)

Thank you.

**Comment by JFchin11** [comment]
Dear Raphaelsty
Sorry for the delay in responding. I am running the sample code in the Pycharm. According to the instruction (https://riverml.xyz/latest/user-guide/on-hoeffding-trees/), model.draw() should have generated a tree diagram. However, the diagram is not displayed at the end of the run (no bug report is being generated). I am rather new to python, and this may be a low-level question.
![image](https://user-images.githubusercontent.com/85749548/121888553-ba315000-cd4a-11eb-9747-e6892a0821b6.png)

**Comment by MaxHalford** [comment]
@JFchin11 try to run that code in a Jupyter Notebook instead.
