### ISSUE TITLE
RollingQuantile (median) calculation and even window sizes

### ISSUE THREAD

**Issue by smastelini** [online-ml/river#610]
## Versions

**river version**: all
**Python version**: N/A
**Operating system**: N/A

## Describe the bug

The median values obtained in `stats.RollingQuantile` are not correct when the window size is even. I am not sure how that extends to the other percentile values. But in the specific case of medians, the correct result should be something like:

```python
n = len(w)
if n % 2 == 0:
    return (w[(n - 1) // 2] + w[(n + 1) // 2]) / 2
else:
    return w[n // 2]
```

This calculates the mean between two consecutive data points. However, some might argue that for percentiles the ceiling operation is the way to go. Any thoughts?

## Some context

While investigating the [ikd-Tree card](https://www.notion.so/ikd-Tree-bc9c71e8bce14186a0f2fbb905c3427c) in the Notion's roadmap I started wondering whether or not an incremental, rolling window-based Median estimator would be a nice choice to use in an incremental kd-Tree structure. Then I realized the results were not consistent with the batch results obtained with Python's `statistics.median`.

**Comment by MaxHalford** [comment]
So the implementation is not incorrect but it follows a different convention than the standard library, right? If so it makes sense to align with the standard library, or with numpy.

**Comment by smastelini** [comment]
Yes. This seems to be the case.

### When using an even number of instances

```python
import random

import numpy as np
from river import stats


rng = random.Random(42)


# Even number of instances
data = [rng.uniform(-10, 10) for _ in range(100)]

p25 = stats.RollingQuantile(q=.25, window_size=100)
p50 = stats.RollingQuantile(q=.5, window_size=100)
p75 = stats.RollingQuantile(q=.75, window_size=100)
p99 = stats.RollingQuantile(q=.99, window_size=100)


for d in data:
    p25.update(d)
    p50.update(d)
    p75.update(d)
    p99.update(d)


print([p25.get(), p50.get(), p75.get(), p99.get()])
print(np.percentile(data, q=[25, 50, 75, 99]).tolist())

# [-5.442034486969063, -0.8229629482520231, 4.582535959006984, 9.950752129902206]
# [-5.4654721744826835, -0.3579285930923879, 4.2142115329755985, 9.922710850052939]
```

### Now with an odd number of instances

```python
# Odd number of instances
data = [rng.uniform(-10, 10) for _ in range(101)]

p25 = stats.RollingQuantile(q=.25, window_size=101)
p50 = stats.RollingQuantile(q=.5, window_size=101)
p75 = stats.RollingQuantile(q=.75, window_size=101)
p99 = stats.RollingQuantile(q=.99, window_size=101)


for d in data:
    p25.update(d)
    p50.update(d)
    p75.update(d)
    p99.update(d)


print([p25.get(), p50.get(), p75.get(), p99.get()])
print(np.percentile(data, q=[25, 50, 75, 99]).tolist())

# [-5.39770534806846, -0.5465794737641172, 5.250216001503025, 9.902987133217891]
# [-5.39770534806846, -0.5465794737641172, 5.250216001503025, 9.902987133217891]

```

**Comment by MaxHalford** [comment]
Closing this because we have an answer. Feel free to suggest a change in a PR :)
