### ISSUE TITLE
SimpleImputer

### ISSUE THREAD

**Issue by Loglosss** [online-ml/river#616]
Hi. In river there is no SimpleImputer (

**Comment by MaxHalford** [comment]
What is a `SimpleImputer`? What are you looking to do?

**Comment by JovanVeljanoski** [comment]
I guess they meant [this implementation from scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html). Would be nice to have but simple enough (pardon the pun) to be implemented per use-case..

**Comment by kulbachcedric** [comment]
Isn't it already implemented with the `StatImputer` in `river.preprocessing`?

**Comment by MaxHalford** [comment]
Indeed @kulbachcedric!
