### ISSUE TITLE
expected_mutual_info import error

### ISSUE THREAD

**Issue by ColdTeapot273K** [online-ml/river#617]
## Versions

**river version**: 628de4d4
**Python version**: 3.6.3
**Operating system**: Win10

## Describe the bug
```----> 217 import river.metrics

e:\morefun\develop-river\river\__init__.py in <module>
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,

e:\morefun\develop-river\river\ensemble\__init__.py in <module>
      5 
      6 """
----> 7 from .adaptive_random_forest import (
      8     AdaptiveRandomForestClassifier,
      9     AdaptiveRandomForestRegressor,

e:\morefun\develop-river\river\ensemble\adaptive_random_forest.py in <module>
      7 import numpy as np
      8 
----> 9 from river import base, metrics, stats, tree
     10 from river.drift import ADWIN
     11 from river.tree.nodes.arf_htc_nodes import (

e:\morefun\develop-river\river\metrics\__init__.py in <module>
     33 from .cross_entropy import CrossEntropy
     34 from .exact_match import ExactMatch
---> 35 from .expected_mutual_info import expected_mutual_info
     36 from .fbeta import (
     37     F1,
```

## Steps/code to reproduce
```python
import river.metrics
```

As far as I can see, `.../develop-river/river/metrics/expected_mutual_info.pyx` is present, as well as `.../develop-river/river/metrics/mutual_info.py`

**Comment by MaxHalford** [comment]
@hoanganhngo610 can you look into this? 🙏

**Comment by hoanganhngo610** [comment]
@MaxHalford @ColdTeapot273K As far as I try to reproduce the bug, I have no problem running 
```python
import river.metrics
```
for Python versions 3.7.x and 3.8.x, on MacOS. I believe that @jacobmontiel also does not have any other problems concerning this. 

For the presentation of both `expected_mutual_info.pyx` and `mutual_info.py` in the package, the first Cython file is used as a quick calculation for the Adjusted Mutual Information in the second python file. As a result, there should not be any problems between these 2 files.

**Comment by MaxHalford** [comment]
Indeed I fixed the error recently :)
