### ISSUE TITLE
ImportError: cannot import name 'VectorDict' from 'river.utils'

### ISSUE THREAD

**Issue by Piyushbalwani** [online-ml/river#621]
Hi Team,

I am getting below error while importing `**river** `package. Can you please help.

```
ImportError                               Traceback (most recent call last)
<ipython-input-19-b3971b832238> in <module>
      2 
      3 # from river import datasets
----> 4 from river import evaluate
      5 from river import metrics
      6 from river import preprocessing  # we are going to use that later

xxx/.local/lib/python3.6/site-packages/river/__init__.py in <module>
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,

xxx/.local/lib/python3.6/site-packages/river/anomaly/__init__.py in <module>
      7 
      8 """
----> 9 from .hst import HalfSpaceTrees
     10 
     11 __all__ = ["HalfSpaceTrees"]

xxx/.local/lib/python3.6/site-packages/river/anomaly/hst.py in <module>
      5 
      6 from river import base
----> 7 from river.tree.base import Branch, Leaf
      8 
      9 __all__ = ["HalfSpaceTrees"]

xxx/.local/lib/python3.6/site-packages/river/tree/__init__.py in <module>
     42 """
     43 
---> 44 from . import splitter
     45 from .extremely_fast_decision_tree import ExtremelyFastDecisionTreeClassifier
     46 from .hoeffding_adaptive_tree_classifier import HoeffdingAdaptiveTreeClassifier

xxx/.local/lib/python3.6/site-packages/river/tree/splitter/__init__.py in <module>
     12 
     13 from .base_splitter import Splitter
---> 14 from .ebst_splitter import EBSTSplitter
     15 from .exhaustive_splitter import ExhaustiveSplitter
     16 from .gaussian_splitter import GaussianSplitter

xxx/.local/lib/python3.6/site-packages/river/tree/splitter/ebst_splitter.py in <module>
      3 
      4 from river.stats import Var
----> 5 from river.utils import VectorDict
      6 
      7 from ..utils import BranchFactory

ImportError: cannot import name 'VectorDict' from 'river.utils' (xxx/.local/lib/python3.6/site-packages/river/utils/__init__.py)
```

Regards,
Piyush

**Comment by smastelini** [comment]
Hi @Piyushbalwani, which version are you using? From pip or the development one?

When installing from the source, the Cython portions must be compiled.

Using `pip install -e .` should do the trick if you're using the development version.

**Comment by Piyushbalwani** [comment]
Hi @smastelini,  I installed river with `pip install river`. I am getting error `ModuleNotFoundError: No module named 'river.utils.vectordict'` while executing` import river`.

Below is complete error log:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-30ebf5eeaff2> in <module>
----> 1 import river

xxx/river/__init__.py in <module>
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,

xxx/river/anomaly/__init__.py in <module>
      7 
      8 """
----> 9 from .hst import HalfSpaceTrees
     10 
     11 __all__ = ["HalfSpaceTrees"]

xxx/river/anomaly/hst.py in <module>
      5 
      6 from river import base
----> 7 from river.tree.base import Branch, Leaf
      8 
      9 __all__ = ["HalfSpaceTrees"]

xxx/river/tree/__init__.py in <module>
     42 """
     43 
---> 44 from . import splitter
     45 from .extremely_fast_decision_tree import ExtremelyFastDecisionTreeClassifier
     46 from .hoeffding_adaptive_tree_classifier import HoeffdingAdaptiveTreeClassifier

xxx/river/tree/splitter/__init__.py in <module>
     11 """
     12 
---> 13 from .base_splitter import Splitter
     14 from .ebst_splitter import EBSTSplitter
     15 from .exhaustive_splitter import ExhaustiveSplitter

xxx/river/tree/splitter/base_splitter.py in <module>
      5 
      6 from ..split_criterion.base_split_criterion import SplitCriterion
----> 7 from ..utils import BranchFactory
      8 
      9 

xxx/river/tree/utils.py in <module>
      5 
      6 from river.base.typing import FeatureName
----> 7 from river.stats import Var
      8 
      9 

xxx/river/stats/__init__.py in <module>
      1 """Running statistics"""
----> 2 from .auto_corr import AutoCorr
      3 from .base import Bivariate, Univariate
      4 from .count import Count
      5 from .cov import Cov, RollingCov

xxx/river/stats/auto_corr.py in <module>
      2 import typing
      3 
----> 4 from . import base, pearson
      5 
      6 

xxx/river/stats/pearson.py in <module>
----> 1 from . import base, cov, var
      2 
      3 
      4 class PearsonCorr(base.Bivariate):
      5     """Online Pearson correlation.

xxxr/river/stats/cov.py in <module>
      1 import copy
      2 
----> 3 from . import base, mean, summing
      4 
      5 

xxx/river/stats/mean.py in <module>
      1 import copy
      2 
----> 3 from . import base, summing
      4 
      5 

xxx/river/stats/summing.py in <module>
----> 1 from .. import utils
      2 from . import base
      3 
      4 
      5 class Sum(base.Univariate):

xxx/river/utils/__init__.py in <module>
      7 from .sdft import SDFT
      8 from .skyline import Skyline
----> 9 from .vectordict import VectorDict
     10 from .window import SortedWindow, Window
     11 

ModuleNotFoundError: No module named 'river.utils.vectordict'

```
Regards,
Piyush

**Comment by smastelini** [comment]
@Piyushbalwani were you able to get everything working? Can you share the root cause of the problem?

**Comment by kristopher-wood** [comment]
I've got a similar issue using the version from `pip install river`.

When running model.learn_one(x, y) where x is my dict and y is the target value, I get the following error at line 83 of river\linear_model\glm.py:

> TypeError: can't multiply sequence by non-int of type 'float'

Here are the contents of my dict at the moment:

`{'date': '2019-09-08 17:57:00', 'volume_a': 0.001, 'volume_b': 10.0, 'count': 1}`

Oddly, when I run this through the Spyder 5.0 debugger, I cannot step into utils.VectorDict(x) at all. When I check the definition for the VectorDict class, it's a .pyx file and a .c file so I cannot debug any further with Spyder.

**Comment by MaxHalford** [comment]
Maybe this is because `date` is a `str`?

**Comment by kristopher-wood** [comment]
I ran into the same issue when I was using a timestamp as an int. My point
was more that something is odd about the import from the pip package. I'll
try with -e in a moment.

**Comment by kristopher-wood** [comment]
I wasn't able to use pip install -e river because I didn't have the source to build it yet.

I was wrong in my previous comments regarding my dict though, my timestamp was a float because it was coming from a pandas dataframe and I didn't explicitly set it as an int. I did so and the script runs just fine.

Meanwhile I still can't debug VectorDict possibly because it's not compiled to python. I'll try building from the source after work today. :)

**Comment by MaxHalford** [comment]
Hey, are you on Windows by any chance? It seems that Windows wheels haven't been built for the last version of River. You can try installing version `0.7.0` (`pip install river==0.7.0`) while waiting for a new version to be released.

**Comment by thanaswetha15** [comment]
Hi ,

I am getting below error while importing **river 0.1.0** package. Can you please help.
were you able to get everything working? Can you share the root cause of the problem?



ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10332\1863907629.py in <module>
----> 1 from river import metrics
      2 from river import stream
      3 from river import tree,neighbors,naive_bayes,ensemble,linear_model
      4 from river.drift import DDM, ADWIN,EDDM,HDDM_A,HDDM_W,KSWIN,PageHinkley
      5 

~\anaconda3\lib\site-packages\river\__init__.py in <module>
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,

~\anaconda3\lib\site-packages\river\cluster\__init__.py in <module>
      1 """Unsupervised clustering."""
----> 2 from .clustream import CluStream
      3 from .dbstream import DBSTREAM
      4 from .denstream import DenStream
      5 from .k_means import KMeans

~\anaconda3\lib\site-packages\river\cluster\clustream.py in <module>
      2 from abc import ABCMeta
      3 
----> 4 from river import base, cluster, utils
      5 
      6 EPSILON = 0.00005

~\anaconda3\lib\site-packages\river\utils\__init__.py in <module>
      7 from .sdft import SDFT
      8 from .skyline import Skyline
----> 9 from .vectordict import VectorDict
     10 from .window import SortedWindow, Window
     11 

ModuleNotFoundError: No module named 'river.utils.vectordict'
