### ISSUE TITLE
Add predict_one to classifiers

### ISSUE THREAD

**Issue by PSSF23** [online-ml/river#634]
I noticed the exclusion of `predict_one` function in classifier objects, which seems unnecessary to me. While `predict_proba_one` is nice, sometimes we only need a simple label prediction. Besides, the function could be easily imported from the corresponding regressor class by copy-and-paste, so why not just include them in the first place?

**Comment by smastelini** [comment]
Hi @PSSF23, there is no exclusion. `predict_one` is defined in the base classes. Unless the trees perform special steps, by default, `predict_one` simply assigns the label with the highest weight (obtained from `predict_proba_one`).

**Comment by PSSF23** [comment]
@smastelini I see. Thanks.
