### ISSUE TITLE
What is the core advantage of River compared to general mini-batch models?

### ISSUE THREAD

**Issue by ZulunZhu** [online-ml/river#643]
I read the documents about the regression model or the application in recommender systems, and I still don't know what is River's advantage compared to common models. In your paper, you mentioned that other models need to retrain when new data is added, but actually, River also needs to retrain, right?

**Comment by Aaryanverma** [comment]
In common models, you have to retrain the whole model from scratch after adding new data but in the case of River, the model will be trained only on newly added data in an incremental manner which obviously takes very low computation resources and time.

**Comment by ZulunZhu** [comment]
So in that case, how does the model utilize the old data or old weights?  If only considering the newly added data, it can be inaccurate.

**Comment by mathco-wf** [comment]
The weights are adjust with each data point, so model is not losing any prior information and is also adapting to the distribution of the upcoming data. The problem with traditional ML models are that we need to train the model time to time as the nature of the data may change overtime (data drift/concept drift)  but with online learning you don't need to train your model again.

**Comment by ZulunZhu** [comment]
But in my understanding, when I change the traditional ML models into batch_size=1 training, and it can be the online learning? Because in that case the traditional ML models don't lose any prior information(the weights are adjusted by each known node), and they also don't need to be trained from time to time.

**Comment by Aaryanverma** [comment]
In addition to online learning, river also gives you the advantage of getting predictions even if the number of features while testing is less or more than number of features used in training.

**Comment by ZulunZhu** [comment]
Thanks for your reply. But I want to ensure that, whether the parameter updating in online learning equals the parameter updating in "batch size = 1"?

**Comment by MaxHalford** [comment]
That's the idea yes @ZulunZhu. One advantage at that point is that River is much faster than mini-batch because it's designed to be good at handling the "batch size = 1" case. I'm closing this, feel free to open a discussion if you have more questions! It's a friendlier format than issues and pollutes less.
