### ISSUE TITLE
river/sktime intersection: stream/online mode for forecasting and time series ML

### ISSUE THREAD

**Issue by fkiraly** [online-ml/river#646]
Brilliant toolbox, nice work!
I also admire the pragmatic and collaborative ethos behind your recent merger, this is really rare.

@fkiraly here from [sktime](https://github.com/alan-turing-institute/sktime), I was wondering about a particular intersection I've spotted:

* sktime's scope is time series ML, with a particular focus on forecasting - it seems like you have forecasting on your roadmap, too. Nice SNARIMAX there.
* sktime's forecasting core design has methods for stream updating and forecasting, `update`, and `update_predict` - we are going through a phase of refactoring, and the stream/update interface has been identified as an important pain point and refactor target, see issue https://github.com/alan-turing-institute/sktime/issues/982
* both projects seem particularly interested in scikit-learn-like composition
* other intersections are in the domain of stream anomaly detection, with temporal vs tabular batch methods being very closely linked.

I was hence thinking, wouldn't it make a lot of sense to stick our heads together and ensure compatible interfaces?
Not sure how to contact you best, your landing page does not seem too informative in that respect...

**Comment by jacobmontiel** [comment]
Thanks for reaching out. Yes, we are proud of the merger. It is indeed important to consider how open-source packages such as `sktime` and `river` play a role in the larger Python/ML ecosystem. I am pinging the other two maintainers: @MaxHalford and @smastelini . Some people on our team are currently on vacation. What is your timeline for the refactoring and a possible discussion?

**Comment by fkiraly** [comment]
>What is your timeline for the refactoring and a possible discussion?

Not too much urgency, but maybe Aug/Sep if possible? 
Summer is quieter at day jobs and hence a better time for contributing 😃 so earlier is better.

Perhaps we could already exchange contact details to schedule a meeting due ahead of time?

You could PM me on the sktime gitter with emails, or we could chat on the sktime slack to which I can invite you using any type of PM. You could also simply email me under `f.kiraly` at UCL's domain (the London university)

**Comment by jacobmontiel** [comment]
> Not too much urgency, but maybe Aug/Sep if possible?

This should work fine.

> Perhaps we could already exchange contact details to schedule a meeting due ahead of time?

Already sent you an email.

I will close this issue later today to avoid confusion.
