### ISSUE TITLE
Bayesian linear regression

### ISSUE THREAD

**Issue by MaxHalford** [online-ml/river#65]
I'm currently working on an implementation of Bayesian linear regression for streaming data. I don't need any help (yet!) but I'm just putting this issue here for information.

**Comment by kivo360** [comment]
What's the progress on this? I'd really love it.

**Comment by MaxHalford** [comment]
I have a prototype that is working, but I haven't pushed it yet. It's a whole new field for me so I'm learning a lot. One of the papers of my PhD will be using this. You'll to be patient on this one :).

**Comment by kivo360** [comment]
:( ha ha, okay. I can't wait. This is something I've been looking for outside of libraries such as pyro and pymc.

**Comment by filipmarkoski** [comment]
Where is this model available? I cannot find Bayesian Linear Regression as easily as I found [Linear Regression](https://riverml.xyz/latest/api/linear-model/LinearRegression/). While web searching for a variant I stubbled across this [Bayesian Linear Regressor](https://probflow.readthedocs.io/en/latest/user_guide/models.html#bayesian-updating) however I would like to use `river` if possible. 

The aforementioned `probflow` linear regressor replaces the priors with the already calculated posteriors as the aim is online learning.

**Comment by MaxHalford** [comment]
I have made no progress on this! I have a job now so it's a bit difficult to commit time :)

**Comment by MaxHalford** [comment]
Adding this to the [roadmap](https://www.notion.so/d1e86fcdf21e4deda16eedab2b3361fb?v=503f44740b8b44a99a961aa96e9e46e1) instead.

**Comment by davidsteinar** [comment]
@MaxHalford in your awesome blog post on [Bayesian linear regression](https://maxhalford.github.io/blog/bayesian-linear-regression/) you already have working code examples, would it be hard to implement in the River framework? 

This is something that would be very useful for me, or do you know of any other Python implementations of online Bayesian linear regression? It seems that most Bayesian frameworks are still batch based, even considering that the posterior can so naturally become the prior for new data (which is awesome).

**Comment by MaxHalford** [comment]
Yep it shouldn't be too hard, the only caveat is that the blog post using numpy and here we need to support dictionaries. It's totally doable, I've just been too lazy and busy with other things!

**Comment by TomKealy** [comment]
I would be willing to integrate a bayesian model, if someone could give me guidance.

**Comment by MaxHalford** [comment]
The code in [this](https://maxhalford.github.io/blog/bayesian-linear-regression/) blog post works well for mini-batches of data. It leverages the Sherman-Morrison identity to estimate the inverse covariance matrix online. But to make this work for River, one would have to make it work with dictionaries, which is not trivial.

**Comment by TomKealy** [comment]
`But to make this work for River, one would have to make it work with dictionaries, which is not trivial.`

That's fine!

If you could provide some acceptence criteria, this is something I'd be happy to work on!
