### ISSUE TITLE
Update `Reading data` section of the user guide

### ISSUE THREAD

**Issue by gbolmier** [online-ml/river#660]
Fetching `sklearn` datasets with `stream.iter_sklearn_dataset` should be mentioned

**Comment by MaxHalford** [comment]
Done!

**Comment by MaxHalford** [comment]
By the way let's try and use the [roadmap](https://www.notion.so/d1e86fcdf21e4deda16eedab2b3361fb?v=503f44740b8b44a99a961aa96e9e46e1) instead of opening issues for listing stuff to implement.
