### ISSUE TITLE
Doc inconsistency for ADWIN drift detection method

### ISSUE THREAD

**Issue by rscmendes** [online-ml/river#688]
**river version**: v0.7.1

The documentation of the ADWIN drift detector in `river/drift/adwin.py` seems to be inconsistent with the other drift detectors.

Specifically, it states that `value` should be 1 for correct classification and 0 for error. This is in contrast with DMM and variants, and I believe it to be an error in the documentation of ADWIN.

Let me know if you would like a PR to fix this. If you do want a PR, should we normalize the text of the **Input** note to be equal to the DDM one?

PS: Sorry if this should've been posted in the Discussions. Let me know, and I'll copy it to over there.

**Comment by smastelini** [comment]
Thanks for mentioning that @rscmendes. Pinging @jacobmontiel.

**Comment by jacobmontiel** [comment]
Hi @rscmendes 

This is actually correct. `DDM` explicitly tracks error occurrences (1). `ADWIN` tracks the distribution of the data by keeping the "reference" and "current" window. Actually, this implementation of `ADWIN` supports continuous values as input. In the original paper, the input for classification error is defined as `1=correct`, `0=error`. In theory, you could invert the input to be consistent with `DDM`. Note, the same does not apply for `DDM`.

**Comment by rscmendes** [comment]
> Hi @rscmendes
> 
> This is actually correct. `DDM` explicitly tracks error occurrences (1). `ADWIN` tracks the distribution of the data by keeping the "reference" and "current" window. Actually, this implementation of `ADWIN` supports continuous values as input. In the original paper, the input for classification error is defined as `1=correct`, `0=error`. In theory, you could invert the input to be consistent with `DDM`. Note, the same does not apply for `DDM`.

Thanks a lot for the clarification. I should've check the reference.

I've actually stumbled upon this discrepancy when trying to run multiple drift detectors on a cycle in the form of:
```
name2detector = {"DDM": drift.DDM(), 
                 "ADWIN": drift.ADWIN(),
                 "EDDM": drift.EDDM(),
                 "HDDM_A": drift.HDDM_A(),
                 "HDDM_W": drift.HDDM_W(),
                }

for drift_detector_name, drift_detector in name2detector.items():
   # ...
   drift_detector.update(is_prediction_correct)
```
Now I might need to check whether the method is ADWIN and then negate `is_prediction_correct` if so, which is fine but not as intuitive -- but that's another discussion. I'll close the issue. 

Thank you.
