### ISSUE TITLE
Documentation does not build locally

### ISSUE THREAD

**Issue by silvavn** [online-ml/river#724]
## Versions

**river version**: Latest
**Python version**: 3.7
**Operating system**: Windows

## Describe the bug

After following instructions found here: https://github.com/online-ml/river/blob/master/CONTRIBUTING.md 
Documentation does not seem to build. I keep getting errors saying that `user-guide` and `API` Nav entries are not found.

## Steps/code to reproduce

Clone repo
Install all plugins
then run
```
$ pip install -e ".[docs]"
$ pip install git+https://github.com/MaxHalford/yamp
$ mkdocs serve --dirtyreload
```

**Comment by MaxHalford** [comment]
Hey. How about if you run `make doc` instead of `mkdocs serve --dirtyreload`?

**Comment by silvavn** [comment]
Solved, docs seem to need linux to be built. Under windows I setup wsl2 and use the `make doc` or `make livedoc`.
Thanks
