### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import. In google colab.

### ISSUE THREAD

**Issue by draperjames** [online-ml/river#728]
## Versions

**river version: latest**:
**Python version: latest**:
**Operating system: colab vm**:

### Input

```python
# Sample code to reproduce the problem
```

**Comment by raphaelsty** [comment]
Hi @draperjames,

This should solve the problem: `pip install -U numpy`
 
This issue is described on [stackoverflow](https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import).

**Comment by MaxHalford** [comment]
Marking as closed, feel free to reopen if the problem persists.
