### ISSUE TITLE
MultiLabelConfusionMatrix() is none type

### ISSUE THREAD

**Issue by icedpanda** [online-ml/river#730]
## Versions

**river version**: 0.8.0
**Python version**: 3.6.13
**Operating system**: mac OS

## Describe the bug

I using `LabelCombinationHoeffdingTreeClassifier()` for a multi-label classification problem and use `ExamplePrecision()` as evaluation metric. 

Meanwhile, I want to see the model performance on each class so I use `MultilabelconfusionMatrix` metric but receive '`NoneType' object has no attribute 'update'`. 
## Steps/code to reproduce

```python
# evaluation on testing set
precision = metrics.ExamplePrecision()
cm = metrics.MultiLabelConfusionMatrix()
for idx, (feature, label) in enumerate(test_dataset):
    y_pred = model.predict_one(feature)
    precision  = metric.update(label, y_pred)
    cm = cm.update(label, y_pred)
```

Get the following traceback
```python
<ipython-input-208-ed687990afa2> in <module>
     16     y_pred = model.predict_one(feature)
     17     precision  = metric.update(label, y_pred)
---> 18     cm = cm.update(label, y_pred)
     19 
     20 

AttributeError: 'NoneType' object has no attribute 'update'
```

Does river provide similar precision like in sklearn `precision_score(average="None")` that return the scores for each class?  I only found ExamplePrecision() in river that supports multi-label. 

I have tried `ClassificationReport()` but it looks like only support multi-class/binary or list-liked array while river created dict-liked outputs/inputs for multi-label.

What would be the best practice to generate a multi-label classification report in river?

Thanks

**Comment by icedpanda** [comment]
Thank you @MaxHalford , `cm.update(label, y_pred)` works! 

Does the river have an existing API that supports class-level precision for a multi-output classifier?

**Comment by MaxHalford** [comment]
Mmm I'm not sure. But the fact that you can't find it by yourself in the documentation is a failure on our side 😅. @jacobmontiel can I pretty please ask you to chime in? :)

**Comment by jacobmontiel** [comment]
Hi @icedpanda 

Indeed, the classification report only supports binary/multi-class classification. This is missing in the documentation, our bad.

Label-based metrics are not currently available. However, you can calculate them from the multi-label confusion matrix. The interface can be confusing though. Here is a MWE:

Instantiating and updating a multi-label confusion matrix

```python
from river import metrics

y_true = [
    {0: 0, 1: 1, 2: 1},
    {0: 1, 1: 1, 2: 0},
    {0: 1, 1: 1, 2: 0},
]
y_pred = [
    {0: 1, 1: 1, 2: 1},
    {0: 1, 1: 0, 2: 0},
    {0: 1, 1: 1, 2: 0},
]
cm = metrics.MultiLabelConfusionMatrix()
for yt, yp in zip(y_true, y_pred):
    cm.update(yt, yp)

cm
```

In the last line, we just print the state of the confusion matrix

```
  Label     TP     FP     FN     TN
      0    2.0    1.0    0.0    0.0
      1    2.0    0.0    1.0    0.0
      2    1.0    0.0    0.0    2.0
```

You can actually access the data in the confusion matrix (`cm.data`) which is essentially a 3d matrix. Be careful to access the labels as they are stored in the data matrix (this depends on the order of arrival). For that, you can use the internal dictionary `cm._label_dict` that maps the labels with their index in the data matrix. Here is the calculation for Precision:

```python
precision = {label: cm.data[key][1][1] / (cm.data[key][1][1] + cm.data[key][0][1])
             for label, key in cm._label_dict.items()}
```

and the result
```
{0: 0.6666666666666666, 1: 1.0, 2: 1.0}
```

Similarily, for recall:

```python
recall = {label: cm.data[key][1][1] / (cm.data[key][1][1] + cm.data[key][1][0])
          for label, key in cm._label_dict.items()} 
```

```
{0: 1.0, 1: 0.6666666666666666, 2: 1.0}
```

You can compare against the `sklearn` methods:

```python
from sklearn.metrics import recall_score, precision_score

y_true = [[0,1,1], [1,1,0], [1,1,0]]
y_pred = [[1,1,1], [1,0,0], [1,1,0]]
precision_score(y_true, y_pred, average=None)
```

```
array([0.66666667, 1.        , 1.        ])
```

```python
recall_score(y_true, y_pred, average=None)
```

```
array([1.        , 0.66666667, 1.        ])
```

I hope this helps. Let me know if you have questions.

**Comment by icedpanda** [comment]
Hi @jacobmontiel, this is really helpful. Thanks
