### ISSUE TITLE
TypeError: can't convert complex to float

### ISSUE THREAD

**Issue by TrungKhoaLe** [online-ml/river#732]
I tried to feed a pandas dataframe to RiverML in a row by row manner, and I received the following problem:

`
 File "/Users/kl/.virtualenvs/my_env/lib/python3.8/site-packages/river/proba/gaussian.py", line 68, in cdf
    return 0.5 * (1.0 + math.erf((x - self.mu) / (self.sigma * math.sqrt(2.0))))
TypeError: can't convert complex to float
`

I checked the rows/samples where the problem occurred, but I didn't find any thing weird. Have you guys ever met this problem before?

At the moment, I have to drop those samples out of the dataset to bypass the issue.

**Comment by TrungKhoaLe** [comment]
Is the the data at the row where the issue occurred useful? The following is the data per se:
`
0.217119 | 0.217487 | 0.216522 | 0.217208 | 40900.0 | 0.34565551 | 0.0001 | 0.1759920877268840 | 8.555267642648770 | -0.021623005418827300 | -10.627953088097200 | 40.28459993186120 | -0.0021128545232274200 | -0.0007030640130263160 | -517.2203368176910 | 939.6522432960190 | 0.0 | 0.0 | -0.19311422906815600 | 0.0 | 1.0 | 0.12554904831625600 | 1.1838769268050900 | -0.00031314997795825900 | 20.916903789823100 | 25.28797889327800 | 31.04950922443070 | 1.1705758146436100 | -0.0005341999999999850 | -4.329590078504340 | 32.0 | 96.0 | -64.0 | 0.0 | 0.0 | 14.587784520919500 | 41.0326990538092 | 0.035694509367050300 | 0.04385521048325570 | 0.25032821272827200 | 42.87214612602350 | 14.991344059276300 | -1.0820460507140700 | 13.978786737336000 | 11.003484568282000 | 2.9753021690539200 | 0.06403493819937550 | 0.06401444458108420 | 0.217 | 0.21737 | 0.21639 | 0.21702 | 13481612.0 | 0.34717584 | 0.0001 | 6.22920395043714 | 7.886174622423870 | 0.011645884305729400 | -2185.5194837193400 | 42.63865749390830 | -6.32416954293006E-06 | -2.96426624134266E-06 | -132595.2823106750 | 829.6069777335990 | 0.0 | 0.0 | -0.19783996072655900 | 0.0 | 1.0 | 0.11371841155234500 | 1.1556541370938200 | -0.0003142659868250000 | 22.99559469106120 | 25.339797418368600 | 29.25928037633230 | 1.1569383259911900 | -0.0006654999999999860 | -4.202011660801360 | 32.0 | 8.0 | 24.0 | 0.0 | 0.0 | 18.483645824291100 | 40.69650350755480 | 0.005293501179677200 | 0.0342110183953773 | 0.2547074786044290 | 44.19740277193650 | 15.364827365281200 | -1.1298405466970400 | 16.181295207001900 | 14.199256319352400 | 1.9820388876494900 | 0.009216589861749110 | 0.009216165160208510 | 23 | 8 | 7 | 0 | 1 | 0.08655298147398630 | 0 | 0.0
`

The following is the summary of the data:

`Open_exchange_1              0.217119
High_exchange_1              0.217487
Low_exchange_1               0.216522
Close_exchange_1             0.217208
Volume_exchange_1        40900.000000
                             ...     
second                       0.000000
higher_closing_price         1.000000
pct_higher                   0.086553
arbitrage_opportunity        0.000000
target                       0.000000
Name: 20647, Length: 104, dtype: float64
`

**Comment by MaxHalford** [comment]
Papertrail: @TrungKhoaLe shared the code and dataset with me by email. I'll debug.

**Comment by MaxHalford** [comment]
Thanks for being persistent.

I think that the new implementation is more stable. But as you say it's still not perfect. My gut feeling is that the algorithm is not stable when weights are involved. I managed to reproduce the instability with this example:

```py
from river import stats

D = [
    (99.99999978143265, 6),
    (99.99999989071631, 8),
    (99.99999994535816, 6),
    (99.99999997267908, 9),
    (99.99999998633952, 10),
    (99.99999999316977, 3),
    (99.99999999829245, 5),
    (99.99999999957309, 9)
]

var = stats.Var()

for x, w in D:
    s.update(x, w)
    
print(s.get())
```

```
-1.50379458547148e-13
```

Obviously a variance should never be negative! I'll dig into this, but feel free to do so too.
