### ISSUE TITLE
Docs correction for DDM and variants

### ISSUE THREAD

**Issue by tnwei** [online-ml/river#742]
## Versions

**river version**: latest
**Python version**: N/A
**Operating system**: N/A

## Describe the bug

Hi folks, noticed an inconsistency in docs for `river.drift.DDM`, `river.drift.EDDM`, `river.drift.HDDM_A`,  and `river.drift.HDDM_W`. The docs denote that 0 in inputs represent prediction error. However, that statement is contradicted by the elaboration right under it, as well as comments in the code: https://github.com/online-ml/river/blob/842f7c5be5574e62a3aab0b46d996eb5f1d73beb/river/drift/ddm.py#L125 

The text in question:
```
  **Input:** `value` must be a binary signal, where 0 indicates error.
  For example, if a classifier's prediction $y'$ is right or wrong w.r.t the
  true target label $y$:

  - 0: Correct, $y=y'$

  - 1: Error, $y \neq y'$
```   

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
```

**Comment by MaxHalford** [comment]
Ok I'm merging the PR and closing this PR. @jacobmontiel feel free to raise your hand if it doesn't look right to you.
