### ISSUE TITLE
Serving Framework for Online Machine Learning 

### ISSUE THREAD

**Issue by LeonardAukea** [online-ml/river#754]
I recently proposed a suggestion to KServe community to add support for serving online machine learning models on k8s. Not sure how that will land. Either way, I think it would be interesting to build on top of [cloudstate](https://cloudstate.io/) and design a CRD `OnlineInferenceService` and controller. Since, online models need to be stateful. We need to opt for a solution that manages state in a distributed setting. All of this is explained with with a bit more detail in the following issue: 

https://github.com/kserve/kserve/issues/1890#issue-1041526101

If the interest is low in the Kserve community, I propose that such an implementation is added to River itself.

**Comment by MaxHalford** [comment]
Cool! I'm not well-versed in KServe so I can't help right now. But I'll take a loot.

Meta: I suggest converting this issue into a discussion. I think you can do it as you're the OP.

**Comment by LeonardAukea** [comment]
> Cool! I'm not well-versed in KServe so I can't help right now. But I'll take a loot.
> 
> Meta: I suggest converting this issue into a discussion. I think you can do it as you're the OP.

@MaxHalford It seems like I'm not allowed to convert the issue to a discussion. At least I don't see that option where it is usually visible.
