### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [online-ml/river#765]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

```diff
diff --git a/river/drift/ddm.py b/river/drift/ddm.py
index 7b59bc4e..822d4306 100644
--- a/river/drift/ddm.py
+++ b/river/drift/ddm.py
@@ -128,7 +128,7 @@ class DDM(DriftDetector):
         if self._in_concept_change:
             self.reset()
 
-        self.miss_prob = self.miss_prob + (value - self.miss_prob) / float(
+        self.miss_prob += (value - self.miss_prob) / float(
             self.sample_count
         )
         self.miss_std = math.sqrt(
diff --git a/river/drift/eddm.py b/river/drift/eddm.py
index 9f23db06..287f6c44 100644
--- a/river/drift/eddm.py
+++ b/river/drift/eddm.py
@@ -142,7 +142,7 @@ class EDDM(DriftDetector):
                 self.m_mean + (float(distance) - self.m_mean) / self.m_num_errors
             )
             self.estimation = self.m_mean
-            self.m_std_temp = self.m_std_temp + (distance - self.m_mean) * (
+            self.m_std_temp += (distance - self.m_mean) * (
                 distance - old_mean
             )
             std = np.sqrt(self.m_std_temp / self.m_num_errors)
diff --git a/river/drift/page_hinkley.py b/river/drift/page_hinkley.py
index ce80fdc8..c09bae44 100644
--- a/river/drift/page_hinkley.py
+++ b/river/drift/page_hinkley.py
@@ -81,7 +81,7 @@ class PageHinkley(DriftDetector):
         if self._in_concept_change:
             self.reset()
 
-        self.x_mean = self.x_mean + (value - self.x_mean) / float(self.sample_count)
+        self.x_mean += (value - self.x_mean) / float(self.sample_count)
         self.sum = max(0.0, self.alpha * self.sum + (value - self.x_mean - self.delta))
 
         self.sample_count += 1
diff --git a/river/ensemble/adaptive_random_forest.py b/river/ensemble/adaptive_random_forest.py
index b02d1d96..d9bcd505 100644
--- a/river/ensemble/adaptive_random_forest.py
+++ b/river/ensemble/adaptive_random_forest.py
@@ -817,7 +817,7 @@ class AdaptiveRandomForestRegressor(BaseForest, base.Regressor):
                 # The higher the error, the worse is the tree
                 weights = sum_weights - weights
                 # Normalize weights to sum up to 1
-                weights = weights / weights.sum()
+                weights /= weights.sum()
                 y_pred *= weights
         else:
             for idx, model in enumerate(self.models):
diff --git a/river/metrics/pair_confusion.py b/river/metrics/pair_confusion.py
index c5a62ae3..84bb7196 100644
--- a/river/metrics/pair_confusion.py
+++ b/river/metrics/pair_confusion.py
@@ -79,9 +79,9 @@ class PairConfusionMatrix(metrics.MultiClassMetric):
 
         true_positives = sum_squares - self.cm.n_samples
 
-        false_positives = false_positives - sum_squares
+        false_positives -= sum_squares
 
-        false_negatives = false_negatives - sum_squares
+        false_negatives -= sum_squares
 
         true_negatives = (
             self.cm.n_samples * self.cm.n_samples
diff --git a/river/preprocessing/lda.py b/river/preprocessing/lda.py
index 9e38ba35..2d85b4f0 100644
--- a/river/preprocessing/lda.py
+++ b/river/preprocessing/lda.py
@@ -351,7 +351,7 @@ class LDA(base.Transformer):
 
         phi = self.rng.random((self.n_components, size_vocab))
 
-        phi = phi / np.sum(phi, axis=0)
+        phi /= np.sum(phi, axis=0)
 
         phi_sum = np.sum(phi, axis=1)
 
diff --git a/river/tree/nodes/hatc_nodes.py b/river/tree/nodes/hatc_nodes.py
index 1f45290c..77f5cd80 100644
--- a/river/tree/nodes/hatc_nodes.py
+++ b/river/tree/nodes/hatc_nodes.py
@@ -88,7 +88,7 @@ class AdaLeafClassifier(LeafNaiveBayesAdaptive, AdaNode):
             # Perform bootstrap-sampling
             k = self._rng.poisson(1.0)
             if k > 0:
-                sample_weight = sample_weight * k
+                sample_weight *= k
 
         aux = self.prediction(x, tree=tree)
         class_prediction = max(aux, key=aux.get) if aux else None
diff --git a/river/tree/nodes/hatr_nodes.py b/river/tree/nodes/hatr_nodes.py
index 82f3e506..50c2d653 100644
--- a/river/tree/nodes/hatr_nodes.py
+++ b/river/tree/nodes/hatr_nodes.py
@@ -72,7 +72,7 @@ class AdaLeafRegressor(HTLeaf, AdaNode):
             # Perform bootstrap-sampling
             k = self._rng.poisson(1.0)
             if k > 0:
-                sample_weight = sample_weight * k
+                sample_weight *= k
 
         if self._adwin is None:
             self._adwin = ADWIN(delta=self.adwin_delta)
```

**Comment by MaxHalford** [comment]
Hello 👋

That's rather cool? May I ask which tool you used? We could consider adding it to our CI setup.

Regarding the changes listed in your post, could you take care of opening a pull request to implement them?

**Comment by elfring** [comment]
>May I ask which tool you used?

The shown update candidates were found with the help of a tiny Perl command (which I constructed for this transformation approach).


>We could consider adding it to our CI setup.

Such feedback sounds promising.
I know that the applied search pattern can be also improved further.


>Regarding the changes listed in your post, …?

Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")? :thinking:

**Comment by MaxHalford** [comment]
> Do any factors hinder the wider application of functionality which became generally available with Python 2? 🤔

Not at all. These are just low hanging fruits waiting to be picked.

Meta: I would have expected [black](https://github.com/psf/black) to pick these up.

**Comment by elfring** [comment]
>These are just low hanging fruits waiting to be picked.

Thanks for such a positive feedback.
I came along other software areas where some developers reacted in questionable ways according to the presented transformation pattern.

**Comment by MaxHalford** [comment]
I welcome any kind of help. I appreciate the effort to open an issue or a discussion. Open source software would never work without good manners and positivity :)

To come back to the point: do you feel comfortable to open an issue to apply the changes suggested by your Perl command? If you don't, then I'll gladly do the changes. The nice thing about you doing the change is that you'll be listed as contributor.

It would be great to check if what your tool does isn't already done by some other established tool. If it isn't, then you can either contribute to an existing tool, or package your tool into something that can be used in CI. I'm sure people would appreciate it. Regardless, that's a separate issue that I'll let you handle.

**Comment by elfring** [comment]
>do you feel comfortable to open an issue

I submitted several suggestions (or bug reports) for published software components.


>to apply the changes suggested by your Perl command?

:thinking:
* The licence selections can trigger special development considerations.
* The command example is also improvable.


>If you don't, then I'll gladly do the changes.

:thought_balloon: This would be nice.


>The nice thing about you doing the change is that you'll be listed as contributor.

I would find it occasionally sufficient to be active as an idea reporter in selected areas.


>If it isn't, then you can either contribute to an existing tool, …

:thought_balloon: Would you like to help another bit to influence the software situation any more?


>I'm sure people would appreciate it.

The responses are varying (also according to my published software development activities).

**Comment by elfring** [comment]
Thanks for your integration of a small software adjustment.

* :thought_balloon: Has this issue got the potential to trigger any more collateral evolution?
* How much do source code refactorings fit to streaming data for machine learning approaches? :thinking:

**Comment by MaxHalford** [comment]
> Thanks for your integration of a small software adjustment.

With pleasure!

> 💭 Has this issue got the potential to trigger any more collateral evolution?

I would say so! As I already mentioned, it would be nice if your tool was available as a continuous integration tool.

> How much do source code refactorings fit to streaming data for machine learning approaches? 🤔

I'm sorry but I don't really understand the question. Would you be so kind as to reformulate?

**Comment by elfring** [comment]
>…, it would be nice if your tool was available as a continuous integration tool.

:thought_balloon: Can you get any further development ideas from [related information sources](https://github.com/iipeace/guider/issues/266#issuecomment-944926071 "Increase the usage of augmented assignment statements")?


>Would you be so kind as to reformulate?

The integrated source code adjustment can be achieved with various software tools.
:thought_balloon: You would like to improve the software library “online-ml/river” (besides others), wouldn't you?

Thus the information “River's ambition is to be the go-to library for doing machine learning on streaming data.” is provided.
How much can the evolving technology “machine learning” be applied for [discussed software changes](https://en.wikipedia.org/wiki/Automatic_bug_fixing "Description for the repair of software bugs")? :thinking:

**Comment by MaxHalford** [comment]
> 💭 Can you get any further development ideas from related information sources?

Thanks for the link. As far as I can tell you're making use of regex. Therefore, you should be able to implement what you're doing as a linting rule. I would suggest looking into flake8 and/or black to see where the linting rule should be added.

>  How much can the evolving technology “machine learning” be applied for discussed software changes? 🤔

That's a beefy topic! I'm not sure I have a good answer.

**Comment by elfring** [comment]
>As far as I can tell you're making use of regex.

I am demonstrating that some helpful data processing results can be achieved also by the application of advanced regular expressions according to approaches for searching and replacing source code.


>Therefore, you should be able to implement what you're doing as a linting rule.

* :thought_balloon: Further software developments in such design directions will depend on general change acceptance and related factors.
* Some evolution would be nice also for the use of semantic patch languages, wouldn't it? :thinking:
