### ISSUE TITLE
is it possible  incrementally train CategoricalNB  Naive Bayes 

### ISSUE THREAD

**Issue by Sandy4321** [online-ml/river#772]
is it possible  incrementally train your code CategoricalNB  Naive Bayes 
when scikit  CategoricalNB   can not predict / retrain for new values in features 
https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.CategoricalNB.html#sklearn.naive_bayes.CategoricalNB

scikit onloy can do it for MultinomialNB, BernoulliNB, and GaussianNB

https://scikit-learn.org/stable/modules/naive_bayes.html#out-of-core-naive-bayes-model-fitting

MultinomialNB, BernoulliNB, and GaussianNB expose a partial_fit method that can be used incrementally as done with other classifiers

**Comment by raphaelsty** [comment]
Hi @Sandy4321, River provides `MultinomialNB`, `BernoulliNB`, and `GaussianNB`, `ComplementNB` but do not provide `CategoricalNB` :)

**Comment by Sandy4321** [comment]
any  plans?

**Comment by raphaelsty** [comment]
Contributions are welcome
