### ISSUE TITLE
Code and Docs not align

### ISSUE THREAD

**Issue by cenzwong** [online-ml/river#785]
# The River.time_series module not align with the docs

Originally I would like to use the detrend function in time_series module. But I have installed the latest version (0.8.0) of river and the package from river is totally different from the docs. (see the attached images)

![image](https://user-images.githubusercontent.com/44856918/143606898-ea6b13cc-c772-4182-bd2b-36f8acb4c411.png)

![image](https://user-images.githubusercontent.com/44856918/143606977-4e1cc8b6-963f-4d5c-8793-434658fbd148.png)

So I would like to ask where is the detrend module place inside the library?

**Comment by cenzwong** [comment]
https://github.com/online-ml/river/blob/236cade8d46e128629a4dc12b69e0e2426461506/docs/releases/unreleased.md

time_series
time_series.Detrender and time_series.GroupDetrender have been removed as they overlap with meta.TargetStandardScaler.
Implemented a time_series.evaluate method, which performs progressive validation for time series scenarios.
Implemented time_series.HorizonMetric class to evaluate the performance of a forecasting model at each time step along a horizon.
Implemented time_series.HoltWinters.

for those who need to use the detrender function, you can check the above guide.


Also, this examples needs update as well
https://riverml.xyz/latest/examples/building-a-simple-time-series-model/

**Comment by MaxHalford** [comment]
Hey there! How did you install River? With pip?

**Comment by cenzwong** [comment]
I install with ```pip install git+https://github.com/online-ml/river --upgrade```

**Comment by MaxHalford** [comment]
So you installed the development version. The docs for those are [here](https://riverml.xyz/dev/). To install version 0.8.0 (the latest stable version) you should simply do `pip install river --upgrade`. Please tell me if it's not clear :)
