### ISSUE TITLE
MAE potentially in wrong order in bike share example doc

### ISSUE THREAD

**Issue by Pverheijen** [online-ml/river#800]
The MAE is stated to be too optimistic yet is lower than the corrected version in the bike share example that follows.

I'll write a more detailed description later this week. 

https://riverml.xyz/latest/examples/bike-sharing-forecasting/

**Comment by MaxHalford** [comment]
Hello there @Pverheijen. Thanks for opening this issue. That is indeed a bit worrying. I'm not sure where the issue is coming from.

**Comment by remiadon** [comment]
Hello there, just for curiosity, is it related to the update of the `metrics.MAE` class itself or the call to `evaluate.progressive_val_score` ? I do hope this is the latest

**Comment by MaxHalford** [comment]
Probably the latter. But I haven't had time to look into it yet

**Comment by MaxHalford** [comment]
I've fixed the docs. It's a bit long to explain, but basically I was very wrong the first time I wrote those docs :)
