### ISSUE TITLE
Mathematical formulas are not rendered in docs

### ISSUE THREAD

**Issue by david26694** [online-ml/river#805]
Is this expected?

![image](https://user-images.githubusercontent.com/22721584/146405668-e8e41ef7-84aa-4893-8ace-e782dd3923fb.png)

**Comment by MaxHalford** [comment]
Yes this sometimes bugs out. Can you try with the [development version](https://riverml.xyz/dev/)?

**Comment by david26694** [comment]
It works in the development version, yes

**Comment by MaxHalford** [comment]
I believe @nakamasato fixed the issue.

**Comment by nakamasato** [comment]
Yes, I fixed it in https://github.com/online-ml/river/pull/792.
