### ISSUE TITLE
PageHinkley only detects increases in mean

### ISSUE THREAD

**Issue by yuritpinheiro** [online-ml/river#810]
## Describe the bug
PageHinkley Concept Drift Detector is unable to detect concept drift for a statistical mean which decreases in value.

## Steps/code to reproduce
```
import numpy as np
from river.drift import PageHinkley

import matplotlib.pyplot as plt

data = np.random.normal((0, 5, 0), size=(1000, 3)).T.reshape(-1)

cdd = PageHinkley()
sum_list = []
detect = []
for i, x in enumerate(data):
    cdd.update(x)
    sum_list.append(cdd.sum)
    if cdd.change_detected:
        detect.append(i)

data_plot = plt.plot(data, label="Data samples")
ax2 = plt.gca().twinx()
sum_plot = ax2.plot(sum_list, color='orange', label="PHT sum")
for d in detect:
    detect_plot = plt.axvline(d, c="red")

plt.legend([data_plot[0], sum_plot[0], detect_plot], ["Data samples", "PHT sum", "CD detection"])
plt.show()
```
![image](https://user-images.githubusercontent.com/13771630/147503616-3f271487-e2a1-46c9-9260-14e5faf72f52.png)

**Comment by MaxHalford** [comment]
Hello there! I'm not familiar with this specific part of the code base. I'll let @jacobmontiel or maybe @smastelini take a look when they can.

**Comment by smastelini** [comment]
I'm not familiar with this portion of the codebase, but I can give it a try if @jacobmontiel is unavailable. I believe he coded PageHinkley.

**Comment by jacobmontiel** [comment]
Hi @yuritpinheiro

This is the expected behavior. Page-Hinkley (and CUSUM) is a one-sided drift detector, it only indicates changes when the mean increases.

You can easily extend the existing implementation to create a two-sided detector by symmetry or use a two-sided detector such as HDDM or ADWIN.

**Comment by yuritpinheiro** [comment]
Thank you @jacobmontiel.
