### ISSUE TITLE
Error with learn_one

### ISSUE THREAD

**Issue by rj76** [online-ml/river#817]
## Versions

**river version**:
0.9.0

**Python version**:
3.9.7

**Operating system**:
linux

## Describe the bug

When trying to start learning with learn_one, an exception is beging raised: `TypeError: unsupported operand type(s) for -: 'str' and 'float'`

## Steps/code to reproduce

```python
from river import compose
from river import linear_model
from river import optim
from river import preprocessing


mlmodel = compose.Pipeline(
    compose.Select('customer', 'postal', 'city', 'country', 'weekday'),
    preprocessing.StandardScaler(),
    linear_model.LogisticRegression(optimizer=optim.SGD(0.001))
)

data = {'customer': 'GLS Spaanse Polder 1091', 'postal': '3044EW', 'city': 'Rotterdam', 'country': 'NL', 'weekday': 2}

mlmodel.learn_one(data, 'test')
```

**Comment by MaxHalford** [comment]
Hello there!

There are a couple of things that are wrong with what you're doing. I'm actually curious what you're expecting to happen? First of all `LogisticRegression` is a binary classifier, implying that the `y` value should be a `bool` and not `test` (which is a `str`). Also, it is meant to process numeric values only, so you can't pass `str` features like you did.

You could either one-hot encode all your features:

```py
mlmodel = compose.Pipeline(
    compose.Select('customer', 'postal', 'city', 'country', 'weekday'),
    preprocessing.OneHotEncoder(),
    linear_model.LogisticRegression(optimizer=optim.SGD(0.001))
)

data = {'customer': 'GLS Spaanse Polder 1091', 'postal': '3044EW', 'city': 'Rotterdam', 'country': 'NL', 'weekday': 2}

mlmodel.learn_one(data, 1)
```

Or only one-hot encode the strings:

```py
mlmodel = compose.Pipeline(
    (
        (
            compose.Select('customer', 'postal', 'city', 'country') |
            preprocessing.OneHotEncoder()
        ) +
        (
            compose.Select('weekday') |
            preprocessing.StandardScaler()
        )
    ) |
    linear_model.LogisticRegression(optimizer=optim.SGD(0.001))
)

data = {'customer': 'GLS Spaanse Polder 1091', 'postal': '3044EW', 'city': 'Rotterdam', 'country': 'NL', 'weekday': 2}

mlmodel.learn_one(data, 1)
```

I hope that brings some clarity!

**Comment by rj76** [comment]
Hi Max,

Thank you for your answer. I figured I'd try something like the example of the [bikes](https://riverml.xyz/latest/examples/bike-sharing-forecasting/), but with different data. There just uses `compose.Select`, `preprocessing.StandardScaler` (which I thought to be weird), and then `linear_model.LinearRegression`.

Sorry for this noob question :)
