### ISSUE TITLE
Implement new changepoint detection models

### ISSUE THREAD

**Issue by anlarro** [online-ml/river#836]
I found that some univariate drift detectors are implemented in RIVER. I wonder if you're planning to implement other well known detectors like the [Bayesian Online Chagepoint Detector (BOCD)](https://arxiv.org/abs/0710.3742) and/or other multivariate variants such as: [MF-BOCD](https://arxiv.org/abs/2103.14224) or [SB-BOCD](https://dl.acm.org/doi/10.1145/3459637.3482167).

How can I implement / integrate these or any similar model into RIVER?

**Comment by MaxHalford** [comment]
Hey there! Thanks for the interest.

We're definitely open to new implementations. In particular, the BOCD method seems to be well established, judging from its number of citations. I would probably start with that one, and implement other flavors/variants in a subsequent step.

In general, I would say that the drift detection module needs some love and ownership. For instance, it would be great to define some [tracks](https://github.com/online-ml/river/blob/main/river/evaluate/tracks.py) to evaluate drift detection methods. The API in itself can also be challenged if necessary, as it was mostly imported from scikit-multiflow "as is" without any modifications.

We're a bit stretched on resources, so feel free to take ownership of this part of the codebase. If you just want to introduce a new method, then that's more fine of course :). Every little helps.

**Comment by MaxHalford** [comment]
Added a card [here](https://www.notion.so/d1e86fcdf21e4deda16eedab2b3361fb?v=503f44740b8b44a99a961aa96e9e46e1).

**Comment by smastelini** [comment]
+1 to adding these algorithms. 

It will be great to see multivariate detectors in River. 

As far as I'm concerned, the main challenge API-wise, was to unify an interface to cope with detectors that have both warning and drift signals and those that only detect drifts.

I think the current state is fairly generic, but with the addition of more detectors the API might evolve. Maybe become more similar to what we have in `stats`.
