### ISSUE TITLE
unsupported operand type(s) for -: 'str' and 'float'

### ISSUE THREAD

**Issue by vishmonika98** [online-ml/river#859]
![Screenshot (40)](https://user-images.githubusercontent.com/36053063/155672325-f98b8cdc-6fdf-4dbd-b79f-72480f93afb6.png)
![Screenshot (39)](https://user-images.githubusercontent.com/36053063/155672333-f11411cf-51ec-448c-bbfa-572fce7123f0.png)
Please help to resolve this problem 

<ipython-input-3-81f1436ab933> in <module>
      2 
      3 for x, y in X_y:
----> 4     y_pred = model.predict_one(x)      # make a prediction
      5     metric = metric.update(y, y_pred)  # update the metric
      6     model = model.fit_one(x, y)        # make the model learn

~\anaconda3\lib\site-packages\river\compose\pipeline.py in predict_one(self, x, learn_unsupervised)
    396 
    397         """
--> 398         x, final_step = self._transform_one(x=x, learn_unsupervised=learn_unsupervised)
    399         return final_step.predict_one(x=x)
    400 

~\anaconda3\lib\site-packages\river\compose\pipeline.py in _transform_one(self, x, learn_unsupervised)
    361 
    362             elif not t._supervised and learn_unsupervised:
--> 363                 t.learn_one(x=x)
    364 
    365             x = t.transform_one(x=x)

~\anaconda3\lib\site-packages\river\preprocessing\scale.py in learn_one(self, x)
    153             self.counts[i] += 1
    154             old_mean = self.means[i]
--> 155             self.means[i] += (xi - old_mean) / self.counts[i]
    156             self.vars[i] += (
    157                 (xi - old_mean) * (xi - self.means[i]) - self.vars[i]

TypeError: unsupported operand type(s) for -: 'str' and 'float'

**Comment by MaxHalford** [comment]
I'm sorry but I can't reproduce this bug. I can't copy/paste from a screenshot. I could either tils 2032 when we develop that technology, or I'll wait for you to produce a [minimal, producible example](https://stackoverflow.com/help/minimal-reproducible-example) :)

Also, saying hello or even just expressing a few words goes a long way in starting a good relationship. You can't just throw a screenshot and some messy, partial copy/paste at us and expect us to do the legwork for you.

**Comment by vishmonika98** [comment]
I tried to solve the problem, but new issues come with this river and creme package every time. Because it can handle some specific type of data (phishing data). Every dataset has different properties. Due to the lack of documentation, challenging to use this package. In this article,  https://pyimagesearch.com/2019/06/17/online-incremental-learning-with-keras-and-creme/, They mentioned the datatype should be converted into float.
