### ISSUE TITLE
Potential bug in vector matrix multiplication of dotvecmat

### ISSUE THREAD

**Issue by Leo-VK** [online-ml/river#863]
## Versions

**river version**: 0.7.0
**Python version**: 3.7.10
**Operating system**: Windows

## Describe the bug

Hi everyone

I was experimenting with the math.utils functions and came across the function _dotvecmat_. I think there seems to be an issue with the index for the _get_-method of the new dictionary. Down below I provided a simple example with a matrix having all entries set to 1 and a vector having all entries set to one. According to vector matrix multiplication I would expect a vector with two entries of 2, instead the function returns a vector with two entries of threes. Am I missing something?

If instead I change the index of the _get_ method in _dotvecmat_ to the column index _k_ in following way

`line 95: C[k] = C.get(k, 0.0) + xi * ai`

the multiplication returns the expected result.

## Steps/code to reproduce

```python
from river import utils
A = {(0,0) : 1, (0,1) : 1, (1,0) : 1, (1,1) : 1}
v = {0: 1, 1: 1}

result = utils.math.dotvecmat(v, A)
print(result)    # output is {0: 3.0, 1: 3.0}, but expected would be a vector of {0: 2.0, 1: 2.0}
```

**Comment by MaxHalford** [comment]
I confirm this is a bug. Good catch! I suggest you make a pull request. Ideally, it would be nice to add a couple of unit tests. Either as doctests, or with unit tests with a comparison to numpy, or both.
