### ISSUE TITLE
a question on denstream#887

### ISSUE THREAD

**Issue by sherrypie077** [online-ml/river#892]
I got a question about def _merge: "creat a new o-micro-cluster" is under the condition "if not merged_status and len(self.o_micro_clusters)! = 0", so the point can not creat a new omc if there is no omc before?
Thanks a lot!

**Comment by smastelini** [comment]
Pinging @hoanganhngo610!

**Comment by hoanganhngo610** [comment]
@sherrypie077 Sorry for such a late response! Indeed, we forgot to take this situation into account, and given that the function `_get_closest_cluster_key()` only works when the `self.o_micro_clusters` are not empty. Would make an update on the code ASAP!
@smastelini @MaxHalford pinging for acknowledgement!

**Comment by hoanganhngo610** [comment]
@sherrypie077 This problem has been solved in PR #898 as seen above. Please feel free to leave any comments or concerns remaining!

**Comment by hoanganhngo610** [comment]
Close issue as it is fully solved!

**Comment by sherrypie077** [comment]
Thanks for solving this!
