### ISSUE TITLE
Question about multi-output regression with MLPRegressor

### ISSUE THREAD

**Issue by beinathan** [online-ml/river#897]
Hi, I'm a online-ml starter, and I have a question, as for a multi-output regression situation with MLPRegressor, each feature has been a numeric type, When I run the following statement, there is a problem, how to deal with it?
**evaluate.progressive_val_score(dataset, model, metric)
TypeError: unsupported operand type(s) for -: 'dict' and 'int'**
[usv_data.csv](https://github.com/online-ml/river/files/8380180/usv_data.csv)
The attached file is a dataset that I copied from River's dataset format.

**Comment by VaysseRobin** [comment]
Hello, 

I think that there is 2 problems:
- You are using `metrics.MAE` which is a metric for regression (not multi output regression) so, you should use something like `metric = metrics.multioutput.MacroAverage(metrics.MAE())` which compute the mean of the 3 MAE (one for each output)

- The second problem is from our side. MLPRegressor inherit from `base.Regressor`, so when it is applied to Multi output regression, the MacroAverage metric will not recognize the model. Furthemore, by using `progressive_val_score` on MLPRegressor, the model will be initialised as a Regressor model. I'm not sure what would be the best solution to fix this, but I recommend you not using progressive_val_score with MLPRegressor for Multi Ouput Regression.

Here is a minimal working exemple with `progressive_val_score` (assuming `usv_data.csv` is in the same directory as the script).
```python
from river import evaluate
from river import neural_net as nn
from river import optim
from river import preprocessing as pp
from river import metrics
from river import stream

from river import base

class MultiOutputMLP(base.MultiOutputMixin, nn.MLPRegressor):
    pass

dataset=stream.iter_csv(
            "usv_data.csv",
            target=["out_0", "out_1", "out_2"],
            converters={
                "number": int,
                "u": float,
                "v": float,
                "r": float,
                "tau_u": float,
                "tau_v": float,
                "tau_r": float,
                "out_0": float,
                "out_1": float,
                "out_2": float}
            )


model = (pp.StandardScaler() | 
         MultiOutputMLP(
            hidden_dims=(5,),
            activations=(
                nn.activations.ReLU,
                nn.activations.ReLU,
                nn.activations.Identity
            ),
            optimizer=optim.SGD(1e-3),
            seed=42
        ))
metric = metrics.multioutput.MacroAverage(metrics.MAE())

# Learn on the first example in order to initialize the model with the 
# good number of output
for x, y in dataset:
    model.learn_one(x, y)
    break

a = evaluate.progressive_val_score(dataset, model, metric)
print(a)
```

**Comment by beinathan** [comment]
Thank you very much sir, but I have another problem with the above code when I try to run it.
**ValueError: MacroAverage metric is not compatible with StandardScaler | MLPRegressor**
Could you briefly introduce the use of the | operator, in the tutorial, I haven't seen percise description of this part.

**Comment by VaysseRobin** [comment]
Check my example, I replaced `MLPRegressor` with `MultiOutputMLP` which I created in order to have a Multi Output version of `MLPRegressor`.

For a detailed explanation of Pipelines, I recommend you this : https://riverml.xyz/latest/user-guide/pipelines/

**Comment by beinathan** [comment]
Thanks for your patience, my problem was solved.

**Comment by smastelini** [comment]
Closing it!
