### ISSUE TITLE
`RollingQuantile` and `Quantile` output difference for similar input data

### ISSUE THREAD

**Issue by fox-ds** [online-ml/river#905]
## Versions

**river version**: 0.10.1
**Python version**: Python 3.10.2
**Operating system**: Fedora Linux 35

## Describe the bug
The output of `RollingQuantile` and `Quantile` differs with similar inputs and a window that is not full. This should as far as I know result in the same value. Maybe a test can be added to validate this for other `Rolling*` variants as well.

## Steps/code to reproduce

```python
from river.stats import RollingQuantile, Quantile

data = list()
data.extend([3] * 20_000)
data.extend([2] * 10_000)
data.extend([1] * 1_000)
data.extend([6] * 10)
data.extend([7] * 10)
data.extend([8] * 10)
data.extend([9] * 10)

q = 0.997

rolling_q = RollingQuantile(window_size=1_000_000, q=q)
regular_q = Quantile(q=q)

for x in data:
    rolling_q.update(x)
    regular_q.update(x)

result1 = rolling_q.get()
result2 = regular_q.get()

assert result1 == result2

```

**Comment by MaxHalford** [comment]
This is expected.

`RollingQuantile` is exact. It maintains the values in memory and searches for the quantity in a greedy manner. It should produce the same results as numpy.

`Quantile` implements an approximate algorithm. The idea is that it compresses the data into a data structure will a smaller memory footprint. Right now I believe it uses the P-square algorithm. There's a whole literature around these approximate data structure for measuring statistics.

I agree that this isn't super clear. We should add some note in the documentation. You're welcome to open a pull request :)

**Comment by fox-ds** [comment]
Thanks for the explanation! I think we'll also cover this in #906, so I'll close this issue.
