### ISSUE TITLE
Question about making a prediction into the unknown future

### ISSUE THREAD

**Issue by emreguenduez** [online-ml/river#916]
Hey, how would I go about creating a model and training it with data that is available until today and use it to predict data about the next n hours (e.g. 96 hours)? I used the code in the [examples page in the documentation](https://riverml.xyz/latest/examples/building-a-simple-nowcasting-model/) to make predictions on the current data itself but I'm not quite sure how I can apply it to make forecasts about the unknown future (future for which I have no data). Do I need to change the input dataset?

This is the code I used:

```python
from river import compose
from river import linear_model
from river import preprocessing


def get_ordinal_date(x):
    return {'ordinal_date': x['month'].toordinal()}


model = compose.Pipeline(
    ('ordinal_date', compose.FuncTransformer(get_ordinal_date)),
    ('scale', preprocessing.StandardScaler()),
    ('lin_reg', linear_model.LinearRegression())
)

from river import metrics
import matplotlib.pyplot as plt


def evaluate_model(model): 

    metric = metrics.Rolling(metrics.MAE(), 12)

    dates = []
    y_trues = []
    y_preds = []

    for x, y in datasets.AirlinePassengers():

        # Obtain the prior prediction and update the model in one go
        y_pred = model.predict_one(x)
        model.learn_one(x, y)

        # Update the error metric
        metric.update(y, y_pred)

        # Store the true value and the prediction
        dates.append(x['month'])
        y_trues.append(y)
        y_preds.append(y_pred)

    # Plot the results
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.grid(alpha=0.75)
    ax.plot(dates, y_trues, lw=3, color='#2ecc71', alpha=0.8, label='Ground truth')
    ax.plot(dates, y_preds, lw=3, color='#e74c3c', alpha=0.8, label='Prediction')
    ax.legend()
    ax.set_title(metric)
```

Thanks in advance.

**Comment by MaxHalford** [comment]
Hey there!

It depends how you frame it. In your example you should create observations which describe the future. You do this by creating features. For instance, just create a dict with `{'ordinal_date': <desired_month>}` and pass it through the model's `predict_one` method.

Basically, it doesn't matter if it's the past or the future you're referring to, it's just dictionaries of features that you pass through the models. 

An alternative is to use the models in the `time_series` module. They have a `forecast` method which does most of the work for you.

**Comment by emreguenduez** [comment]
Hey @MaxHalford! Thanks for the reply, and sorry for my late response, I was out of the office. I created a `pandas DataFrame`with dates as the future dates and used that with the `stream.iter_pandas` method, which worked like you said! Thanks a lot!
