### ISSUE TITLE
One-hot Encoded Features

### ISSUE THREAD

**Issue by numersoz** [online-ml/river#930]
I'm using regression with one-hot encoded features on time-series data.

This feature represents the area code the vessel operates in. There are about 5 different areas.

Model totally fails when this feature is introduced. Without it, I get 0.91 R2. This feature significantly improves regular regression, thus I wanted to introduce it to RiverML as well. 

My theory is, as it takes long time for the model to realize other areas exists, it doesn't get adjust to this fact. Coefficients always stays at zero thus wrong predictions are made. Regular regression works well and better with this feature.

This seems like a limitation to RiverML and not sure if there is a way around it.

**Comment by MaxHalford** [comment]
Hey! Difficult to say why introducing this feature makes your model fail without any code. Maybe your data is ordered by area?

**Comment by numersoz** [comment]
Hi, 

Think of it this way.

Say I convert 1 categorical feature into 10 features with one hot encoding (10 unique values).

For the first 2-3 months of data coming in (at 1 hour sample rate), only few of the features are non-zero. Thus, coefficient of the other features is near zero. When suddenly the incoming data has non-zero for those features, during prediction there is high error because model hasn't adjusted to increase the weight of the coefficients for those features yet. 

I'll try to replicate this and share.

This feature represents the sea area code ship operates in. You can image a ship being in the Caribbean for 6 months and later 6 months in Europe. Maybe due to the nature of steaming ML, this kind of feature should not be used.

**Comment by MaxHalford** [comment]
Indeed, it sounds like there's not much to do. It's normal that a model has a lower performance when such drift occurs. But it will eventually learn and improve.

The ideal thing to do would be to detect this feature drift, and fallback to conservative predictions when it occurs, while allowing the model to keep learning in the background. But we don't have cookie cutter tools to do this, yet.
