### ISSUE TITLE
How to use conditionals in composed pipelines

### ISSUE THREAD

**Issue by dberardo-com** [online-ml/river#931]
My use case is the following: i want to use an ARIMA model to do timeseries forcasting, but i dont want outliers to "pollute" the forecast quality. Those outliers are usally bad sampled data deriving from bad sensor settings or maintenance and are in generally easy to figure out (sudden drops in values, or so)

So the idea would be to use pipe an anomaly detector before the arima model and when an anomaly is detected then the model.learn function is not called.

Sure enough i could implement those  2 models as independent models and an if/else statement in betwee, but i was wondering if it is possible to have all of it into a single pipeline.

Like:
```
StandardScaler --> AnomaliesDetector --> Thresholder -->  If(isNotAnomaly) --------- true -----> ArimaModel --> done
                                                               |----- false ------> skip learning
  ````                                                                                                            
Is this possible in river ?

**Comment by MaxHalford** [comment]
That's a really good use case, and something other people have mentioned to me. Right now there's no way to do this via a pipeline, but it's definitely something we could add :). By any chance, do you have a dataset you can share? If so I could get this done very soon.

**Comment by dberardo-com** [comment]
i dont have a complete dataset, but an example of timeseries / vector. Do you have any requirements on the quality of a dataset and its minimum/desired size?

also, for easeing the research of such kind of issues, would you mind adding a tag to both this issue and the other ones you were referring to where the discussion was started already? i would like to have a look.

Maybe a tag like Feature::Pipelines (i use gitlab so i am used to scoped "::" tag labels, maybe there are better standards on github)

**Comment by dberardo-com** [comment]
here an example of such a vector, the green line is the measured data, and the red line is the SARIMAX model that struggles to fit it:

![image](https://user-images.githubusercontent.com/65530457/168750934-b7b7e975-310c-4c96-9062-d8561b2bb139.png)

in this case i know that the dropdown in the greenline are due to human intervention and are controlled, but they can be regarded as anomalies for the sake of predicting the normal behavior of the signal and thus should not be considered in the forecast

**Comment by MaxHalford** [comment]
> i dont have a complete dataset, but an example of timeseries / vector. Do you have any requirements on the quality of a dataset and its minimum/desired size?

Ideally we want to create a dataset in the `datasets` module. The dataset you've shared in the screenshot looks really good :). How big is it?

> also, for easeing the research of such kind of issues, would you mind adding a tag to both this issue and the other ones you were referring to where the discussion was started already? i would like to have a look.

I'll try to yes, but I can't remember where those other discussions are. There were not in-depth anyway, it's just something people mentioned passing by. I know exactly what to do so I can take care of implementing this, don't worry :)

**Comment by dberardo-com** [comment]
On the dataset:

- are you asking for a whole dataset (multiple, perhaps correlated vectors) or just a single vector (like in the picture)?
- i cannot provide many years of "clean" data, but i could provide e.g. 2+ months in 1 minute/1hour/1day resolution, as you required. Or i could even provide unsampled data, meaning that you will get no regular timestamps, like minutes, etc. but then you would perhaps need to aggregate that in the script

> I'll try to yes, but I can't remember where those other discussions are. There were not in-depth anyway, it's just something people mentioned passing by. I know exactly what to do so I can take care of implementing this, don't worry :)

I was trying to make the point that using labels could be useful a-posteriori :D

**Comment by MaxHalford** [comment]
> are you asking for a whole dataset (multiple, perhaps correlated vectors) or just a single vector (like in the picture)?

I guess a single vector would be good to start with. Basically I think to think to being there's value in implementing a simple solution which solves your problem.

> i cannot provide many years of "clean" data, but i could provide e.g. 2+ months in 1 minute/1hour/1day resolution, as you required. Or i could even provide unsampled data, meaning that you will get no regular timestamps, like minutes, etc. but then you would perhaps need to aggregate that in the script

An hourly dataset sounds like the right size for a toy dataset to being with :)

**Comment by dberardo-com** [comment]
good, let me check that. Should i upload it in here or send you an email?

**Comment by MaxHalford** [comment]
You can me an email at maxhalford25@gmail.com :)

**Comment by dberardo-com** [comment]
great, in the meantime i tag here @izzyhd for generic interest on the topic (research)

**Comment by dberardo-com** [comment]
While this issue is being worked out, a question related to forecasting: do you suggest any good python "calendar" library for generating flags on national holidays to add to the forecasted features ? or does river already implement any?

@MaxHalford

**Comment by MaxHalford** [comment]
As soon as possible ideally. But there's still one unit test that's failing, and I also want to investigate the issue some people are having with regards to some specific numpy versions. In the meantime you can install the development version directly from GitHub.

**Comment by dberardo-com** [comment]
alright, that is not possible via pip right? it should be an installation from source, correct?

**Comment by MaxHalford** [comment]
I'm on my phone so I can't give you details instructions. It actually happens with pip, it's just that you have to tell pip to install from sources on GitHub. There are I strictions in the installation section in the docs.

**Comment by dberardo-com** [comment]
great
`pip install git+https://github.com/online-ml/river.git@73279f0fb95b550ab32aea81decf8eb691b7a9c5`

**Comment by MaxHalford** [comment]
Closing this for now :)
