### ISSUE TITLE
'function' object has no attribute 'StandardScaler'

### ISSUE THREAD

**Issue by emreguenduez** [online-ml/river#979]
**RIVER VERSION: 0.11.1**
**PYTHON VERSION: 3.9.12**

The code works as expected on my main system. However, when I try to run it on the remote desktop that is connected to the main database, I get this error: **'function' object has no attribute 'StandardScaler'**. Everything about the code is the same. What could be the reason for this? I am using jupyter on both of the computers. 

Code:
```py
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta
from river import compose
from river import linear_model
from river import metrics
from river import preprocessing
from river import stream
from river import ensemble
from river import optim
from river import time_series

import psycopg2
import pandas.io.sql as psql
import pickle

def riverFirstLearning(df, forecastPeriod, filename):

    # upper part of the function

    model = (
        extract_features |
        time_series.SNARIMAX( 
            p = 0,
            d = 0,   # no need to do differencing as the series is already stationary
            q = 1,
            m = 365, # daily seasonality
            sp = 3,
            sq =365,
            regressor = (
                preprocessing.StandardScaler() |
                linear_model.LinearRegression(
                    intercept_init = 500,
                    optimizer=optim.Adam(),
                    intercept_lr = 0.01
                )
            )
        )
    )
    
    metric = metrics.Rolling(metrics.MAE(), 24*15)

    # Train Test Split part

    for xi, yi in stream.iter_pandas(x_train, y_train):
        y_pred = model.forecast(horizon = 1, xs = [xi])
        model = model.learn_one(xi, yi)
        metric = metric.update(yi, y_pred[0])
        
    pickle.dump(model, open(filename, 'wb'))
```

And this is the output on my main computer, where the code works properly. 

![image](https://user-images.githubusercontent.com/79257400/177110780-58520ecb-9eef-4a7f-a0a8-9c0fa21579b7.png)

**Comment by MaxHalford** [comment]
Hey there. Hard to tell really. Maybe you've called something `preprocessing` and that's taking precedence over River's `preprocessing` module? A trick I sometimes use is to put the imports into the function that loads the model.

**Comment by emreguenduez** [comment]
You were absolutely right! First I checked if i had imported any other module with the same name but I completely forgot about a custom function with the same name. Sorry for the bother over something like this. Thanks a lot!
