### ISSUE TITLE
VotingClassifier bug

### ISSUE THREAD

**Issue by ercangunbilek** [online-ml/river#994]
## Versions

**river version**:
**Python version**:
**Operating system**:

## Steps/code to reproduce

```python
# Sample code to reproduce the problem
# Please do your best to provide a Minimal, Reproducible Example: https://stackoverflow.com/help/minimal-reproducible-example
```

**Comment by ercangunbilek** [comment]
![Capture](https://user-images.githubusercontent.com/33091962/181719604-aaba2815-52ac-4f51-a541-9ec7cd81bf93.PNG)
While i am using ensemble.VotingClassifier , i had error.

**Comment by MaxHalford** [comment]
Can you please follow the issue template? It's not there for nothing. For instance we need a piece of code we can copy/paste to debug. We can't help you with the information you gave us.
